### ISSUE TITLE
feature request: clearer error when saving a buffer with copied file that isn't renamed

### ISSUE THREAD

**Issue by maxh** [stevearc/oil.nvim#101]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

When I copy a file but don't rename it, I can edit the file by selecting either instance of the filename and making changes. Then when I `:wa` to save the changed file (and the oil buffer) I get an error:

```
Error detected while processing BufWriteCmd Autocommands for "oil://*":                                                      
Error parsing oil buffers  
```

### Provide background

This doesn't happen to me in practice but I happened to run into it while doing user acceptance testing for https://github.com/stevearc/oil.nvim/issues/93.

**Comment by stevearc** [comment]
This is expected. You cannot have two files with the same name in the same directory. There is an error notification and there should also be an error diagnostic that appears in the oil directory on the line of the duplicated file.

**Comment by maxh** [comment]
Understood -- the suggestion was to make the error more clear in the case where the buffer is not visible. But it's not a big deal.
