### ISSUE TITLE
bug: `get_current_dir` returns nil

### ISSUE THREAD

**Issue by ssiyad** [stevearc/oil.nvim#102]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

MacOS 13.3.1

### Describe the bug

`oil.get_current_dir()` is supposed to return current directory of buffer, but doesn't.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/28098330/237051340-0f6481a7-3539-43f9-9c90-61cf3c6555cd.png">

### Steps To Reproduce

`vim.print(require("oil").get_current_dir())`

### Expected Behavior

Current directory string

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
`oil.get_current_dir()` will return the directory _of the current oil buffer_. If you are not in an oil buffer, it will return nil. If you are in an oil buffer with no local directory (e.g. oil-ssh://my.server.com/path/to/file), it will return nil.

If you want the directory containing the current file use `vim.fn.expand("%:p:h")` (see `:help expand()`)
