### ISSUE TITLE
bug: vim.opt.hidden = false produce unexpected behavior of oil

### ISSUE THREAD

**Issue by timsofteng** [stevearc/oil.nvim#104]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Alpine Linux Edge

### Describe the bug

I see error message when I jump between folders with `ctrl-o` and `ctrl-i`.
I guess it is because if have `vim.opt.hidden = false`
Is it possible to make it work with hidden false? Or may I set hidden false just for Oil buffers?

![image](https://github.com/stevearc/oil.nvim/assets/51912173/a7afb452-3174-494f-bd85-f5f9c0c65138)

In addition cutting and pasting files on different levels is near impossible with hidden = true too.
![image](https://github.com/stevearc/oil.nvim/assets/51912173/743f42bd-8290-48f9-8892-af6cec161806)

### Steps To Reproduce

Just back and fourth throw two different folders.

### Expected Behavior

Jumping between dirs should work without error message. Would be cool to have workaround for vim.opt.hidden.true too.

### Directory structure

a/some.file
some-other.file

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Sounds like you want to set `bufhidden = "hide"`. You can do this yourself, but I think it also makes sense to set this by default.
