### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by gsa9** [stevearc/oil.nvim#107]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-361+ge3e6fadfd-Homebrew

### Operating system/version

MacOS 13.3.1 (a) (22E772610a)

### Describe the bug

oil buffers as I was able to open and display in 'pseudo-tabs' by the plugin 'ap/vim-buftabline' are not restored between nvim sessions (exit and then reopen nvim) by 'Shatur/neovim-session-manager'.
I am setting buflisted = true, even though I am not sure it would be needed for this.

-- Buffer-local options to use for oil buffers
  buf_options = {
    buflisted = true, -- default is false
    bufhidden = "hide",
  },

### Steps To Reproduce

1. nvim -u repro.lua
2. :edit file.txt, which opens buffer in a new 'tab', and new 'Session' is saved (by 'ap/vim-buftabline')
3. edit and save file.txt
4. I beleive a default Session is now created automatically by 'Shatur/neovim-session-manager'
5. press '-' for keymap .. require("oil").open, { desc = 'Open parent directory' ..
6. the oil buffer opens, but no new 'tab' is opened for it, which would be desirable in my case
7. now if I press "-" for .. actions.parent, oil opens parent dir in a new 'tab' (this time it does, great!)
8. :qa, to quit nvim
9. nvim -u repro.lua, opens nvim restoring my default Session (session was created automatically by 'Shatur/neovim-session-manager' in step 3)
10. only file.txt 'tab' is restored, the oil-buffer-tab isn't

Edit:
After removing 'icon' from 'colums', like so:
  {
    'stevearc/oil.nvim',
    config = function()
      require("oil").setup({
        -- See :help oil-columns
        columns = {
          -- "icon",
          -- "type",
          -- "permissions",
          -- "size",
          -- "mtime",
        },
        -- Buffer-local options to use for oil buffers
        buf_options = {
          buflisted = true,           -- default is false
          bufhidden = "hide"
        }
      })
    end
  }

... now these are the new
Steps To Reproduce:

1. nvim -u repro.lua
2. :edit file.txt, which opens buffer in a new 'tab', and new 'Session' is saved (by 'ap/vim-buftabline')
3. edit and save file.txt
4. I beleive a default Session is now created automatically by 'Shatur/neovim-session-manager'
5. press '-' for keymap .. require("oil").open, { desc = 'Open parent directory' ..
6. the oil buffer opens in a new 'tab', (great!)
7. :qa, to quit nvim
8. nvim -u repro.lua, re-opens nvim, restoring my default Session (session was created automatically by 'Shatur/neovim-session-manager' in step 3)
9. only file.txt 'tab' is restored, the oil-buffer-tab isn't

### Expected Behavior

Main expectation: I wish all the oil 'buffer-tabs' I had open in my previous default Session were preserved and restored after exiting and reopening nvim.

Side effect: it is strange that removing 'icon' from 'columns' in oil setup would make a difference in the behaviour of the require("oil").open function in the '-' keymap. But in my case, it is much better now since it has the desired effect (for my buftab workflow) of creating a new 'tab' with the new oil buffer.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
              -- Buffer-local options to use for oil buffers
              buf_options = {
                buflisted = true, -- default is false
                bufhidden = "hide",
              },
            })
        end,
  },
  -- add any other plugins here
  { "Shatur/neovim-session-manager", dependencies = { "nvim-lua/plenary.nvim" } },
  'ap/vim-buftabline',
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.keymap.set("n", "-", require("oil").open, { desc = 'Open parent directory' })
```

And my edited Repro is:

```
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    'stevearc/oil.nvim',
    -- dependencies = { "nvim-tree/nvim-web-devicons" },   -- optional
    config = function()
      require("oil").setup({
        -- See :help oil-columns
        columns = {
          -- "icon",
          -- "type",
          -- "permissions",
          -- "size",
          -- "mtime",
        },
        -- Buffer-local options to use for oil buffers
        buf_options = {
          buflisted = true,           -- default is false
          bufhidden = "hide"
        }
      })
    end
  },
  -- add any other plugins here
  { "Shatur/neovim-session-manager", dependencies = { "nvim-lua/plenary.nvim" } },
  'ap/vim-buftabline',
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.keymap.set("n", "-", require("oil").open, { desc = 'Open parent directory' })
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Whether or not the oil buffer is displayed in the tabline is entirely determined by the `vim-buftabline` plugin. I can't speak to that plugin, but most bufferlines only display buffers with `buflisted = true`, which is why you see the difference after changing that option.

As for the restoring of the oil buffer, that sounds like an issue with the session plugin. I don't know what it's doing under the hood, but I can confirm that saving and restoring oil buffers works fine with `:mksession`. You can see this for yourself by opening oil and running `:mksession session.vim`, then restart vim and run `:source session.vim`. Try reporting an issue on the `neovim-session-manager` repo.
