### ISSUE TITLE
feature request: Support other trash commands

### ISSUE THREAD

**Issue by fbearoff** [stevearc/oil.nvim#110]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

There are several other programs that provide a trash bin such as [trash-d](https://github.com/rushsteve1/trash-d) that use commands other than `trash-put`. It would be nice to have an option to configure what the trash command is i.e.:

```lua
delete_to_trash = true,
trash_command = "trash"
```

**Comment by stevearc** [comment]
Done!
