### ISSUE TITLE
feature request: Open multiple files only in the buffer

### ISSUE THREAD

**Issue by haru02w** [stevearc/oil.nvim#111]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

When I select a lot of files and run "action.select", a lot of vsplits are made. 
I really would like to open the first file and load all other in buffers.

**Comment by stevearc** [comment]
I like this idea and I will get to it when I get a chance. My schedule has been and will continue to be a bit nuts, so it might take a while

**Comment by stevearc** [comment]
Upon review, I don't think this requires any API changes, which makes this quite a bit easier. This should be the default behavior now; anyone that wants the old behavior can use the default `<C-s>` mapping or create their own mapping that calls `oil.select({vertical = true})`.

**Comment by qixiao986** [comment]
can we select multiple files that are not continuous in the file list? I only know we can select file in visule mode, which can only select files that are continuous.

**Comment by qixiao986** [comment]
@stevearc good advice and Oil is a great plugin. Thanks.
