### ISSUE TITLE
bug: Oil seems to stuck in error state and not usable if we try to switch buffer not saving changes in oil

### ISSUE THREAD

**Issue by sultanahamer** [stevearc/oil.nvim#113]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Macos 12.6.6

### Describe the bug

Oil becomes  unusable if after editing Oil window with lets say adding a new file and then without saving it, trying to switch to a different buffer. In this case, I tried opening Telescope old_files picker. My autosave could be the culprit here.

![image](https://github.com/stevearc/oil.nvim/assets/11389059/fb5a52ed-19bd-47d5-a6cb-fe674d5c97aa)

I think the problem here is that, I am using vim auto save plugin(Plug '907th/vim-auto-save') and it auto saves buffers on particular events
and here is my config for the same
```
vim.g.auto_save = 1 -- enable AutoSave on Vim startup
vim.g.auto_save_events = { "FocusLost", "TabLeave", "WinLeave", "BufLeave" }
```
Here are the autocommands created by that plugin
![image](https://github.com/stevearc/oil.nvim/assets/11389059/bcc102f1-f113-4888-bd42-8d3283ea2af9)

### Steps To Reproduce

Keystrokes to reproduce:
:Oil 
o abc.txt
ctrl [
:Telescope find_files

### Expected Behavior

At present there seems to be a lock because user needs to answer the dialog, do you want to create file abc.txt and as that window disappears, the save function is locked as happening and it won't allow for next action. We can probably have some timeout and ignore it or on cancellation of the popup window, we can cancel the save operation

### Repro

```Lua
Not filling this as it would entail, adding plugin manager, plugins etc. Hope the above plugin information and the plugin config suffices
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
I'll add a `pcall` to guard against failures here, but it's still going to display an error. I would recommend disabling your auto-save plugin on oil buffers. Automatically committing file mutations doesn't sound like a good idea.
