### ISSUE TITLE
feature request: Allow for configuring prompt keywords for accepting change

### ISSUE THREAD

**Issue by hkupty** [stevearc/oil.nvim#114]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like the ability to configure oil to prompt me with `[Y]es`/`[N]o` instead of `[O]k`/`[C]ancel`.

I searched but I couldn't find anything on that, so sorry if I'm asking for something that exists already..

The reason for that is so it matches the default (and usual muscle memory) of `y` for accepting instead of `o`.
I've noticed that for several times I've got stuck with the cursor pending because I pressed `o` in the confirmation screen when it should've been `o` instead.

Of course, leaving that as a configuration as I believe some people are already used to `o`/`c` :)

**Comment by stevearc** [comment]
It's easy enough to add a mapping for `y`

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "oil_preview",
  callback = function(params)
    vim.keymap.set("n", "y", "o", { buffer = params.buf, remap = true, nowait = true })
  end,
})
```
