### ISSUE TITLE
feature request: Support command modifiers

### ISSUE THREAD

**Issue by MisanthropicBit** [stevearc/oil.nvim#116]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

The `:Oil` command should support command modifiers for splitting windows so you can do e.g. `:tab Oil .` or `:vertical Oil .`.

### Provide background

Vim commands that split a window can be prefixed by command modifiers such as `tab` or `vertical`. This is pretty neat since you can do `:tab Command args` to open the window in a new tab. The table argument passed to the function of `nvim_create_user_command` contains a `mods` string which is the command modifiers that can be prefixed to a underlying command that splits the window.

However, executing something like `:tab Oil .` does not open oil in a new tab but in the current window. I'd be happy to submit a PR 🙂

### Additional details

Thanks for this great plugin! I've since uninstalled the tree-based file explorer I was (rarely) using before and haven't looked back 🙂

**Comment by luathn** [comment]
I think you can use `:vs | Oil args` or `:tabnew | Oil args`.

**Comment by MisanthropicBit** [comment]
Thanks for the suggestion @luathn. Today I remembered that oil overrides the default file explorer so I can actually just do e.g. `tabe .` or `vert <dir>` and it will open in oil automagically so there's no need to support command modifiers for the `Oil` command itself.

**Comment by stevearc** [comment]
It's still a nice feature to support modifiers for the `:Oil` command, so I've added it
