### ISSUE TITLE
Question: How to disable file/inode id while searching?

### ISSUE THREAD

**Issue by skogler** [stevearc/oil.nvim#119]
First off, thanks for the awesome plugin, love it!

Now, I have this issue where oil shows a leading indicator of what I suspect is the file/inode id when I search in the buffer:

![image](https://github.com/stevearc/oil.nvim/assets/1032405/aa8ed95f-eb57-46af-b22b-1d3420c6aa72)

This behavior also shows in the screencast on the README, so I think it must be an intended feature.
I have no idea what to do with this information, so is there a way to turn it off? It is a bit irritating for me since it moves the text while searching.

**Comment by stevearc** [comment]
You're looking for `:help concealcursor`. If you look at the [config options](https://github.com/stevearc/oil.nvim/#options), it defaults to `"n"`. You probably want `"nc"` at least.

**Comment by skogler** [comment]
Thanks, that helped a lot! I did not realize what this was!

**Comment by cxreiff** [comment]
Just to save anybody who lands here and makes the same mistake I just did, concealcursor is local to window, so setting it directly in your init.vim will not work! oil.nvim has an `win_options.concealcursor` opt that will set this option specifically for oil.nvim buffers.
