### ISSUE TITLE
bug: breaks goto last editing position

### ISSUE THREAD

**Issue by herrvonvoid** [stevearc/oil.nvim#120]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Archlinux

### Describe the bug

I have this line in my config to go to the last editing position after opening a file: `autocmd BufReadPost * silent! normal! g'"zv`. This only works when I do not open a file with Oil. I believe with previous versions of Oil there was no problem...

### Steps To Reproduce

1. put `autocmd BufReadPost * silent! normal! g'"zv` in your config
2. open a file in nvim and edit a line which is not the first, then close nvim
3. open no, or a different file in nvim
4. use oil to open the file you previously edited
5. your cursor will be on the first line instead of the one you edited

### Expected Behavior

cursor on the line you edited last

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.cmd[[autocmd BufReadPost * silent! normal! g'"zv]]
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by davidsierradz** [comment]
Hi, I'm seeing something similar, but with a `FileType` autocommand that sets `'foldmethod'`:

```
augroup rest_fold
  autocmd!
  autocmd FileType rest setlocal foldmethod=expr
augroup end
```

If I open the file through oil, foldmethod is manual (the default), if opened through telescope or directly from the command line, it works as expected, also if I run `:edit` command after opening with oil.

**Comment by stevearc** [comment]
Can confirm this bug. It has to do with how we open buffers (in the `oil://path/to/file` format) and then rename them. I will definitely fix this, but it's going to require some tricky changes or potentially mild hacks to how we currently do things.

**Comment by stevearc** [comment]
I believe I found a fix without any terrible hacks. Give it a try and see if it resolves your issue

**Comment by herrvonvoid** [comment]
seems to work. thanks a lot!
