### ISSUE TITLE
bug: Error message when opening floating window with border "none"

### ISSUE THREAD

**Issue by luckasRanarison** [stevearc/oil.nvim#125]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Fedora 37

### Describe the bug

Opening floating window by using open_float() with "none" border in configuration causes an unexpected behaviour

E5108: Error executing lua .../luckas/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:339: BufWinEnter Autocommands for "*": Vim(append):Error executing lua callback: .../luckas/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:326: title requires border to be set
stack traceback:
	[C]: in function 'nvim_win_set_config'
	.../luckas/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:326: in function <.../luckas/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:321>
	[C]: in function 'edit'
	.../luckas/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:339: in function 'open_float'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'edit'
	.../luckas/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:339: in function 'open_float'
	[string ":lua"]:1: in main chunk

### Steps To Reproduce

1. nvim -u repro.lua (just changed border to "none")

### Expected Behavior

Floating window should open normally

### Directory structure

~/.config/nvim
~/Projects/mess 

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"stevearc/oil.nvim",
		config = function()
			require("oil").setup({
				float = {
					border = "none",
				},
			})
		end,
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Fixed! Thanks for the report
