### ISSUE TITLE
feature request: Shortcut for opening recent directoris by zoxide or telescope

### ISSUE THREAD

**Issue by fecet** [stevearc/oil.nvim#127]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Is there any methods to fast open recent dir, including oil-ssh?

**Comment by stevearc** [comment]
No, a fuzzy-finder and recency list is out of scope for oil. There is a user autocmd that you can use to track what directories are entered
https://github.com/stevearc/oil.nvim/blob/6f8bf067c09e96d6bff548b5e6addb6d9c25a678/lua/oil/view.lua#L340-L343

From that it should be possible to build & store a list and open it with your fuzzy-finder of choice.

**Comment by elmarsto** [comment]
Is anyone working on this? I'd be interested in working on this.

**Comment by humbornjo** [comment]
> Is anyone working on this? I'd be interested in working on this.

It can be achieved using [telescope-zoxide](https://github.com/jvgrootveld/telescope-zoxide)
Then change the default action from `vim.cmd.cd(selection.path)` to `require("oil").open(selection.path)`
