### ISSUE TITLE
bug: deletes and recreates directory links ending in /

### ISSUE THREAD

**Issue by herrvonvoid** [stevearc/oil.nvim#131]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.1

### Operating system/version

archlinux

### Describe the bug

sometimes when links to folders exist in the edited directory, when all you want is to create a new file foo, this happens:

CREATE foo
DELETE linkdir
CREATE linkdir -> dir

### Steps To Reproduce

1. mkdir dir
2. echo hello world >> dir/file
3. ln -s dir/ linkdir # important: the folder has to end in /
4. nvim -u repro.lua
5. :Oil 
6. Ofoo<esc>:w

### Expected Behavior

does not change the links

### Directory structure

repro.lua
dir
dir/file
linkdir -> dir/

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Fixed! Thanks for the report
