### ISSUE TITLE
bug: oil.nvim not working with ts-nvim-autotag and other plugins

### ISSUE THREAD

**Issue by kayuxx** [stevearc/oil.nvim#138]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM 0.9

### Operating system/version

WIN 10

### Describe the bug

the plugin `oil.nvim` its self works fine but it prevents other plugins to work eg: `nvim-ts-autotag` and causes some nvchad issues, i think the problem is from ssh that prevents those plugins to work

### Steps To Reproduce

oil.nvim

### Expected Behavior

oil.nvim

### Directory structure

oil.nvim

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [x] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Please provide some concrete steps to reproduce the issue, and describe what the error actually is. As it is, I don't know how to recreate the problem or what the problem looks like.
