### ISSUE TITLE
bug: Preview buffers aren't closed on cursor move

### ISSUE THREAD

**Issue by RayJameson** [stevearc/oil.nvim#141]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.10.0-dev-661+gef94fb69c-Homebrew

### Operating system/version

MacOS 13.4.1

### Describe the bug

When using preview mode (`<C-p>`), previewed buffers aren't closed when you move the cursor to the next entry.
[![asciicast](https://asciinema.org/a/596675.svg)](https://asciinema.org/a/596675)

### Steps To Reproduce

1. nvim .
2. `<C-p>`
3. jjjjjjjjjjj
4. `<C-p>`
5. :buffers

### Expected Behavior

Previewed buffers, that are no longer focused, should be closed

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Should be fixed!

**Comment by RayJameson** [comment]
Yes, it is! Thank you for your plugin!
