### ISSUE TITLE
question: options for border?

### ISSUE THREAD

**Issue by qube-03** [stevearc/oil.nvim#143]
hi! im enjoying the admittedly different workflow that oil has, im using the floating window most of the time now.

i just need to know what other options except "rounded" and "none" exist for the border option, as i cant find anything in the help page or the documentation. (this could turn into a feature request for better documentation)

more specifically, i would like to know if theres a border option that removes the line but keeps the one character padding around the floating window, like this (mockup):
![image](https://github.com/stevearc/oil.nvim/assets/92535344/7a54df76-16c2-42b2-921b-b9239e4ec9c5)
(it would also be nice if the border matched the content background color, maybe theres a highlight group for that already?)

thanks for the help!

**Comment by stevearc** [comment]
See `:help nvim_open_win`. It describes the "border" option and possible values. In particular, I think you want to use "solid".

The border uses the `FloatBorder` highlight group, so you could either set it to be the same as `Normal` (to match the background) or `NormalFloat` (to match the float).

**Comment by qube-03** [comment]
thank you ill try this!
