### ISSUE TITLE
feature request: icon hl color

### ISSUE THREAD

**Issue by adriancmiranda** [stevearc/oil.nvim#145]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I noticed that it is possible to pass tables in the 'columns' property as well, but I would like to customize two other properties: [removing the extra space added to the icon](https://github.com/stevearc/oil.nvim/blob/master/lua/oil/columns.lua#L219) and changing the color of the directory icon, something more like:

```lua
columns = {
	{
		'icon',
		directory = {
			icon = '',
			color = '#E0AF68',
			name = 'OilDir',
		},
		default_file = {
			icon = '',
			color = '#E0AF68',
			name = 'OilFile',
		},
	},
},
```

and not simply:

```lua
columns = {
	{
		'icon',
		directory = '',
		default_file = '',
	},
},
```

I'm not sure if I misunderstood something or if there is another way to achieve this.

### Provide background

The idea is to have a bit more freedom in customization (but again, I'm not sure if I misunderstood something and this is already possible, if so, disregard).

![image](https://github.com/stevearc/oil.nvim/assets/5431310/23cfe9a7-702e-4234-80dd-10bd38f0c1f9)

> I would like to achieve a result closer to this.
![image](https://github.com/stevearc/oil.nvim/assets/5431310/4ddb7aac-7fb2-4636-a941-a5b6188288b6)

### Additional details

I'm trying to understand how can I use [highlight function ](https://github.com/stevearc/oil.nvim/blob/master/lua/oil/columns.lua#L127) conf. I tried to just pass at `columns.directory` table, but with no sucess.

I tried to use:
![image](https://github.com/stevearc/oil.nvim/assets/5431310/fdd7f570-a159-4d09-9713-c3eb27f5f48e)
but the result is not exactly what I expect:
![image](https://github.com/stevearc/oil.nvim/assets/5431310/73b99eaf-bb6b-4c99-875d-358dbeb30c50)

**Comment by stevearc** [comment]
Okay, I've added the ability to configure the padding. You should be able to do
```lua
require("oil").setup({
  columns = { { "icon", add_padding = false } },
})
```
To change the color, you should configure the highlight group. There are two groups: `OilDir` for the directory name and `OilDirIcon` for the icon. For example
```lua
vim.api.nvim_set_hl(0, 'OilDirIcon', {fg = "#E0AF68"})
```
