### ISSUE TITLE
feature request: Show cwd & parent dir

### ISSUE THREAD

**Issue by zim0369** [stevearc/oil.nvim#146]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Show the neovim's current working directory as well as oil's current directory(parent directory) at the top. This will help us not feel lost. Additional information like number of files in the current dir, etc. could be added.

**Comment by stevearc** [comment]
This is something that could be done with the winbar (see `:help winbar`). The floating window already puts the oil directory in the title, and that's as much as makes sense to have built-in to oil itself. If you want to display the rest of that information, it should be relatively straightforward to get it using the API and configure your statusline/winbar plugin of choice to display it.
