### ISSUE TITLE
feature request: bookmarks

### ISSUE THREAD

**Issue by zim0369** [stevearc/oil.nvim#147]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Feature to bookmark directories and files which can open in their own view. Like pressing `gb` should list bookmarked directories and files. Also, having a description for the bookmarks would be of great help. ex- `/home/zim/problem.js desc-reattempt leetcode problem`

**Comment by stevearc** [comment]
Closing this as out-of-scope. This is again something that doesn't need to live inside oil itself (would work fine with just the public API), and I expect there to be significant conflicting opinions about how people would want it to work. Additionally, many existing plugins already support bits and pieces of this. Telescope can open recent files, for example. Session managers (or `:mksession`) can save open files/directories to be opened later.
