### ISSUE TITLE
feature request: Toggle permissions column in open oil buffer

### ISSUE THREAD

**Issue by amurahul** [stevearc/oil.nvim#151]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to toggle  long listing of files (particularly permissions) in an open oil buffer. 
Currently I am only able to predefine the columns that will be available in oil buffer. A way to toggle this in opened buffer would be nice, particularly helpful in changing permissions if required, but won't have hassle to see permissions always.  

### Provide background

Doomemacs has a similar plugin like oil.nvim, I don't remember the name, but it had key binding to toggle long listing in open buffer.

**Comment by stevearc** [comment]
You can dynamically set the columns with `oil.set_columns`. From there you can build a toggle function, or whatever else you like. Here's an example of how I toggle between simple and detailed view: https://github.com/stevearc/dotfiles/blob/86c971e436dc00ed4f9d46cfaec4104afac5258a/.config/nvim/lua/plugins/oil.lua#L23-L33
