### ISSUE TITLE
bug: actions.terminal doesn't work for ssh buffer

### ISSUE THREAD

**Issue by amurahul** [stevearc/oil.nvim#152]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Linux 6.4.8-arch1-1 - Arch

### Describe the bug

Can't open terminal window in an ssh oil buffer

### Steps To Reproduce

1. Map actions.terminal to a key in the config
2. Open an ssh oil buffer with oil-ssh://
3. Press the key to launch terminal

### Expected Behavior

Terminal should open with the remote shell, nothing happens.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            keymaps = {
                ["<leader>t"] = "actions.open_terminal",
            },

            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Should be fixed!

**Comment by amurahul** [comment]
Thanks, is there way to either open terminal in a different buffer or go back to oil buffer from terminal?

**Comment by amurahul** [comment]
I found a workaround for the latter question, require("oil.actions").open_terminal.callback()

**Comment by stevearc** [comment]
If you're looking to open it in a different window, you can open the window however you like (e.g. `vim.cmd.vsplit()`) and then call the action `require("oil.actions").open_terminal.callback()`
