### ISSUE TITLE
bug: splitting window: oil split could not find parent window

### ISSUE THREAD

**Issue by FrostyNick** [stevearc/oil.nvim#155]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.0 Release

### Operating system/version

Ubuntu 20.04

### Describe the bug

![image](https://github.com/stevearc/oil.nvim/assets/57016218/8661db22-b481-4641-bd65-6a0d6c699d2a)

### Steps To Reproduce

1. nvim -u repro.lua
2. `ZZ` to close Lazy.
3. <kbd>:Ex</kbd>
4. `<C-w>v`
5. Warning text below: "Oil split could not find parent window. Please try to replicate whatever you just did and report a bug on github"

### Expected Behavior

Oil split finds parent window.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This is due to bad interactions with oil and netrw when oil is trying to take over directory buffers but netrw is doing the same. The correct thing to do here is to set 
```lua
require("oil").setup({
  default_file_explorer = false
})
```

Because I've seen these errors before, I've changed the behavior so that when `default_file_explorer = true` (the default), oil will disable netrw. This means that you now _must_ set `default_file_explorer = false` if you want to continue using netrw.

**Comment by Hippo0o** [comment]
if netrw is disabled scp:// ftp:// sftp:// stops working. Is it really the best choice to straight up disable it?

**Comment by stevearc** [comment]
Fundamentally, if you want oil to work when you do `nvim .`, you have to disable netrw. netrw does a lot, but is not very configurable so there's no way to turn off the directory hijacking without disabling the whole plugin. If you still want to use netrw, I'm not stopping you. Just set `default_file_explorer = false` and you're good.

**Comment by Hippo0o** [comment]
I'm pretty sure hijacking worked fine without disabling netrw before and nvim-tree does so aswell but i don't know every edge case. 
I will just set default_file_explorer to true after setup then.

**Comment by kevinm6** [comment]
@stevearc sorry to bother here, but I think that’s better than open a new issue.

I got the same warning today, after opening a file via
`nvim scp://user@server//private/etc/hosts` that was correctly loaded by **Oil**, the warning appears after I’ve tried to enter a command like `diffsplit /private/etc/hosts`.

I have netrw completely disabled and this is my compacted **oil config**

```lua
"stevearc/oil.nvim",
keys = {}
cmd = "Oil",
opts = function(_, o)
  o.columns = default_coloumns(true)
  o.keymaps = {},
  o.use_default_keymaps = false
  o.silence_scp_warning = true -- disable scp warn to use oil-ssh since I'm using a remap
   o.view_options = {}
   o.float = {}
   o.progress = {}
 
   -- This are defaults for now, no need to override
   -- adapters = {
   --   ["oil://"] = "file",
   --   ["oil-ssh://"] = "ssh",
   -- },
   -- When opening the parent of a file, substitute these url schemes
 
   -- HACK:
   -- https://github.com/stevearc/oil.nvim/blob/931453fc09085c09537295c991c66637869e97e1/lua/oil/config.lua#L102~110
   -- Using this to remap url-scheme from args with oil-ssh schemes
   o.adapter_aliases = {
     ["ssh://"] = "oil-ssh://",
     ["scp://"] = "oil-ssh://",
     ["sftp://"] = "oil-ssh://",
   }
end,
init = function(p)
  if vim.fn.argc() == 1 then
    local argv = tostring(vim.fn.argv(0))
    local stat = vim.loop.fs_stat(argv)

    local remote_dir_args = vim.startswith(argv, "ssh") or
      vim.startswith(argv, "sftp") or
      vim.startswith(argv, "scp")

      if stat and stat.type == "directory" or remote_dir_args then
        require("lazy").load { plugins = { p.name } }
      end
   end
   if not require("lazy.core.config").plugins[p.name]._.loaded then
     vim.api.nvim_create_autocmd("BufNew", {
       callback = function()
         if vim.fn.isdirectory(vim.fn.expand("<afile>")) == 1 then
           require("lazy").load { plugins = { "oil.nvim" } }
           -- Once oil is loaded, we can delete this autocmd
           return true
        end
      end,
    })
  end
end
```

**Comment by HarshK200** [comment]
@kevinm6 Did you find a fix for it?
i got the same issue today as well
![image](https://github.com/user-attachments/assets/e9f015f4-35e2-4bda-af05-91ba85de69d1)
The wierd thing is that this warning disappears every now and then
```lua
// the config
return {
	"stevearc/oil.nvim",
	---@module 'oil'
	---@type oil.SetupOpts
	opts = {},
	-- Optional dependencies
	dependencies = { { "echasnovski/mini.icons", opts = {} } },
	-- dependencies = { "nvim-tree/nvim-web-devicons" }, -- use if prefer nvim-web-devicons
	config = function()
		require("oil").setup({
            -- just shows all the hidden files
			view_options = {
				show_hidden = true,
			},
            default_file_explorer = true
		})
		vim.keymap.set("n", "<C-n>", "<CMD>Oil<CR>", { desc = "Open parent directory" })
	end,
}

```
