### ISSUE TITLE
feature request: file path operations (like vinegar)

### ISSUE THREAD

**Issue by Nekketsu** [stevearc/oil.nvim#158]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Vinegar has 2 cool features regarding to file path operations:
* Press `.` on a file to pre-populate it at the end of a `:` command line. This is great, for example, to quickly initiate a `:grep` of the file or directory under the cursor. Type `.!chmod +x` and get `:!chmod +x path/to/file`.
* Press `y.` to yank an absolute path for the file under the cursor.

Would it be possible to implement these features in oil.nvim?

Thank you in advance.

**Comment by stevearc** [comment]
Have you looked at `:help oil-actions`? There are some built-in actions that should do what you want (and you can bind them to whatever key you want in `setup()`). I believe that `open_cmdline` and `copy_entry_path` are the two that you're asking for.

**Comment by Nekketsu** [comment]
Ups, sorry about that, and thank you for the clarification.
