### ISSUE TITLE
bug: Files over ssh are not modifiable

### ISSUE THREAD

**Issue by Supreeeme** [stevearc/oil.nvim#159]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Operating system/version

Ubuntu 22.04 (WSL2)

### Describe the bug

Files opened with oil via ssh cannot be edited, regardless of whether or not proper permissions are in place. Is this intended?

### Steps To Reproduce

1. Open file over ssh
2. Try to edit and save

### Expected Behavior

File is edited and saved

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Very odd; I swear that this worked before, but when I tried again just now I did see an error. I tried to bisect it, but my particular repro worked for every single version. Not sure what's different about how I was doing it now vs before, but there definitely was a bug. Possibly something changed in a recent Neovim release that caused this to surface more easily.

I've fixed the bug that _I_ was seeing. LMK if your issue is fixed, and if not, please provide the text of the error that you're seeing.

**Comment by Supreeeme** [comment]
I was able to normally write and save the file, so that works now. However I realized I was running into a different but related issue: my `BufWritePre` autocmd (which just strips trailing whitespace from all the lines in the buffer) breaks saving and causes it to fail. This is the error:
```
Error detected while processing BufWriteCmd Autocommands for "oil-ssh://*":
Error executing lua callback: ...m/site/pack/paqs/start/oil.nvim/lua/oil/adapters/ssh.lua:393: BufWriteCmd Autocommands for "oil-ssh://*"..BufWritePre Autocommands for "*": Vim(append):Error executing lua callback: /home/supreme/.config/nvim/lua/autocmds.lua:63: Vim:E21: Cannot make changes, 'modifiable' is off
stack traceback:
        [C]: in function 's'
        /home/supreme/.config/nvim/lua/autocmds.lua:63: in function </home/supreme/.config/nvim/lua/autocmds.lua:61>
        [C]: in function 'doautocmd'
        ...m/site/pack/paqs/start/oil.nvim/lua/oil/adapters/ssh.lua:393: in function 'write_file'
        ...hare/nvim/site/pack/paqs/start/oil.nvim/lua/oil/init.lua:901: in function <...hare/nvim/site/pack/paqs/start/oil.nvim/lua/oil/init.lua:892>
stack traceback:
        [C]: in function 'doautocmd'
        ...m/site/pack/paqs/start/oil.nvim/lua/oil/adapters/ssh.lua:393: in function 'write_file'
        ...hare/nvim/site/pack/paqs/start/oil.nvim/lua/oil/init.lua:901: in function <...hare/nvim/site/pack/paqs/start/oil.nvim/lua/oil/init.lua:892>
```

`nomodifiable` is then left on the buffer and it doesn't save properly. If I remove the autocmd it works without issue.

**Comment by stevearc** [comment]
Give it another try!

**Comment by Supreeeme** [comment]
Works without issue now, thanks!
