### ISSUE TITLE
feature request: change cwd and update oil buffer

### ISSUE THREAD

**Issue by manuelgcsousa** [stevearc/oil.nvim#160]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I am not sure if it's possible, but is there any way to update the oil buffer when changing directories within nvim?

For example, if I open an oil buffer in directory ~/A/B/C but then I use 'cd ~/A' as an nvim command, can I make oil reflect that within it's buffer?

**Comment by stevearc** [comment]
How would you want oil to reflect that the cwd has changed? Do you just want to open oil in `~/A` when you cd to `~/A`? That's doable with the command `:Oil ~/A`. You can create an autocmd on `DirChanged` to do that automatically

**Comment by manuelgcsousa** [comment]
Yes, that is basically what I want. Your actually tried you suggestions, it seems the correct way to do it:

`vim.cmd[[
  autocmd DirChanged * lua require('oil').open(vim.fn.getcwd())
]]`

But when I, for example, jump from ~/A/B/C to ~/A with `cd ~/A`, the Oil buffer just becomes empty, which is odd.

Do you have any guess about what might be the issue?

**Comment by stevearc** [comment]
The issue is that you're opening oil inside an autocmd. Oil relies on an autocmd to load properly (see `:help BufReadCmd`). I tried configuring it to run even when nested inside another autocmd, but apparently that doesn't work. The solution is to defer the call to open oil:
```lua
vim.cmd([[ autocmd DirChanged * lua vim.schedule_wrap(require('oil').open)(vim.v.event.cwd) ]])
```

**Comment by manuelgcsousa** [comment]
Amazing, that's it! Many thanks!

**Comment by manuelgcsousa** [comment]
Amazing, that's it! Many thanks!
