### ISSUE TITLE
bug: File is deleted instead of moved when containing dir is also deleted 

### ISSUE THREAD

**Issue by Amleto** [stevearc/oil.nvim#162]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.1 (winget)

### Operating system/version

win10 22h2

### Describe the bug

There is a file within a directory. I attempt to move the file up one level, and remove the (now empty) directory. The directory is deleted (I think before the file move is attempted), and the file is not moved. The file is also deleted. There is an exception message.

![image](https://github.com/stevearc/oil.nvim/assets/2996796/6d0039f8-8a77-48a5-b682-746c0a6c14c7)
![image](https://github.com/stevearc/oil.nvim/assets/2996796/a3dd93e2-4096-44b7-a33d-a71283eafd4d)

### Steps To Reproduce

1. nvim -u repro.lua
2. :Oil
3. go into 'foo' dir
4. 'dd' to delete the file
5. '-' to go back to root
6. 'p' to put the file in the root
7. delete 'foo' dir
8. ':w' to make the changes, 'o' to confirm

### Expected Behavior

Expected the file to be moved, _and then_ the directory to be deleted.

### Directory structure

foo/file.lua

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
You have found the first bug in the action resolution logic! Thanks for the report! Should be fixed now.

**Comment by Amleto** [comment]
ooh, is there a bounty?! XD

Many thanks for oil + fix

**Comment by stevearc** [comment]
Just these bounteous thanks for helping to make the plugin better!
