### ISSUE TITLE
bug: Unknown function: netrw#NetRead

### ISSUE THREAD

**Issue by GustavoKatel** [stevearc/oil.nvim#163]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-949+gd4dc52a83-Homebrew

### Operating system/version

MacOs 13.4

### Describe the bug

This happens when Nvim tries to install spell checking packages. The errors appears after the download.

I'm using oil.nvim (commit 2fde9d84fcead6c61a59388fe29bd3135c39fa94) with Neovim nightly (see version above)

I believe this is happening because this plugin is completely disabling `netrw` here: https://github.com/stevearc/oil.nvim/commit/9d90893c377b6b75230e4bad177f8d0103ceafe4#diff-728cdf59715c53b98f7e57e210d89aa8e3fa013cd5719baf72b74993bbaf2822R850-R851

The `spell` plugin uses some of the `netrw` functionality.  From the docs: https://neovim.io/doc/user/spell.html#spell-SpellFileMissing

> The [netrw](https://neovim.io/doc/user/pi_netrw.html#netrw) plugin is used for getting the
file, look there for the specific syntax of the URL

Is there a better way to override `netrw` without completely disabling it?

### Steps To Reproduce

With the suggested `repro.lua` you don't get the same error, instead it completely disables the spell download altogether. Even though it's a different behavior, I believe they are caused by the same issue.

1. nvim -u repro.lua
2. `:set spelllang=pt`
3. `:set spell`

### Expected Behavior

Neovim to suggested and download the correct spell file. This does not happen in either my config and the suggested `repro.lua`

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by GustavoKatel** [comment]
also worth mentioning that it works fine with (old behavior I believe)

```lua
require("oil").setup({
  -- Oil will take over directory buffers (e.g. `vim .` or `:e src/`)
  -- Set to false if you still want to use netrw.
  default_file_explorer = false,
})
```

**Comment by stevearc** [comment]
Unfortunately, setting `default_file_explorer = false` is the only fix for now. If you want to download spelling files, you can't disable netrw. If netrw is active, it will try to take over directory buffers and cause all manner of havoc if oil tries to do the same.
See https://github.com/neovim/neovim/issues/7189
and https://github.com/neovim/neovim/issues/23232 for a possible future solution
