### ISSUE TITLE
question: is there a way to show ".." (parent directory)

### ISSUE THREAD

**Issue by ray-pH** [stevearc/oil.nvim#166]
I know we can navigate to the parent path using a keybind (default : -), But i prefer having the directory ".." listed in the list. Is there a way to show ".."?

**Comment by stevearc** [comment]
This is a reasonable request. Hard to say how difficult this will be until I start doing the work. Will put this on my backlog.

**Comment by leet0rz** [comment]
Would love to see this too !

**Comment by ray-pH** [comment]
I'm able to do this by manually adding ".." to the entries of the listed files

inside `uv.fs_readdir(...)`, i can add manually add  `{ name = "..", type = "directory" }` to `entries`
```lua
table.insert(entries, { name = "..", type = "directory" });
```

by default, it will be grouped with the hidden file, but you can make it to be always shown by setting the `is_hidden_file` function in the user config
```lua
    is_hidden_file = function(name, bufnr)
      return (name ~= "..") and vim.startswith(name, ".")
    end,
```

not sure if there's any bad side effects

**Comment by stevearc** [comment]
This is now supported. The same note from @ray-pH applies; it is hidden by default, but you can configure that with
```lua
    is_hidden_file = function(name, bufnr)
      return name ~= ".." and vim.startswith(name, ".")
    end,
```

**Comment by oysandvik94** [comment]
Is there a way to disable this in the config? If not I can make a PR. 
If am navigating through multiple dirs with only one subdirectory it gets a bit annoying to always have to go one down.

**Comment by ray-pH** [comment]
> Is there a way to disable this in the config? If not I can make a PR. If am navigating through multiple dirs with only one subdirectory it gets a bit annoying to always have to go one down.

You can set `..` to always be hidden in the `view_options`

```lua
  view_options = {
 
    is_always_hidden = function(name, bufnr)
      return (name == "..")
    end,

  },

```
