### ISSUE TITLE
Default winblend value causes black background on floating windows

### ISSUE THREAD

**Issue by LittleAmara** [stevearc/oil.nvim#167]
If `winblend != 0` (10 being the default value for oil) then the background appears black:
![image](https://github.com/stevearc/oil.nvim/assets/96989958/514a7d2e-8815-42ff-af36-0cd825791607)
It is related to [this issue](https://github.com/neovim/neovim/issues/18576) on the Neovim repository.

Maybe it would be good to either change the default value or add a little note in the README about overriding the `win_options` for the people that are not familiar with floating windows.

**Comment by stevearc** [comment]
Yes, the issue you linked is the problem. I think that changing the default value is a reasonable response, at least until this gets fixed in core
