### ISSUE TITLE
feature request: ability to sort the files first

### ISSUE THREAD

**Issue by sajjathossain** [stevearc/oil.nvim#169]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

the file tree should list file files first and directories last. it allows easier file access.

**Comment by stevearc** [comment]
I've added an API for configuring the sort order. In your case you will want
```lua
require("oil").setup({
  view_options = {
    sort = {
      { "type", "desc" },
      { "name", "asc" },
    }
  }
})
```
