### ISSUE TITLE
bug: abandoned floating window does not close

### ISSUE THREAD

**Issue by herrvonvoid** [stevearc/oil.nvim#17]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.2 build type: release

### Operating system/version

archlinux, 6.1.2-arch1-1

### Describe the bug

If you abandon a floating window created by oil it stays there.

### Steps To Reproduce

* `:Oil`
* `g?`
* `<C-w>h`
* hit enter on a file -> it opens the file but the oil-help is still shown

or:
* `:lua require'oil'.open_float()`
* `<C-w>h`
* oil still shown

### Expected Behavior

close all oil created windows as soon as a non-oil-created window gains focus

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require"oil".setup() -- add any needed settings here
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Done!

**Comment by herrvonvoid** [comment]
Nice, however, this does not cover the second test case I provided... An abandoned open_float() has the same problem

**Comment by herrvonvoid** [comment]
@stevearc please reopen

**Comment by stevearc** [comment]
Apologies, I was in a rush. Should be working as expected now
