### ISSUE TITLE
bug (?): BufModifiedSet is not called after updating the filesystem

### ISSUE THREAD

**Issue by murtaza64** [stevearc/oil.nvim#171]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 20.04 on WSL2

### Describe the bug

It seems that BufModifiedSet is not called after writing to the filesystem. It would be useful if it was for updating stuff like an icon indicating unsaved changes.

### Steps To Reproduce

1. nvim -u repro.lua
2. :Oil<enter>
3. ohello^[ (add a new file)
4. :w<enter> (write changes to filesystem)
5. o (confirm changed)

### Expected Behavior

BufModifiedSet is called thrice:
1. initial load sets modified to false
2. creating new file sets modified to true
3. updating filesystem sets modified to false

modified is indeed false after the write but the autocommand is never called. The observed behavior is that only 1. and 2. are triggered (only two lines in :mes)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here



vim.api.nvim_create_autocmd({'BufModifiedSet'}, {
    pattern = "oil://*",
    callback = function(ev)
	print("Hello world!", vim.bo.modified, ev.buf)
    end
})
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This is because `BufModifiedSet` is not _really_ tracking the status of the `modified` option. If you [look at the implementation](https://github.com/neovim/neovim/pull/13205/files), it's really only going to fire when the modified status changes due to normal edits. You can verify this with the following example:

```lua
local group = vim.api.nvim_create_augroup("test", {})
vim.api.nvim_create_autocmd({ "BufModifiedSet" }, {
	group = group,
	pattern = "*",
	callback = function(ev)
		print("BufModifiedSet", vim.bo.modified, ev.buf)
	end,
})

vim.defer_fn(function()
	vim.bo.modified = true
	vim.defer_fn(function()
		vim.bo.modified = false
	end, 500)
end, 500)
```

If you want `BufModifiedSet` to be more comprehensive, try filing a bug report on the Neovim repo. You could also try using the `OptionSet` autocmd to get a more complete view of when `modified` is changed.
