### ISSUE TITLE
feature request: Highlight groups for confirmation popup?

### ISSUE THREAD

**Issue by jesseleite** [stevearc/oil.nvim#174]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Would be nice if there were highlight groups to control the border and background color of the confirmation popup. Or maybe there is a way? Did a quick code dive and it doesn't seem currently possible. What are your thoughts on this?

![CleanShot 2023-09-08 at 23 07 06](https://github.com/stevearc/oil.nvim/assets/5187394/b3b038a3-bd15-44c7-88d3-e3c177b1fd92)

**Comment by stevearc** [comment]
You can set this via the window options using winhighlight (see `:help winhighlight`)

```lua
require("oil").setup({
  preview = {
    win_options = {
      winhighlight = "NormalFloat:DiagnosticError",
    },
  },
})
```

**Comment by jesseleite** [comment]
I'm actually even fine to just theme `NormalFloat`, etc. Just didn't realize that's what was being used there. Thank you for the tip, and for all your work on oil.nvim! 🎉
