### ISSUE TITLE
feature request: Cursor only on mutable column

### ISSUE THREAD

**Issue by LamprosPitsillos** [stevearc/oil.nvim#175]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

d4eb4f3

Could you expand on this pr , not allowing cursor on non mutable columns? ( Size , time etc)

**Comment by stevearc** [comment]
It would be tricky, but potentially doable. I would worry that this is becoming a little bit too much magic cursor movement. For the most part, I want oil to feel like a normal buffer, and I think this would be a bit too much. Closing as out of scope.
