### ISSUE TITLE
feature request: create symlinks

### ISSUE THREAD

**Issue by kflak** [stevearc/oil.nvim#176]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hi, and thanks for an _awesome_ plugin!

Is there any way to create symlinks from within oil?

**Comment by stevearc** [comment]
Yep! If you notice, symlinks get displayed as `link_name -> link-target` in oil. To create one, you just create a new file in the same format

**Comment by kflak** [comment]
Absolutely fantastic! Thanks :-D

**Comment by melMass** [comment]
for reference I use this: https://gist.github.com/melMass/47f5c7582c3d9533f8514c2abfe6c862
