### ISSUE TITLE
add autocmds to Oil augroup

### ISSUE THREAD

**Issue by bugsbugsbux** [stevearc/oil.nvim#18]
It might be a good idea to add autocmds to the Oil group created in setup() so the user knows who created them (and to prevent creating them multiple times if sourcing the pluing again).

It can be done by groupname instead of groupid! Just add `group="Oil",` to the nvim_create_autocmd() calls...

**Comment by herrvonvoid** [comment]
never mind, you use once=true

**Comment by max397574** [comment]
he also already uses an augroup
![Screenshot 2023-01-05 at 22 10 58](https://user-images.githubusercontent.com/81827001/210880668-3ad0e0ef-37ba-4e09-b0ca-09a5abeb1c32.png)
