### ISSUE TITLE
bug: Remapped "require("oil").open" not opening Oil, instead discoloring the current file and making the filetype "oil" on lualine.

### ISSUE THREAD

**Issue by leet0rz** [stevearc/oil.nvim#181]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Windows 10

### Describe the bug

Basically just trying to open Oil in current directory with the remap:

`
vim.keymap.set("n", "<C-b>", require("oil").open)
`

It happens with lua files. 
:e . and :e %:h seems to be working fine but not require("oil").open

### Steps To Reproduce

1. Install git-bash on windows
2. Open a lua config settings file
3. Run the remap "vim.keymap.set("n", "<C-b>", require("oil").open)"
Before:
![8NMaBnZ 1](https://github.com/stevearc/oil.nvim/assets/29175192/bd60dd77-1329-40ce-8105-1b85d33bccbf)
After:
![vYtgXly 1](https://github.com/stevearc/oil.nvim/assets/29175192/43c59e59-841a-4aa9-a701-ae1ebf842286)

### Expected Behavior

For Oil to open as usual in the directory of the file I currently have open.

### Repro

```Lua
Was not able to figure this part out, sorry.
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Unfortunately without a repro all I can offer is "it works on my machine". It could possibly be some odd interaction with some other part of your config, but I can't reproduce so I can't debug. Feel free to reopen if you manage to get a minimal repro config
