### ISSUE TITLE
feature request: Netrw's `gx` shortcut

### ISSUE THREAD

**Issue by lukewiebe** [stevearc/oil.nvim#182]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I'd love to get Netrw's `gx` action to open a file using the default app alongside Oil as my file browser.

### Provide background

I use Netrw's `gx` shortcut to open links, images, and PDFs from any neovim buffer. Unfortunately when Oil disables Netrw, it also disables this action. Is there a way to use Oil as the default file browser without losing this function? I'm not a plugin developer, so I have no idea how feasible this is.

(Thanks for making Oil by the way! It's super cool and I love it.)

**Comment by stevearc** [comment]
I put up a PR that should implement this. I've got some brain fog right now, so I'm not willing to merge my fever-addled code, but you can test it out now and I'll review+merge it when I'm in a better state.

**Comment by lukewiebe** [comment]
Wow, that was quick! I'll report any issues I find. Thanks!

**Comment by mroavi** [comment]
I ran into this same issue. I don't think that https://github.com/stevearc/oil.nvim/pull/183 solves the problem posted by the OP.

Netrw provides the `gx` mapping, which allows one to open a URL located in any buffer (not only the Netrw plugin) in one's default browser (in fact, I had no idea that it was the Netwr plugin providing this functionality). As far as I can tell, the functionality provided in the PR mentioned above opens a file listed in the OIL buffer using the default program, which is a different functionality.

I'm also looking into how to retain Netrw's `gx` functionality without having to install an extra plugin.

**Comment by mroavi** [comment]
Here is how `nvim-tree` solves this issue:

```
|g:nvim_tree_hijack_netrw|		             *g:nvim_tree_hijack_netrw*

Can be 0 or 1. When 1, disable netrw buffers when nvim-tree start but keeps
existing netrw functionnalities accross buffers (like `gx`).
1 by default.
```

More info here: https://www.reddit.com/r/neovim/comments/p5outz/how_can_i_keep_gx_functionality_without_netrw/

**Comment by AndyMcAliley** [comment]
How about this workaround for init.lua to keep netrw's `gx` in regular buffers but use Oil instead of netrw as a file explorer:
```lua
-- Leave netrw on
require("oil").setup({default_file_explorer = false})
-- Let oil open directories by default
require("oil.config").setup({default_file_explorer = true})
-- Turn off the directory browsing part of netrw manually
if vim.fn.exists("#FileExplorer") then
  vim.api.nvim_create_augroup("FileExplorer", { clear = true })
end
```
One downside is that if you pass a directory as an argument to `nvim` at the command line then that directory will still be opened in a netrw buffer.
