### ISSUE TITLE
feature request: LSP willRenameFiles

### ISSUE THREAD

**Issue by lopi-py** [stevearc/oil.nvim#184]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Add callbacks when creating, renaming/moving and deleting files.

### Provide background

It would be nice to notify the lsp when a file is renamed, for example [this plugin](https://github.com/antosha417/nvim-lsp-file-operations) makes it possible with nvim-tree and neo-tree. It would be nice if it could integrate with oil.nvim. Also this could be interesting to have as a built-in feature

**Comment by stevearc** [comment]
I've added built-in support for willRenameFiles. Been thinking about this for a while; just needed an extra push!

**Comment by jacksonludwig** [comment]
Might be worth adding this to the readme, personally I had nvim-tree installed only because oil did not yet support this :)
