### ISSUE TITLE
feature request: mouse support

### ISSUE THREAD

**Issue by maximyurevich** [stevearc/oil.nvim#185]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

enter directory location with right click

**Comment by stevearc** [comment]
The only tricky part is getting vim to run the keymap _after_ the mouse click moves the cursor. It's a little awkward, but doable:
```lua
require("oil").setup({
  keymaps = {
    ["<RightMouse>"] = "<LeftMouse><cmd>lua require('oil.actions').select.callback()<CR>",
  }
})
```
