### ISSUE TITLE
feature request: map `gf` in oil-ssh file to goto the file whose name is under  the cursor.

### ISSUE THREAD

**Issue by gh-liu** [stevearc/oil.nvim#186]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

map `gf` in oil-ssh file to goto the file whose name is under  the cursor.

**Comment by stevearc** [comment]
That's just the behavior for `<CR>` right? You can set that keymap in the config

```lua
require("oil").setup({
  keymaps = {
    gf = "actions.select",
  },
})
```

**Comment by gh-liu** [comment]
No, what I mean is when I open  a regular file by oil-ssh, there may be a file name under the cursor, if you type `gf`, vim could not goto the file, because the file is not in the local machine. 

For example: 
I open a oil-ssh file `oil-ssh://[username@]hostname[:port]/[path]/config.json`, the `config.json` contain a path to `config.yaml`, when the path under the cursor, type `gf` then open the `config.yaml`.

**Comment by stevearc** [comment]
I took a stab at it. I think the name extraction might need some work, but the basic functionality should be there

**Comment by gh-liu** [comment]
Thanks for your great work.
