### ISSUE TITLE
feature request: Support for Mode-Specific Keymaps in Oil Buffer

### ISSUE THREAD

**Issue by mroavi** [stevearc/oil.nvim#187]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like the ability to specify the mode for a keymap in the Oil buffer. For example, I want to map the `action.close` function to the `<Esc>` key, but I only want this mapping to be active when in Normal mode. This means that if there is a visual selection active, pressing `<Esc>` should not close the Oil buffer. Instead, it should exit Visual mode and return to Normal mode, keeping the Oil buffer open.

I couldn't find information in the current documentation on how to accomplish mode-specific keymapping in the Oil buffer. If this is already possible, please do let me know.

**Comment by stevearc** [comment]
I've added the ability to specify a mode. In your case, this is what you will want:

```lua
require("oil").setup({
  keymaps = {
    ["<Esc>"] = { callback = "actions.close", mode = "n" },
  },
})
```

**Comment by mroavi** [comment]
You are very kind. Thank you very much.
