### ISSUE TITLE
bug: FloatTitle is overwritten when loading Oil

### ISSUE THREAD

**Issue by yorickpeterse** [stevearc/oil.nvim#189]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Fedora Silverblue 38

### Describe the bug

At https://github.com/stevearc/oil.nvim/blob/977da9ac6655b4f52bc26f23f584d9553f419555/lua/oil/init.lua#L714, the code checks if `FloatTitle` is defined, and if not sets up a definition for this. At least on NeoVim 0.9.2, this line always returns `false` (e.g. `lua print(vim.inspect(pcall(vim.api.nvim_get_hl_by_name, "FloatTitle")))` prints `false`), thus overwriting the `FloatTitle` definition. This is because `nvim_get_hl_by_name` is deprecated [and does nothing](https://github.com/neovim/neovim/blob/b917db062fc673dfbbc6a8c722b05101319ab44e/runtime/lua/vim/_meta/api.lua#L1252) and its replacement, `nvim_get_hl`, takes two arguments: a namespace ID, and a list of options.

### Steps To Reproduce

1. Use a theme that defines something like `hi FloatTitle guifg=red gui=bold`
2. Load oil on NeoVim 0.9.2 (or 0.9.0 or newer based on when `nvim_get_hl_by_name` was deprecated)
3. Run `hi FloatTitle`, observe the lack of `gui=bold`

### Expected Behavior

`FloatTitle` is left alone.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--single-branch",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

vim.cmd("hi def FloatTitle guifg=red gui=bold")

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
                -- add any needed settings here
            })
        end,
    },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
You definitely found a bug, but the diagnosis is off. While `nvim_get_hl_by_name` is deprecated, it does still function. That lua definition is just for typechecking and (possibly?) documentation generation. [The real implementation](https://github.com/neovim/neovim/blob/b917db062fc673dfbbc6a8c722b05101319ab44e/src/nvim/api/deprecated.c#L208) is in C and definitely still works.

The issue here was that I was using pcall to check if the function returned an error, and it _always_ did so because I was mistakenly not passing in the mandatory second argument.

Thanks for the report!

**Comment by yorickpeterse** [comment]
@stevearc Thanks! :tada:
