### ISSUE TITLE
feature request: don't open confirmation when nothing changed

### ISSUE THREAD

**Issue by SuperCuber** [stevearc/oil.nvim#19]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

If I just open a directory and `:w` it asks me whether I want to apply the 0 changes.
Either doing nothing or echoing a "no changes to apply" seem more appropriate.

**Comment by stevearc** [comment]
I've elected to let the save operation pass silently, with no preview. This has the effect that if you have modified the buffer in ways that don't change the filesystem (e.g. adding blank lines), it will reset the buffer to its base state.
