### ISSUE TITLE
More of a question, is it possible to have path showing at all times while in oil?

### ISSUE THREAD

**Issue by leet0rz** [stevearc/oil.nvim#190]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

![Sjn7gJE 1](https://github.com/stevearc/oil.nvim/assets/29175192/1ea46117-87ec-4617-9b3e-3be0bcba2cce)
While in this screen, is it possible to have path showing while navigating around? I know there is a command for it, but I would rather have it showing. Maybe there is an option for it, I just could not find it yet. Thanks.

### Provide background

Clarity.

### Additional details

None.

**Comment by stevearc** [comment]
If you use the floating window `:Oil --float` then it will be displayed in the window title. If you're just using the normal buffer, it's up to you how you want to configure it. It doesn't make sense to put the PWD in the buffer, but you could easily add it to the winbar or the statusline. Use the [get_current_dir](https://github.com/stevearc/oil.nvim/blob/master/doc/api.md#get_current_dir) function

**Comment by leet0rz** [comment]
> If you use the floating window `:Oil --float` then it will be displayed in the window title. If you're just using the normal buffer, it's up to you how you want to configure it. It doesn't make sense to put the PWD in the buffer, but you could easily add it to the winbar or the statusline. Use the [get_current_dir](https://github.com/stevearc/oil.nvim/blob/master/doc/api.md#get_current_dir) function

Doing that just changes the theme color I have. 
![xs5vJOU 1](https://github.com/stevearc/oil.nvim/assets/29175192/7a619da2-eac8-42db-af1c-1f2a6bcca1a3)

Make the file "oil" type too (buttom right corner on lualine), which is weird. Is there a bug?

**Comment by stevearc** [comment]
That is very weird. Can you report a new issue, going through the bug report flow to create a minimal repro config? The command obviously works for me, so there is likely something specific to your config that is causing the problem

**Comment by leet0rz** [comment]
> That is very weird. Can you report a new issue, going through the bug report flow to create a minimal repro config? The command obviously works for me, so there is likely something specific to your config that is causing the problem
Give it a try with git-bash on windows, I just tried running the same config on powershell and :Oil works there. Git-bash, Lazy, and Oil should be the minimal, give it a go.

I am guessing it might be a problem with the pathing of git-bash since its not the regular c:\user its c/user etc. Maybe it messes up and opens the file as oil instead? That is just a guess.

**Comment by leet0rz** [comment]
@stevearc 
![1pgSaTw 1](https://github.com/stevearc/oil.nvim/assets/29175192/9b16d5f9-8dc7-4fca-955a-09aee49c7d00)
This thing popped up today, still having the problem with oil taking over the file and messing up the colors, maybe this picture can give you some leads, I dont know.

**Comment by stevearc** [comment]
Ah, I can disable swapfiles for oil buffers, which will fix that problem (after you delete the existing swapfile). Still no idea what would cause the color changes.

**Comment by leet0rz** [comment]
> Ah, I can disable swapfiles for oil buffers, which will fix that problem (after you delete the existing swapfile). Still no idea what would cause the color changes.

Tried disabling swapfiles, but it still happens.
![OUk4hpz 1](https://github.com/stevearc/oil.nvim/assets/29175192/4cbb3dfc-00db-4430-95fd-364084d88746)

**Comment by stevearc** [comment]
Again, the issue you're reporting is extremely weird and I haven't been able to replicate it. You'll need to go through the process of creating a minimal repro for me to have any chance of debugging it.

**Comment by leet0rz** [comment]
> Again, the issue you're reporting is extremely weird and I haven't been able to replicate it. You'll need to go through the process of creating a minimal repro for me to have any chance of debugging it.

Do you mean creating a minimal config that I still get the same issue with when I run it?

**Comment by stevearc** [comment]
yep
