### ISSUE TITLE
feature request: Always open files relative to current directory

### ISSUE THREAD

**Issue by mortezadadgar** [stevearc/oil.nvim#194]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

currently files open being open with their absolute file address results in long file names in status line if `statusline=%f`
is there any way to avoid this?

telescope open files relative to current directory for instance.

### Provide background

![image](https://github.com/stevearc/oil.nvim/assets/27911493/a3c089f0-5eaf-41a2-8f5d-261cfcf6387d)
while I'm in ~/workspace/Book-store so this part should be trimmed from address

**Comment by stevearc** [comment]
Done

**Comment by mortezadadgar** [comment]
Thanks!
