### ISSUE TITLE
feature request: sponsorship

### ISSUE THREAD

**Issue by looshch** [stevearc/oil.nvim#195]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

oil.nvim is incredible, i want to sponsor you. How can i do this?

**Comment by stevearc** [comment]
That's a nice gesture, I appreciate it! I have a policy of not accepting money for my open source work. It helps me to set boundaries so I don't overwork myself _too_ much on my side projects. The best sponsorship is starring the repo and spreading the word :)
