### ISSUE TITLE
bug: oil.nvim it no longer opens files outside of the root (working) directory.

### ISSUE THREAD

**Issue by basilgood** [stevearc/oil.nvim#197]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.0-dev-a03e00a

### Operating system/version

linux

### Describe the bug

Thank you for all your beautiful work.
With commit [6cbc8d725d3964cb08d679774db67d41fa002647](https://github.com/stevearc/oil.nvim/commit/f72b9b2637eec2b3db8255c196aa4bf11231af81), oil.nvim it no longer opens files outside of the root (working) directory.

https://github.com/stevearc/oil.nvim/assets/16057481/e974fcc7-1796-4ffb-8635-e2421097a0d8

### Steps To Reproduce

pwd: ~/.config/nvim

1. nvim -u init.lua
2. press "-" key
3. it open oil.nvim
4. enter on init.lua
5. it open init.lua
6. press "-" key, it open oil in nvim dir
7. press "-" key again to open the tree above nvim dir (.config dir)
8. enter in nvim1 dir, enter init.lua
9. nothing hapens
10. press "-" key it open oil but it entering in "/" directory 

### Expected Behavior

when it open a dir above the working dir to open the desired file

### Directory structure

```~/.config/nvim/init.lua```   this is the repro dir with repro init.lua
```~/.config/nvim1/init.lua```  this is the backup nvim config

### Repro

```Lua
local plugins = {
	{
		'stevearc/oil.nvim',
		opts = {},
		-- Optional dependencies
		dependencies = { "nvim-tree/nvim-web-devicons" },
	}
}
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'

if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		'git',
		'clone',
		'--filter=blob:none',
		'https://github.com/folke/lazy.nvim.git',
		'--branch=stable',
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)
require('lazy').setup(plugins, {})

vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Thanks for the clear repro steps! The bug is probably because of 6cbc8d725d3964cb08d679774db67d41fa002647, though I'm not entirely sure how yet. I'm going to go ahead and revert that change until we can figure out what the root cause is.

Even with the repro steps, I wasn't able to see the failure you're seeing. Would you be able to paste the output of this command?
```
:=require("oil.fs").shorten_path("/abolute/path/to/.config/nvim1/init.lua")
```

**Comment by basilgood** [comment]
Sorry for the late response.
The output of ```:=require("oil.fs").shorten_path("/abolute/path/to/.config/nvim1/init.lua")```
is ```/abolute/path/to/.config/nvim1/init.lua``` for all the commits before and after revert.
With latest commit after revert [6cbc8d7](https://github.com/stevearc/oil.nvim/commit/6cbc8d725d3964cb08d679774db67d41fa002647)
oil works perfectly.
But I can reproduce the bug here before revert  [a8ac4de](https://github.com/stevearc/oil.nvim/commit/a8ac4dee48fa6289bbddf18517bf06169da58c2a)


https://github.com/stevearc/oil.nvim/assets/16057481/9c1d7fd0-a69e-47cd-824f-accd48a7a03d

**Comment by basilgood** [comment]
Strange thing, bug happens only if root dir is nvim dir:


https://github.com/stevearc/oil.nvim/assets/16057481/231f0f46-5576-4462-b060-221e7bc559d1

**Comment by stevearc** [comment]
Ah, I think I know what the problem was. I have re-applied the change I reverted earlier, with an additional fix. Could you try one last time and see if the issue is still fixed for you?

**Comment by basilgood** [comment]
Yes it works now.
Thank you very much.
