### ISSUE TITLE
feature request: do only the minimal operations to achieve the desired changes

### ISSUE THREAD

**Issue by italovieira** [stevearc/oil.nvim#198]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Suppose I write to a oil buffer:

```
dir1/file1.txt
dir1/file2.txt
dir1/file3.txt
dir1/file4.txt
dir1/file5.txt
```

In the popup window to confirm the changes it shows:

```
CREATE dir1/
CREATE dir1/
CREATE dir1/
CREATE dir1/
CREATE dir1/
CREATE dir1/file1.txt
CREATE dir1/file2.txt
CREATE dir1/file3.txt
CREATE dir1/file4.txt
CREATE dir1/file5.txt

[O]k    [C]ancel
```

It would be better if it were:

```
CREATE dir1/
CREATE dir1/file1.txt
CREATE dir1/file2.txt
CREATE dir1/file3.txt
CREATE dir1/file4.txt
CREATE dir1/file5.txt

[O]k    [C]ancel
```

### Provide background

With this enhancement the preview window will be more clean and more easy to understand the operations when there are many changes.
Furthermore, the plugin operations will be reduced in some cases, making it more efficient.

**Comment by stevearc** [comment]
fixed by 354c53080a6d7f4f0b2f0cc12e53bede2480b9e5
