### ISSUE TITLE
bug: Oil buffers cleanup and positioning of cursor

### ISSUE THREAD

**Issue by pteroctopus** [stevearc/oil.nvim#199]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

nvim -v NVIM v0.9.4 Build type: Debug LuaJIT 2.1.1692716794

### Operating system/version

Ubuntu 22.04

### Describe the bug

I have two keymaps to toggle oil buffer using oil API (keymaps and functions in the bottom):

```lua
require('oil').open(path)
```

It works. <localleader>o will toggle oil buffer and open current directory of the buffer. Pressing <localleader>o again will close oil buffer.

The problem is: if you use buffer cleanup, oil buffer will get cleaned up after 2 seconds. And toggling oil buffer again will not position cursor on last opened file.
If buffer cleanup is disabled than everything works but oil remain active for the whole session (although hidden, lua line shows them without name in bufferline).

Suggestion 1:
Leave everything as it is but add another open function in api that would have a second parameter filename. Filename can than be used to toggle oil buffer and position cursor to that file.

Suggestion 2:
Clean all oil buffers except that last one. That should work to.

# Keymaps

```lua
vim.keymap.set('n', '<localleader>o', oil_toggle_curr_buf_path, { desc = '[O] Oil current buffer path' })
vim.keymap.set('n', '<localleader>O', oil_toggle_cwd, { desc = '[O] Oil cwd path' })
```

Functions

```lua
local oil_toggle = function (path)
  if vim.bo.filetype == 'oil' then
    -- Close current oil buffer
    require('oil').close()
  else
    -- Open oil buffer
    require('oil').open(path)
  end
end

-- Oil open path in current directory of the buffer
local oil_toggle_curr_buf_path = function ()
  oil_toggle(vim.fn.expand('%:h'))
end

-- Oil open path in current working directory
local oil_toggle_cwd = function ()
  oil_toggle('.')
end
---

### Steps To Reproduce

1. Add these functions and keymaps to neovim config:

# Keymaps

```lua
vim.keymap.set('n', '<localleader>o', oil_toggle_curr_buf_path, { desc = '[O] Oil current buffer path' })
vim.keymap.set('n', '<localleader>O', oil_toggle_cwd, { desc = '[O] Oil cwd path' })
```

Functions

```lua
local oil_toggle = function (path)
  if vim.bo.filetype == 'oil' then
    -- Close current oil buffer
    require('oil').close()
  else
    -- Open oil buffer
    require('oil').open(path)
  end
end

-- Oil open path in current directory of the buffer
local oil_toggle_curr_buf_path = function ()
  oil_toggle(vim.fn.expand('%:h'))
end

-- Oil open path in current working directory
local oil_toggle_cwd = function ()
  oil_toggle('.')
end
---

2. Open some file
3. Wait number of seconds defined in cleanup_delay_ms
4. Press <localleader>o
5. Cursor will not be positioned on current file from which oil was toggled. Unless it is the file in first row offcourse :-)


### Expected Behavior

Toggling oil should position the cursor on last opened file even if all oil buffers are cleaned up.

### Directory structure

_No response_

### Repro

```Lua
I did not check with clean config.
Also did not upload repro.lua.
Please close this bug if this is a problem.
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
I believe the fix you want is even simpler: remove the `vim.fn.expand('%:h')` because that is the default behavior. When you call `open()` with no path, it opens the parent directory of the current buffer (plus handles some special buffers, like terminals and netrw). In addition, it will jump your cursor to the file that you were just in. If you pass in a path argument, you lose all of those bonus features.

**Comment by pteroctopus** [comment]
Thank you !
That works.
