### ISSUE TITLE
state

### ISSUE THREAD

**Issue by max397574** [stevearc/oil.nvim#2]
I see
"first draft" and "initial commit" commits (and only three commits so far)
it's not that I don't think a plugin can't be good without many commits
but before I'll start renaming files in my directories I wanted to ask about the state of the project
should everything already be fully working? or are there still some wip things?

**Comment by UnrealApex** [comment]
It appears that this plugin is still in the making. There are some bugs that I have noticed but I am confident they will be smoothed out soon such as:
- the Oil buffer being unmodifiable after a file operation
- canceling the modification of a file does not return the file's original state to the buffer(i.e. deleting a file, canceling the operation, and the file is gone from the buffer)

**Comment by max397574** [comment]
you should open issues for those bugs

**Comment by UnrealApex** [comment]
Yeah, I think I should, but I feel like @stevearc probably has patches for these bugs just ready to push. I will take your suggestion.

**Comment by stevearc** [comment]
@max397574 that's a fair concern. I actually have been working on this for some time privately and had about 150 commits that I squashed before doing the public release. I know some people prefer to see the whole history of how things developed, but I find that I feel more free to experiment in a quick and hacky way if I know that only the final product will be visible. To answer your question: all features should be fully formed and ready for use. The only WIP feature is completely undocumented and you won't be able to find or use it without reading the code. That said, the concern you have about doing destructive file manipulation is fair and merited, as this plugin is more complex than the alternatives and therefore there are more ways for it to fail. This is the main reason why the default config displays the preview window before performing _any_ file operations. See my answer to #1 for a bit more color on that subject.

@UnrealApex always happy to get bug reports! The more detail the better. I see you've already filed one for the first thing you mentioned, but go ahead and open an issue or discussion for the second as well. I _think_ that it's intended behavior, but I'll need some clarification first.
