### ISSUE TITLE
Question: is "editing directory buffer changes working directory" the expected behaviour?

### ISSUE THREAD

**Issue by luffyx25** [stevearc/oil.nvim#202]
Hi firstly thank you for the amazing plugin.

I have a question regarding the behaviour of oil with directory. When I edit a directory, my neovim working directory `pwd` will change to that directory. Is this the expected behaviour? Is it possible to keep the original working directory?

**Comment by stevearc** [comment]
I have never seen that behavior before, and it's not something that I added to this plugin. If you can get a minimal config that reproduces the issue I can look into it. A starting template is available in the bug report template

**Comment by luffyx25** [comment]
Yes, my bad. I tested it with minimal config and it was fine. Thank you!
