### ISSUE TITLE
feature request: preview file/sub directory automatically after entering directory

### ISSUE THREAD

**Issue by HalliS20** [stevearc/oil.nvim#203]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Would be very cool if you could recommend a changed keybinding or something so Oil always opens the preview mode when entering a directory

### Provide background

Would save me a little bit of time when entering a directory since I constantly use the preview mode.

**Comment by stevearc** [comment]
There's an autocmd for this in #87
