### ISSUE TITLE
bug: can't open or preview files whose path includes special character like brackets.

### ISSUE THREAD

**Issue by mushfiqRabbi** [stevearc/oil.nvim#204]
### Did you check the docs and existing issues?

- [ ] I have read the docs
- [x] I have searched the existing issues

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Windows 11

### Describe the bug

Can't open or preview files of directories that contain brackets in their name in a Next.js project.

### Steps To Reproduce

1. Create a directory with any name that contains brackets like "()".
2. Create a file under that directory.
3. Now try to open or preview the file using oil.

### Expected Behavior

Open or preview files like other files that are under directories that do not contain brackets.

### Directory structure

app\(main)\page.tsx
app\(sub)\page.tsx

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
It works fine for me, but I'm not on Windows. Are you using WSL, a windows terminal, or a gui?

**Comment by staticWagomU** [comment]
I have the same problem.

## Describe the bug
If the first character of a file or directory is a (, the path is not correctly parsed and is appended to the immediately preceding character.
As shown in the video, `a\(a)bc\baz.txt` is parsed as `aa)bc\baz.txt`.

https://github.com/stevearc/oil.nvim/assets/34824645/3023d702-3dac-436f-a841-45af6bdaac52


## minimal vimrc
```
syntax enable
filetype plugin indent on

set rtp+=~/oil.nvim

lua<< EOF
require("oil").setup()
EOF
```

## env
os: Windows 11 pro
terminal: wezterm
(The same problem occurs in windows terminal.)
```shell
$ nvim -v
NVIM v0.10.0-dev-09a17f9
Build type: RelWithDebInfo
LuaJIT 2.1.1695653777
```

**Comment by mushfiqRabbi** [comment]
> It works fine for me, but I'm not on Windows. Are you using WSL, a windows terminal, or a gui?

I am using neovim inside Windows terminal (no WSL).

**Comment by stevearc** [comment]
I finally got a chance to test this out on a Windows machine. Turns out this is a _very_ long-standing issue with both Vim and Neovim. I've put up a PR that attempts to work around the bug. Please give it a try and see if it fixes your issue, and if it causes any other issues. I'm not confident that the workaround is a perfect replacement for the previous behavior, so it needs some stress testing before it's ready to merge.
