### ISSUE TITLE
bug: can't use on home level

### ISSUE THREAD

**Issue by thjbdvlt** [stevearc/oil.nvim#206]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.3

### Operating system/version

debian 11

### Describe the bug

hi :) and thank you for posting this __fantastic__ plugin. i __love__ using it :-)
when problem is that i cannot use oil.nvim on my home level or higher (`~` or `/home`, or `/`). it produces following error:
```
Error executing luv callback:
...ocal/share/nvim/lazy/oil.nvim/lua/oil/adaptaters/files.lua:23. E5560: vimL function must not be called in a lua loop callback
stack traceback:
[C]: in function 'fnamodify'
...ocal/share/nvim/lazy/oil.nvim/lua/oil/adaptaters/files.lua:23: in function <...ocal/share/nvim/lazy/oil.nvim/lua/oil/adaptaters/files.lua:16>
```

i had not this problems few weeks ago, but dont really know when this started.
(i installed oil.nvim with Lazy, but with Packer i already had this problem.)
have a nice day :)

### Steps To Reproduce

cd ~ 
nvim -c "Oil"

### Expected Behavior

open the directory as it usually do in oil.nvim

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by thjbdvlt** [comment]
i updated to newer version of nvim (0.9.4) and problem disappear, so i mark as 'solved' but maybe the version required for oil.nvim is not 0.8 but higher? anyway, thank's again for creating and maintaining this plugin, it totally changed my command-line based computing life :)

**Comment by thjbdvlt** [comment]
i updated to newer version of nvim (0.9.4) and problem disappear, so i mark as 'solved' but maybe the version required for oil.nvim is not 0.8 but higher? anyway, thank's again for creating and maintaining this plugin, it totally changed my command-line based computing life :)

**Comment by stevearc** [comment]
Thanks for the stack trace! I was able to find and fix the problem pretty quickly. The problem may have stopped for you, but there was definitely an underlying bug that was still there. Thanks for the report!
