### ISSUE TITLE
How can I remap

### ISSUE THREAD

**Issue by restagner** [stevearc/oil.nvim#217]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

How can I remap

    ["<C-s>"] = "actions.select_vsplit",
    ["<C-h>"] = "actions.select_split",

**Comment by stevearc** [comment]
You can set them to `false` to disable the keymap, or you can put anything in the right hand side that you could pass to `vim.keymap.set`.

**Comment by sbancuz** [comment]
If you managed to do it, can you please share how? 

I did
```lua
["<C-k>"] = "actions.select_vsplit",
```
but nothing seems to change, I've also tried with a lot of other Keybinds and also tried to make an autocommand like suggested in another issue, but it still doesn't work

**Comment by restagner** [comment]
This was my experience @sbancuz .  Same exact behavior as you described.   Ultimately, I GAVE UP trying to remap it in my local config and ultimately changed the source located at `.local/share/lunarvim/site/pack/lazy/opt/oil.nvim/lua/oil/config.lua`

@stevearc suggestion did not work for me. Maybe @stevearc can investigate this further.

**Comment by stevearc** [comment]
Can you provide a minimal repro? I used this file and with `nvim -u repro.lua .` I found that `<C-k>` opened a vsplit and `<C-s>` did nothing, both as expected.

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/oil.nvim",
    config = function()
      require("oil").setup({
        keymaps = {
          ["<C-s>"] = false,
          ["<C-k>"] = "actions.select_vsplit",
        },
      })
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by sbancuz** [comment]
I can't replicate the bug anymore, maybe I was just configuring it wrong after following some old issue. But what you provided works. Sorry to have bothered you for nothing.

**Comment by stevearc** [comment]
Ah, no worries. Could have been a typo; happens to the best of us
