### ISSUE TITLE
feature request: Auto-save compatibility

### ISSUE THREAD

**Issue by LintaoAmons** [stevearc/oil.nvim#22]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Don't trigger when `:w`, trigger by another shortcut

### Provide background

I use plugin `auto-save` so `:w` will automatically called by the plugin.

This behavior will trigger `Oil` unintentionally

So maybe this should be a dedicate shortcut to trigger Oil and remove the trigger binding to saving event

**Comment by stevearc** [comment]
The auto-save plugin you're using should have a way to disable it for certain buffers. You can use a FileType autocmd to disable it for all `oil` buffers.
