### ISSUE TITLE
feature request: Put deleted files/directories into trash

### ISSUE THREAD

**Issue by nico-heinrich** [stevearc/oil.nvim#222]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Whenever I delete a file or folder, I want to be able to recover the data via the operating system's trash.

### Provide background

Right now, oil feels like a sharp knife. Very capable but dangerous at the same time. I just deleted some files unintentionally and it would have been amazing if they ended up in the trash before vanishing completely.

**Comment by stevearc** [comment]
`:help oil-trash`

**Comment by nico-heinrich** [comment]
Wow, I love you!
