### ISSUE TITLE
feature request: sending items to quickfix

### ISSUE THREAD

**Issue by lpoto** [stevearc/oil.nvim#223]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be very useful to provide an action in "oil.actions" that allows sending all the files from the currently opened oil buffer to the quickfix list.

### Provide background

As an example, you want to edit all the files adjacent to the currently opened file. You could open the oil buffer and send all files to quickfix, then simply run a command over all the elements in the quickfix, or just iterate over them.

At the moment, I am using a custom function for this, since I find it much better, in the scenario described above, than opening Telescope or something similar and writing a prompt that matches the desired files. Having this built-in would be very convenient, since you could just add the following keymap to config:
```lua
keymaps = {
  ['<C-q>'] = 'actions.send_files_to_quickfix'
}
```

### Additional details

If this is something that would not go against the goals of the project, and is useful enough to be a part of the bulitin actions, I can implement this myself, since it is quite simple and does not seem like it would require any heavy maintenance in the future.

**Comment by garrett361** [comment]
@lpoto would you mind posting your custom function for this? I was just about to sit down and figure out how to write my own, but decided to search the issues first. Thank you!

**Comment by lpoto** [comment]
> @lpoto would you mind posting your custom function for this? I was just about to sit down and figure out how to write my own, but decided to search the issues first. Thank you!

```lua
local function oil_files_to_quickfix()
  if vim.bo.filetype ~= 'oil' then return end
  local oil = require 'oil'
  local dir = oil.get_current_dir()

  local entries = {}
  for i = 1, vim.fn.line '$' do
    local entry = oil.get_entry_on_line(0, i)
    if entry and entry.type == 'file' then
      table.insert(entries, { filename = dir .. entry.name })
    end
  end
  if #entries == 0 then return end

  vim.fn.setqflist(entries)
  return vim.cmd.copen()
end
```
@garrett361 I am using something like this

**Comment by garrett361** [comment]
Thank you!

**Comment by stevearc** [comment]
This would be a reasonable action to add
