### ISSUE TITLE
feature request: Better Custom Sort Behavior

### ISSUE THREAD

**Issue by shakesbeare** [stevearc/oil.nvim#224]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to be able to further customize the sorting behavior of the buffer. Specifically, I would like files to first be sorted by their extension and then again by their name. 

```
Ex:
foo/
a.c
z.c
a.h
z.h

Not:
foo/ 
a.c
a.h
z.c
z.h
```

If this is already possible, please let me know how to do it. If this is the case, please consider this feature requesting improved documentation surrounding sorting instead. 

### Provide background

I find it visually hard to keep track of files when the filetypes are mixed with each other. 

### Additional details

I've searched for similar issues and couldn't find anything. :help oil-columns doesn't seem to expose the file extension.

[Nvim-tree](https://github.com/nvim-tree/nvim-tree.lua/blob/80cfeadf179d5cba76f0f502c71dbcff1b515cd8/doc/nvim-tree-lua.txt#L660C1-L660C1) allows you to pass a function to implement whatever custom sorting you want, exposing table elements for each items attributes (name, extension, type, etc). It also allows strings to simplify common sorting methods.

**Comment by stevearc** [comment]
A lot of the components of oil are tightly coupled (e.g. sorting, columns, performance optimizations), which means they are much more difficult to customize. The somewhat limited sorting capabilities that are currently exposed are structured in a way that will play nice with the other systems. While it's technically possible to enable custom sorting, the API would be unfriendly and it would have to some with a lot of notes about edge cases and unexpected behavior. That kind of API will add more maintenance burden for me than it's worth. Closing this as out of scope.
