### ISSUE TITLE
feature request: Remap confirm changes

### ISSUE THREAD

**Issue by Ramilito** [stevearc/oil.nvim#225]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to remap the confirm button, in my case I would want to hit Enter key to confirm. I think that others might want to use Y/N
I'm guessing the prompt text needs to change to reflect that as well.

Something like this:
<img width="507" alt="image" src="https://github.com/stevearc/oil.nvim/assets/8473233/d361734e-2ff8-461c-a0ea-e111a708d988">

### Provide background

I believe this would be a standard behaviour, I rarely see O used as a confirmation prompt

**Comment by stevearc** [comment]
It's easy to remap these keys, see https://github.com/stevearc/oil.nvim/issues/114#issuecomment-1571332722

**Comment by huix9527** [comment]
Everytime I press O to confirm, vim quits...

**Comment by stevearc** [comment]
@huix9527 this sounds unrelated to this issue. If you have a problem please file a new issue and follow the template to create a minimal repro.
