### ISSUE TITLE
bug: v_g_CTRL-A breaks id

### ISSUE THREAD

**Issue by JulianGCalderon** [stevearc/oil.nvim#229]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

Linux Mint 21.2 x86_64

### Describe the bug

`g<C-A>` does not work on oil buffer:
- It does not increment the number
- It breaks the entry id: "Could not find existing entry (was the ID changed?)"

Individual `<C-A>` does work

### Steps To Reproduce

1. Open oil explorer
2. Yank a file with a number in its name and paste it two times
3. Select both new lines
4. Press: `g<C-A>`
5. Save

### Expected Behavior

The numbers are expected to increase, and saving should not fail

### Directory structure

Mongo 1.py
Mongo 2.py
Mongo 3.py

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This is expected. Oil uses id numbers in order to track files that have been copied/moved/renamed. These numbers are at the beginning of the line, but are typically concealed. Do `:set conceallevel=0` to see what's actually happening when you select the lines and increment the number.

To have this work as expected, try using visual block mode to avoid selecting ranges with the id number
