### ISSUE TITLE
bug: oil-ssh:// paths don't work when show_hidden and size or permissions are enabled

### ISSUE THREAD

**Issue by goncrafa** [stevearc/oil.nvim#235]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.9.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/__w/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include

### Operating system/version

CentOS Linux release 7.3, Linux 3.10.0-1127.10.1.el7.x86_64

### Describe the bug

I am unable to use `oil-ssh` to browse or edit filesystems and files in remote hosts **when hidden files (starting with `.`) and size or permissions are shown**.

|`show_hidden`|`size`|`permissions`|stack traceback|
|-------------|------|-------------|-----------|
|disabled|any|any|no|
|enabled|enabled|disabled|yes|
|enabled|disabled|enabled|yes|
|enabled|enabled|enabled|yes|

The stack traceback shown is as follows:

```
Error executing vim.schedule lua callback: ...ig/nvim/pack/oil/start/oil.nvim/lua/oil/adapters/ssh.lua:112: attempt to index local 'meta' (a nil value)
stack traceback:
        ...ig/nvim/pack/oil/start/oil.nvim/lua/oil/adapters/ssh.lua:112: in function 'render'
        ....config/nvim/pack/oil/start/oil.nvim/lua/oil/columns.lua:125: in function 'render_col'
        ...el/.config/nvim/pack/oil/start/oil.nvim/lua/oil/view.lua:600: in function 'format_entry_cols'
        ...el/.config/nvim/pack/oil/start/oil.nvim/lua/oil/view.lua:528: in function 'render_buffer'
        ...el/.config/nvim/pack/oil/start/oil.nvim/lua/oil/view.lua:698: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps To Reproduce

1. nvim oil-ssh://<hostname>/<path>

### Expected Behavior

After the `Loading` bar and the `ssh <hostname>` terminal window, the `<path>` specified in the command line would be opened and shown and be editable.

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- "permissions" by itself triggers the issue.
              -- "size" by itself triggers the issue.
              -- I included both for the sake of completeness.
              columns = {
                "permissions",
                "size",
              },
              view_options = {
                -- Show files and directories that start with "."
                -- Without this option, permissions and size work fine.
                show_hidden = true,
              },
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Thanks for the report! Fixed now
