### ISSUE TITLE
feature request: do not close preview when cd into dir

### ISSUE THREAD

**Issue by al1-ce** [stevearc/oil.nvim#236]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Current behaviour:
- press `-`
- press `ctrl+p`
- select dir and press `enter`
- preview closes

Desired behaviour:
- press `-`
- press `ctrl+p`
- select dir and press `enter`
- preview stays open and switches to selected file in cd'd dir

**Comment by umlx5h** [comment]
I found weird behaviour regarding this issue.

1. entering directory when preview window is on
2. pressing `-` to go up, then preview window is still.
3. entering <CR> on `../` to go up, then preview window is gone.
