### ISSUE TITLE
feature request: allow skipping confirmation for all edits, not just simple ones

### ISSUE THREAD

**Issue by CWood-sdf** [stevearc/oil.nvim#239]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Could there be a config option to skip confirm for all edits?

### Provide background

I don't like having to confirm whether I want to delete a file or not, I'd rather just save the buffer without it having to ask for confirmation

**Comment by stevearc** [comment]
I explicitly do not make this straightforward because applying changes without looking at them first can be very dangerous. However, you can do this with the API by passing `confirm = false` to `save()` https://github.com/stevearc/oil.nvim/blob/master/doc/api.md#saveopts-cb

**Comment by jake-stewart** [comment]
until this feature is added, or support for `:w` is added, i'll be using [this patch](https://github.com/stevearc/oil.nvim/commit/83674c3c129b307b7c41407c33f2da0e6a03d7b2).

**Comment by stevearc** [comment]
It's dangerous in the same way that rm is dangerous, but there's an extra degree of indirection because there's the possibility that you unintentionally made a change that modified the (concealed by default) ids at the start of the line, using a `:%s/` command or macro or similar. I've tried very hard to make the behavior intuitive, but since these edge cases still exist I don't want to make it _easy_ to disregard the confirmation window.

**Comment by jake-stewart** [comment]
> It's dangerous in the same way that rm is dangerous, but there's an extra degree of indirection because there's the possibility that you unintentionally made a change that modified the (concealed by default) ids at the start of the line, using a `:%s/` command or macro or similar. I've tried very hard to make the behavior intuitive, but since these edge cases still exist I don't want to make it _easy_ to disregard the confirmation window.

annoying tbh

i have it set up so that lines without the ids are highlighted green. i can easily tell when a file is being deleted instead of renamed. i can't imagine an edge case where the tool is any more dangerous than rm

```lua
        vim.api.nvim_create_autocmd("filetype", {
            pattern = "oil",
            callback = function()
                vim.defer_fn(function()
                    vim.cmd.syn("match", "DiffAdd", "/\\v(^\\/[0-9]* )@!<.*/")
                end, 100)
            end
        })
```
