### ISSUE TITLE
bug: chdir failed when opening oli with :Oil

### ISSUE THREAD

**Issue by JoseConseco** [stevearc/oil.nvim#24]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

Latest daily nvim build

### Operating system/version

Linux majaro

### Describe the bug

Runing :Oil  
gives this error:
![obraz](https://user-images.githubusercontent.com/13521338/211336819-45caf95f-81a5-44b6-a391-0a7d690eba90.png)

After creating new line as saving buffer - [O]k  - I get this error now:
![obraz](https://user-images.githubusercontent.com/13521338/211337058-718f9def-db4f-4293-bb21-17f9b67ed6c6.png)

### Steps To Reproduce

1. Open some session in nvim with folder and few files inside
2.  run :oil  <cr> 
3. Get error above. Maybe its due to using nightly build ? Someone can confirm? 

### Expected Behavior

No error

### Directory structure

![obraz](https://user-images.githubusercontent.com/13521338/211337559-1405ce2e-1dc8-43d9-aaa6-dc40610e6587.png)
pwd: 
![obraz](https://user-images.githubusercontent.com/13521338/211337633-5fd02a63-a3aa-4f85-8097-1383df13c69a.png)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require"oil".setup() -- add any needed settings here
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
I tried on nightly, and it seems to work fine. I suspect there may be something conflicting in your personal dotfiles; the line 
```
[C]: in function 'chdir'
/home/bartosz/.config/nvim/init.lua:124: in function </home/bartosz/.config/nvim/init.lua:105>
```
seems to indicate that it has something to do with a function in your init.lua.

If you use the repro init.lua listed above (by saving it to repro.lua and doing `nvim -u repro.lua`), can you get the issue to reproduce?

**Comment by JoseConseco** [comment]
Ah, my  bad. You right, that was my auto cd into current file  root dir auto-command failing  (could not cd into  oil////dir/xyz/ ).  Thanks for help
