### ISSUE TITLE
bug:  Suddenly getting 'E17' 'is-a-directory' error on directory save after config change

### ISSUE THREAD

**Issue by elmarsto** [stevearc/oil.nvim#252]
**EDIT: see comment below for correct diagnosis and solution. It's kind of interesting. I'm not sure if it's expected behaviour but it *is* surprising. Leaving this here for other folks to learn from.**
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

b3c24f4b3

### Operating system/version

NixOS 23.11

### Describe the bug

After upgrading to this commit: https://github.com/stevearc/oil.nvim/commit/b3c24f4b3b2d38483241292a330cd6eb00734dac (**NOTE: this is not the cause, see comment below **)

I'm now seeing 
![image](https://github.com/stevearc/oil.nvim/assets/315987/154d2469-d7b9-4c36-a986-8f8ce464798d)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

Open nvim
:e .
<rename a file>
:w 

### Expected Behavior

I get asked if I want to write to the dir

### Repro

```Lua
I don't have time for this, I'm under deadline pressure, but FYI yeah
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by elmarsto** [comment]
Interestingly, I *do* get asked (by oil) when I do `ZZ` (:wqa equivalent)

**Comment by elmarsto** [comment]
OK I fixed this. It was a config error. BUT an interesting one! 

Turns out if you tell `oil` that ':' is a hotkey for `actions.open_cmdline_dir` this happens. 

The prompt that's pulled up by `open_cmdline_dir` will throw E17 errors if you try to write

**Comment by stevearc** [comment]
This is not a bug. `actions.open_cmdline_dir` is supposed to be used to quickly run commands on the current directory. Binding it to `:` is not recommended, because it interferes with _anything_ you would want to do with command mode. I would recommend using a different keybind (`<leader>:` perhaps).
