### ISSUE TITLE
bug: Oil adapter scheme error when opening from tpope/vim-fugitive buffer?

### ISSUE THREAD

**Issue by jesseleite** [stevearc/oil.nvim#256]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 14.2

### Describe the bug

![CleanShot 2023-12-19 at 11 08 26](https://github.com/stevearc/oil.nvim/assets/5187394/b0eb905f-d544-4b0b-b690-0fac9c5c4664)

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

- Run `:Git` to open vim-fugitive buffer from within a project with a .git repo
- Run `:Oil` from fugitive buffer

### Expected Behavior

Would expect Oil to just silently open to project root, if it can't find file/scheme.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  "tpope/vim-fugitive",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by jesseleite** [comment]
PS. Been using oil.nvim for a few months, and absolutely loving it. Thank you @stevearc for the rad work on this awesome plugin 🔥💘

**Comment by stevearc** [comment]
Thanks for the report, should be fixed!

**Comment by jesseleite** [comment]
Works great! Thank you Steve! ❤️
