### ISSUE TITLE
feature request: Option to show entire absolute path of file + integrate nicely with moving + renaming

### ISSUE THREAD

**Issue by shaun-mathew** [stevearc/oil.nvim#26]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Add a toggle or option to display absolute paths of a file or up until project root. With this option toggled, the user would be able to perform more complex bulk renames/moves faster.

### Provide background

I currently have a folder structure like so:
```
a/
    b/
        c/
            1.file
            2.file
            3.file
```

and I am trying to move a subset of the .files to the same level as the root directory a, but under a new folder, so something like this

```
a/
    b/
        c/
            1.file
a.1/
    2.file
    3.file
```

**Comment by stevearc** [comment]
Changing oil to be anything like a file tree or, as you suggest, selectively display absolute paths is going to be a very hard sell. Either of those options would be a very significant amount of work and added complexity/maintenance burden. I could be convinced if the benefits are _also_ significant, but I'm skeptical of this use case. The move operation you wanted seemed...pretty fast already to me. 

https://user-images.githubusercontent.com/506791/211722555-f1b95a75-e1c6-458d-a522-fdd9412fa92e.mov

**Comment by vishes-shell** [comment]
@stevearc i just wanted to say that i admire your work, and moving files in the way that is shown in video looks like magic! 🪄

**Comment by shaun-mathew** [comment]
I suppose the I've given example is a bit contrived. Perhaps it might be more useful when you want to edit the structure of a lot of files in several different folders within a project simultaneously using macros or the g command, but this use case feels a bit too niche and infrequent.

**Comment by stevearc** [comment]
Yeah anything that requires viewing all the files in a directory recursively is not going to play nice with the current architecture. I'm going to close this as out of scope.
