### ISSUE TITLE
bug: can't open marks from oil buffer 

### ISSUE THREAD

**Issue by rudiejd** [stevearc/oil.nvim#266]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1746+g5651c1ff2

### Operating system/version

Ubuntu 22.04.3 LTS

### Describe the bug

first of all, great work on this plugin! I've been loving it so far. And also good idea on the check boxes, I might rip that off.

Anyway, my issue here is that I can't navigate to marks from the Oil buffer

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. nvim -u repo.lua test.txt
2. Set a mark in test.txt e.g. :mark A
3. Open oil
4. Try to go to said mark e.g. `A or g`A
5. Observe that this is not possible

### Expected Behavior

You should be able to navigate to marks from Oil. I use this a lot to navigate to mark 0

### Directory structure

test.txt

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Ah, oil binds the \` key by default. You can disable this like so

```lua
require("oil").setup({
  keymaps = {
    ["`"] = false,
  },
})
```

Or you can use the single quote `'` to jump to marks
