### ISSUE TITLE
bug: open oil in "VimEnter" event

### ISSUE THREAD

**Issue by perryrh0dan** [stevearc/oil.nvim#268]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.0-dev-1613+g585eeacb2

### Operating system/version

Ubuntu 23.10

### Describe the bug

Hi there, 

First of all, thanks for creating this really great Neovim plugin.

I want to open oil directly when opening nvim if the user has not selected a specific file. My VimEnter callback looks like this:
![image](https://github.com/stevearc/oil.nvim/assets/28621009/397d87fc-2e35-4878-9f0b-8007c1b16d01)

Unfortunately oil opens in a broken state:

![image](https://github.com/stevearc/oil.nvim/assets/28621009/0f0e9554-0884-4f39-b72f-dd39419f5f45)

The buffer is completely empty and I can't make any changes. I use lazy as my package manager. I have also tried different user events from lazy.nvim like "LazyDone" but the same problem occurs.

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. open nvim

### Expected Behavior

Oil should work

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

vim.api.nvim_create_autocmd('VimEnter', {
    callback = function(data)
        vim.print(vim.fn.isdirectory(data.file))
        if (data.file == '' or vim.fn.isdirectory(data.file) ~= 0) then
            vim.print(data.file)
            require('oil').open()
        end
    end
})


-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Add a `schedule_wrap` to your callback

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	callback = vim.schedule_wrap(function(data)
		vim.print(vim.fn.isdirectory(data.file))
		if data.file == "" or vim.fn.isdirectory(data.file) ~= 0 then
			vim.print(data.file)
			require("oil").open()
		end
	end),
})
```
The problem is that Oil relies on the `:help BufReadCmd` autocmd to load and populate a buffer, but autocmds get a little weird with nesting. Usually you can define an autocmd to explicitly continue to be called even if it's inside another autocmd, and we are doing that in oil
https://github.com/stevearc/oil.nvim/blob/c4cc8240f1c71defcb67c45da96e44b968d29e5f/lua/oil/init.lua#L970
But for some reason, it still doesn't get triggered when calling `:edit oil:///home/user/` during VimEnter. I don't know the _exact_ mechanism of the bug; maybe VimEnter is special, maybe BufReadCmd is special, or maybe there's actually something else at work, but I do know that adding a small delay with `schedule_wrap` fixes the problem.

**Comment by perryrh0dan** [comment]
Thanks for the quick replay, the workaround works perfectly.

Best regards
Thomas
