### ISSUE TITLE
feature request: use folds for folders

### ISSUE THREAD

**Issue by nkakouros** [stevearc/oil.nvim#270]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be nice to be able to toggle folders in a buffer with zc/zm/zr/.... For example, if the `foo/` folder contains a `bar` file, then if the buffer looks like:

```
foo/
```

pressing `zo` on `foo/` would show:

```
foo/
  bar
```

or 

```
foo/
foo/bar
```

### Provide background

This would further improve the "filesystem as a buffer" metaphor.

### What is the significance of this feature?

nice to have

### Additional details

I realize this plugin is on the netwr instead of the NERDtree side, but maybe the "filesystem as a buffer" part is prioritized more than the "netwr-like" part.

**Comment by stevearc** [comment]
Though it sounds like a simple request, it would actually necessitate a complete re-write. The way that we track file moves and renames is by putting an ID at the beginning of the line (which you can see if you `:set conceallevel=0`. Currently we have a very useful guarantee of there being a 1-to-1 mapping of buffer to directory. If a file's ID appears somewhere, that means that we should move/copy the file to that buffer's corresponding directory.

If we add a system like this, suddenly any given file could be referenced in any arbitrary parent buffer. So if we see a file ID in some buffer...should we move it there? Was this the canonical location? Or was this a location that was made visible by expanding a tree?

On top of that there are a ton of other UX issues surrounding communicating the UI clearly to the user. Let's say you delete `foo/bar` from one buffer and paste it into another one, then save. Did you intend to move the `bar` file to this new buffer? Or did you intend to make a new directory named `foo` and move `bar` into it? It's much more difficult to work out user intent, and there are now multiple ways to do file moves.

This might be technically feasible, and maybe with enough effort the UX could be made to be sufficiently intuitive, but it is far, far out of scope for this project.
