### ISSUE TITLE
feature request: open_external uses explorer.exe instead of wslview

### ISSUE THREAD

**Issue by vunhatchuong** [stevearc/oil.nvim#273]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Right now `get_open_cmd(path)` uses `wslview` to open file in external editor, which is really slow and require user to download [a package from external PPA](https://wslutiliti.es/wslu/install.html#ubuntu). WSL has [builtin](https://learn.microsoft.com/en-us/windows/wsl/filesystems#view-your-current-directory-in-windows-file-explorer) way to open which is much faster using: `explorer.exe`

### Provide background

`wslview` requires external PPA and slower than builtin `explorer.exe` way.

### What is the significance of this feature?

nice to have

### Additional details

In `lua/oil/actions.lua` you can change this function on line `178`:
```lua
local function get_open_cmd(path)
                   ....
  elseif vim.fn.executable("wslview") == 1 then
    return { "wslview", path }
                   ....
```
Into
```lua
local function get_open_cmd(path)
                   ....
  elseif vim.fn.executable("explorer.exe") == 1 then
    return { "explorer.exe", path }
                   ....
```

**Comment by stevearc** [comment]
This logic was copied from the `vim.ui.open` implementation in Neovim core
https://github.com/neovim/neovim/blob/367e52cc79a786bbee4456b30f9ec5db7e28d6a5/runtime/lua/vim/ui.lua#L146-L147

If you think that `explorer.exe` is the correct way to open files in an external program, I would strongly suggest creating a PR for Neovim! Oil will adopt whatever logic Neovim uses (with the intent to use `vim.ui.open` directly once https://github.com/neovim/neovim/issues/24567 is resolved)

**Comment by vunhatchuong** [comment]
I've made a pull rebase [neovim/pull/26947](https://github.com/neovim/neovim/pull/26947)

**Comment by vunhatchuong** [comment]
The pull request has been merged btw.

**Comment by stevearc** [comment]
Awesome! I've updated the action
