### ISSUE TITLE
bug: "No filename found" diagnostic not showing

### ISSUE THREAD

**Issue by simonmandlik** [stevearc/oil.nvim#275]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1506+g610f50dda-Homebrew

### Operating system/version

MacOS 14.2.1

### Describe the bug

Floating diagnostics work fine for me, e.g. when there is a duplicate filename. The diagnostic is visible and I can jump to it with `vim.diagnostic.goto_next`:

<img width="251" alt="image" src="https://github.com/stevearc/oil.nvim/assets/16707112/cdc33ba0-ae04-4e14-9802-b804f55c3129">

However, when there is a file without any filename (obtained e.g. with `D`), for some reason the diagnostic float isn't showing:

<img width="251" alt="image" src="https://github.com/stevearc/oil.nvim/assets/16707112/259cde17-b263-45fc-85fc-273e835dfb7c">

and can be only invoked with `vim.diagnostic.open_float`:

<img width="343" alt="image" src="https://github.com/stevearc/oil.nvim/assets/16707112/328bb86d-fcd1-4159-ae8d-3061b0d53dbf">

Is this intended?

I have tried with the provided minimal config, and, weirdly, `vim.diagnostic.goto_next` does not show the floating window even in the first case.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1.`nvim -u repro.lua test`
2. `:Oil`
3. As described above

### Expected Behavior

As described above

### Directory structure

```
test/test.txt
```

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

vim.diagnostic.config {
    virtual_text = false,
}

vim.keymap.set("", "]d", function() vim.diagnostic.goto_next() end)
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Fixed. Thanks for the report!
