### ISSUE TITLE
bug: Oil not exiting on `ZZ` and on custom mapping

### ISSUE THREAD

**Issue by simonmandlik** [stevearc/oil.nvim#278]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1506+g610f50dda-Homebrew

### Operating system/version

MacOS 14.2.1

### Describe the bug

When I make changes with `nvim .` and use `:wq` or `:x`, everything works fine and after confirmation neovim immediately exits.

However, this doesn't work for `ZZ` and for custom mapping to `:x`.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

See above.

### Expected Behavior

I would expect `nvim` to exit both on `ZZ` and on pressing (mapped) `ZX`.

### Directory structure

test/test1.txt
test/test2.txt
test/test3.txt

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

vim.keymap.set("", "ZX", ":x<CR>")
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This is a limitation in Neovim. The `:wq` support right now is a complete hack where I inspect the last command issued to see if it's `:wq`, and if so issue a quit after the file operations are complete. Unfortunately there seems to be no way to check for `ZZ`, and certainly not for a custom map.

You can support this in your own config by adding buffer-local keymaps to oil

```lua
require("oil").setup({
  keymaps = {
    ZZ = function()
      require("oil").save({}, function()
        vim.cmd.quit()
      end)
    end,
  },
})
```
