### ISSUE TITLE
Documentation improvement: Define simple operation

### ISSUE THREAD

**Issue by alydh-annotell** [stevearc/oil.nvim#283]
For the option `skip_confirm_for_simple_edits` there is no definition what a simple edit/operation is.

Looking at `lua/oil/mutator/preview.lua is_simple_edit` it seems like everything but the follow list is considered simple.

- delete
- copy/move across adapters
- multiple moves or copies at the same time
- more than 5 creates

Could this be added to the docs somewhere?

**Comment by stevearc** [comment]
Added an explanation to the help docs
