### ISSUE TITLE
bug: `conceallevel` not being set correctly when preview is open

### ISSUE THREAD

**Issue by mehalter** [stevearc/oil.nvim#287]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

Arch Linux

### Describe the bug

When you have the preview window open (specifically before you have navigated into a folder so it creates a new buffer for it) the conceal level is not being correctly set to 3 and exposes all of the ids.

Here is a recording if that's useful: https://asciinema.org/a/xlmjtHyHkDX1J0ywNnMuNMHVr

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. `nvim -u repro.lua`, use repro.lua config
2. `:Oil`, run oil
3. `<C-p>`, open preview immediately
4. Navigate into the `dir` folder and see the conceal level is incorrect

### Expected Behavior

`conceallevel` should be set to 3 and hide the entry ids.

### Directory structure

```
dir/a
dir/b
dir/c
```

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by uncl0g** [comment]
I stumbled into the samme issue and [this line](https://github.com/stevearc/oil.nvim/blob/bf753c3e3f8736939ad5597f92329dfe7b1df4f5/lua/oil/init.lua#L636) seems to be responsible for overriding the window scoped options when setting the buffer.

I was not aware of this behavior and could not find a nice way to deal with it. So locally I am just setting the win_options once again.

```lua
local view = require("oil.view")
view.set_win_options()
```

**Comment by stevearc** [comment]
This should be fixed now
