### ISSUE TITLE
feature request: auto-detect file changes in cwd and refresh view

### ISSUE THREAD

**Issue by fralomb** [stevearc/oil.nvim#292]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be great if oil could be able to detect that a file or directory has been modified outside neovim and, consequentially, reflect the updated status of the current working directory in the oil buffer.

### Provide background

If i create some files or folders from outside neovim, i do not have a view in oil of what my repository currently look like until i close and reopen neovim

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
I added the `experimental_watch_for_changes` option that enables this. It uses the libuv fs_event to watch open directories for changes. You'll need to opt in to the behavior for now, but at some point in the future once I'm convinced that it's stable I'll make this the default behavior and change the config option name to not be experimental.

**Comment by fralomb** [comment]
thank you @stevearc, it is working pretty well actually!
