### ISSUE TITLE
feature request: Add option to open oil in git root

### ISSUE THREAD

**Issue by timofurrer** [stevearc/oil.nvim#297]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

The Oil command should support a `--in-git-root` to set the cwd to the git repository root.

### Provide background

I want to be able to easily configure a key mapping that opens oil in the root of the git repository.

### What is the significance of this feature?

strongly desired

**Comment by timofurrer** [comment]
I'm currently using `lspconfig` to find the git ancestor, but it's not as nice.

**Comment by stevearc** [comment]
Thanks @gregdezeeuw! That is the recommended solution for this. I won't be adding a special option for this, so creating your own custom binding for it is the way to go.
