### ISSUE TITLE
starting manually

### ISSUE THREAD

**Issue by max397574** [stevearc/oil.nvim#3]
not sure if I missed something
but is there a way of starting this manually from nvim?
I'm thinking about sth like dirbuf.nvim has
you can do `:Dirbuf` to open the cwd and `:Dirbuf <folder>` to open that folder

**Comment by stevearc** [comment]
Sure! There's the [open()](https://github.com/stevearc/oil.nvim/#opendir) and [open_float()](https://github.com/stevearc/oil.nvim/#open_floatdir) API methods. Additionally, you can `:e <directory>` and that should open oil as well.

**Comment by max397574** [comment]
thank you
(btw you shouldn't be afraid of closing issues yourself)

**Comment by max397574** [comment]
could you expose a command?
or two? (like `Oil` and `OilFloat`) which take a directory as argument
you could also just make the option to add a `--float` as last argument

because that would make it accessible for more people
should I open a separate issue for this?

**Comment by UnrealApex** [comment]
Until they make one, this works:
```lua
require('oil').setup()
  vim.api.nvim_create_user_command('Oil', function() 
    require('oil').open()
  end,
    {})
end
```
It creates a command called `:Oil`. Basically the same thing as calling Oil's `open()` function.

**Comment by max397574** [comment]
this won't work with directory argument

**Comment by UnrealApex** [comment]
Ah I see. Though I think since Oil hijacks Netrw maybe using `:edit` is fine?  I understand that having a command would make calling Oil more verbose.

**Comment by stevearc** [comment]
Could you explain a little bit more about _why_ you want a command? I'd like to better understand the underlying need behind the ask.

**Comment by max397574** [comment]
yes
for me it isn't a big deal to use `edit`
there are just two issues with it (for me) for other users they might want to have a command like most other plugins
- I can't open a float like this
- I can't easily lazyload the plugin

**Comment by max397574** [comment]
I'll open a pr

**Comment by UnrealApex** [comment]
You are using Lazy correct? I believe Lazy automatically loads a plugin when it is required. Though this does not work when Oil hijacks Netrw. I have had a similar problem like this when trying to lazy-load Vinegar.

**Comment by max397574** [comment]
lazy doesn't automatically load it
believe me I know what I'm talking about 😆
spent quite some time with this stuff

**Comment by Benson9954029** [comment]
I usually open nvim with folder path(like nvim .) so I config lazy with 
event.=."Syntax",

**Comment by tummetott** [comment]
> I usually open nvim with folder path(like nvim .) so I config lazy with event.=."Syntax",

Thats what i was looking for. thanks
