### ISSUE TITLE
feature request: document/enable proper lazy loading with lazy.nvim

### ISSUE THREAD

**Issue by trevarj** [stevearc/oil.nvim#300]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

When using lazy.nvim, it would be nice to have a way to lazyload the plugin on `BufEnter` when the buffer is a directory.

### Provide background

When you open nvim with `nvim .` or `nvim lua/` it will load Oil and drop you into Oil's interface. 

An example config would be like this:
```lua
  {
    "stevearc/oil.nvim",
    cmd = "Oil",
    event = "BufEnter */", -- would like to have '.' as well
    -- truncated ...
  },
```

For some reason, this is broken for me when I start nvim with `nvim lua/`. It shows that I am in oil (`oil:///home/trevor/Workspace/config.nvim/lua/`) but the interface is blank. If I restart nvim and restore my session, it actually works and shows the directory correctly. I'm too stupid to figure it out or there might be an issue with lazy.

### What is the significance of this feature?

nice to have

**Comment by trevarj** [comment]
Apologies. I 'issued' too soon. If you change the event to `VimEnter` this works well.

Closing, but this could probably be added to the doc about using Oil with lazy

**Comment by trevarj** [comment]
Actually, `VimEnter` isn't the final solution either since this won't work when you're in nvim and do `:e lua/`

**Comment by CWood-sdf** [comment]
i've been using the workaround of adding 

```lua
vim.cmd('Oil')
vim.schedule(function()
    vim.cmd('e')
end)
```

in a function that is called on startup to fix this problem

**Comment by trevarj** [comment]
I've been using 
```lua
    "stevearc/oil.nvim",
    cmd = "Oil",
    event = { "VimEnter */*,.*", "BufNew */*,.*" },
```
It's still not fully correct with the `.*`, but I can't figure out how to only work on `.` (for `nvim .`)

**Comment by kevinm6** [comment]
@trevarj try this, never had problem with my config, even with ssh connections!

https://github.com/kevinm6/nvim/blob/nvim/lua/plugins/editor/oil.lua#L141~165

**Comment by kevinm6** [comment]
@trevarj try this, never had problem with my config, even with ssh connections!

https://github.com/kevinm6/nvim/blob/0c2d0fcb04be1f0837ae8918b46131f649cba775/lua/plugins/editor/oil.lua#L141

**Comment by stevearc** [comment]
Due to the complexity of properly lazy loading oil, I do not recommend it. This is something I do for some of my other plugins, but for oil the triggers are too various and the interactions too complex for me to think it's a good idea. If you want to try, go ahead, but there is no blessed path.
