### ISSUE TITLE
Add current directory to the oil buffer

### ISSUE THREAD

**Issue by dmtrKovalenko** [stevearc/oil.nvim#301]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would be happy if there would be any way to display the current directory inside oil without additional hacks like virtual text and being able to edit the current directory just like you can edit any other file. 

### Provide background

I am working on my little idea project of having oild as a sidebar and it looks very good except for one little thing — it does not display the current directory selected at the top which makes it look raw. 

<img width="1611" alt="image" src="https://github.com/stevearc/oil.nvim/assets/16926049/e2dde51d-5f04-4c2b-8cef-edf54caa0704">

### What is the significance of this feature?

cannot use this plugin without it

**Comment by stevearc** [comment]
The recommended way to do this would be by using the winbar (see `:help winbar`). You can set that to a custom function that displays the output of `oil.get_current_dir()`, or you could show the raw buffer name. Editing the name of the directory that oil is currently displaying is probably not going to happen. It's more complex than you think, and the benefit is small.

**Comment by Gelio** [comment]
For anyone wondering how to set the winbar to display the path, I used

```lua
			win_options = {
				winbar = "%{v:lua.require('oil').get_current_dir()}",
			},
```

https://github.com/Gelio/ubuntu-dotfiles/blob/eee2e9914df726d63870cf1174b80f08f938abc4/universal/neovim/config/nvim/lua/plugins/file-tree.lua#L13

**Comment by jdsee** [comment]
> For anyone wondering how to set the winbar to display the path, I used
> 
> ```lua
> 	win_options = {
> 		winbar = "%{v:lua.require('oil').get_current_dir()}",
> 	},
> ```
> 
> https://github.com/Gelio/ubuntu-dotfiles/blob/eee2e9914df726d63870cf1174b80f08f938abc4/universal/neovim/config/nvim/lua/plugins/file-tree.lua#L13

Thanks, very helpful :pray: 

I added a highlight group (`@attribute.builtin`) and shortened the home-path to `~`. I find it easier on the eyes this way. You can find available highlight groups of your theme with `:Telescope highlights`.

```lua
win_options = {
    winbar = "%#@attribute.builtin#%{substitute(v:lua.require('oil').get_current_dir(), '^' . $HOME, '~', '')}",
}
```

![image](https://github.com/user-attachments/assets/6339faa7-a72b-4535-a185-ec8c4e86d697)

**Comment by jimafisk** [comment]
@dmtrKovalenko is your project public? I'd like to use it :). Thanks!

**Comment by dmtrKovalenko** [comment]
@jimafisk I dropped the idea and instead made something totally different 

https://www.reddit.com/r/neovim/s/PgkXt1cpjP
