### ISSUE TITLE
feature request: Add option to specify preview split direction

### ISSUE THREAD

**Issue by omerchn** [stevearc/oil.nvim#304]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

A `preview.split_direction` option to specify in which direction the preview split (`<C-p>`) opens

### Provide background

When I opened the preview split with `<C-p>` it always used to open to the right, but now after updating Oil it always opens to the left 🤔 
I would really appreciate the option to specify the direction. Thank you!

### What is the significance of this feature?

nice to have

**Comment by omerchn** [comment]
I also noticed now that the `<C-s>` functionality also flipped - the vertical split is created to the left instead of the right 🤔 
Is this expected?

**Comment by omerchn** [comment]
closing this as I no longer use oil

**Comment by dudicoco** [comment]
@stevearc can we reopen this please?
I'm also interested in this feature.

**Comment by moyukhc** [comment]
+1 to re-opening this request, I'd love to be able to tile my preview windows from NE as opposed to NW splits. I think you could just expose the `nvim_open_win.anchor` [parameter](https://neovim.io/doc/user/api.html#nvim_open_win()) from the neovim API docs?

Many thanks!

**Comment by Florian-Merle** [comment]
Setting `vim.opt.splitright = true` works. See https://github.com/stevearc/oil.nvim/blob/master/lua/oil/init.lua#L471

Ideally, it would be great to have an oil option for that though

**Comment by AdrianZajkowski** [comment]
I have similar issue with the `<C-s>` functionality. It opens vertical split always on the left. Does anyone have solution how to fix it and open split on the right side?
