### ISSUE TITLE
feature request: Natural sorting

### ISSUE THREAD

**Issue by EJIqpEP** [stevearc/oil.nvim#306]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

A possibility to add natural sort so files with numbers are sorted correctly

### Provide background

I have a numbered list of files in the folder. Oil sorts them like this
1
...
10
100
101
...
11

### What is the significance of this feature?

cannot use this plugin without it

### Additional details

I didn't find anything in docs or open issues which allows to sort files. For example nvim-tree has the same problem but you can provide a sorting function to it to implement a custom sorting.

**Comment by EJIqpEP** [comment]
No comment at all? Is this feature implemented/planned? Or the project is abandoned?

**Comment by lucaseras** [comment]
@stevearc we can close this issue! Thanks again for the review
