### ISSUE TITLE
feature request: Add events to allow integrations

### ISSUE THREAD

**Issue by wojciech-kulik** [stevearc/oil.nvim#310]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be great to be able to subscribe to CRUD events (add/delete/rename) for files and folders. It would allow for integration with other plugins.

### Provide background

I'm working on a plugin ([xcodebuild.nvim](https://github.com/wojciech-kulik/xcodebuild.nvim)) that allows you to manage project files, each change in file structure must update project file. Currently, I provide simple functions to work with files, but for users it would be much more convenient to use their file manager. I'm already working on integration with nvim-tree, because they expose events. However, as far as I was able to check there is no such thing in Oil.

### What is the significance of this feature?

strongly desired

**Comment by wojciech-kulik** [comment]
Here are events provided by nvim-tree, just for the reference:
```
- Event.WillRenameNode
                • Note: A node can either be a file or a directory.
                handler parameters: ~
                  {old_name}     `{string}` Absolute path to the old node location.
                  {new_name}     `{string}` Absolute path to the new node location.

- Event.NodeRenamed
                • Note: A node can either be a file or a directory.
                handler parameters: ~
                  {old_name}     `{string}` Absolute path to the old node location.
                  {new_name}     `{string}` Absolute path to the new node location.

- Event.FileCreated
                handler parameters: ~
                  {fname}        `{string}` Absolute path to the created file

- Event.WillCreateFile
                handler parameters: ~
                  {fname}        `{string}` Absolute path to the file to be
                  created

- Event.FileRemoved
                handler parameters: ~
                  {fname}        `{string}` Absolute path to the removed file.

- Event.WillRemoveFile
                handler parameters: ~
                  {fname}        `{string}` Absolute path to the file to be
                  removed

- Event.FolderCreated
                handler parameters: ~
                  {folder_name}  `{string}` Absolute path to the created folder.

- Event.FolderRemoved
                handler parameters: ~
                  {folder_name}  `{string}` Absolute path to the removed folder.
```

**Comment by rchatham** [comment]
+1 to this! @wojciech-kulik really appreciate all your work to support mac/ios dev in nvim so far. Found this because I prefer using oil and was curious on how to integrate it with your current work, turns out you are already working on it 😄

**Comment by wojciech-kulik** [comment]
@rchatham haha, nice to meat you here, the internet is a small place 😂

**Comment by wSedlacek** [comment]
Having events would help me too.
I have noticed that often times after I delete a file from disk with oil.nvim I still end up with the buffer open.
I would love a solution for removing buffers when files are deleted from disk.
Events could let me setup autocmds to do that.

**Comment by stevearc** [comment]
Okay, I've added two User autocmds that you can subscribe to: `OilActionsPre` and `OilActionsPost`. These both include the raw actions that oil will/did process in the `data`. Note that since oil supports trash and ssh, these actions are _not_ just simple file paths, but fully-specified urls like `oil:///path/to/file`. You can split this into the `url_scheme` + `url_path` easily with this logic, which you can either copy or call directly:
https://github.com/stevearc/oil.nvim/blob/32e18df30f937e02135398c270b72a4d24b40120/lua/oil/util.lua#L11-L16

The full definition of the shapes of actions can be found in these type definitions:

https://github.com/stevearc/oil.nvim/blob/32e18df30f937e02135398c270b72a4d24b40120/lua/oil/mutator/init.lua#L18-L48

And here's a simple example of subscribing to the events:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "OilActionsPre",
  callback = function(args) vim.print(args) end,
})
vim.api.nvim_create_autocmd("User", {
  pattern = "OilActionsPost",
  callback = function(args)
    -- If err is non-null, we encountered an error while processing the actions
    if args.data.err then
      vim.print("ERROR", args.data.err)
    else
      vim.print(args)
    end
  end,
})
```

**Comment by wSedlacek** [comment]
A practical example. Deleting a file with oil will close the buf open with that file (if any)

```
---@param url string
---@return nil|string
---@return nil|string
local parse_url = function(url)
  return url:match "^.*://(.*)$"
end

vim.api.nvim_create_autocmd("User", {
  pattern = "OilActionsPost",
  callback = function(args)
    if args.data.err then
    else
      for _, action in ipairs(args.data.actions) do
        if action.type == "delete" then
          local path = parse_url(action.url)
          local bufnr = vim.fn.bufnr(path)
          vim.t.bufs = vim.tbl_filter(function(b)
            return b ~= bufnr
          end, vim.t.bufs)
        end
      end
    end
  end,
})
```


https://github.com/stevearc/oil.nvim/assets/8206108/04e8d07b-e4c0-4b59-ba21-023e20d07e11

❤️  Thank you for making this possible @stevearc

**Comment by wojciech-kulik** [comment]
Thank you @stevearc!

**Comment by wojciech-kulik** [comment]
@stevearc I get this error when I try moving a file from one folder to another:
<img width="1556" alt="image" src="https://github.com/stevearc/oil.nvim/assets/3128467/208fa78e-22e0-4c88-988c-a646d968866d">

**Comment by wojciech-kulik** [comment]
I started performing multiple operations (one by one) and after moving folder back and forth I got this issue:
<img width="1313" alt="image" src="https://github.com/stevearc/oil.nvim/assets/3128467/b2cd19ea-008c-4381-9d5b-572d5e44c1f2">

**Comment by stevearc** [comment]
@wojciech-kulik please file this as a new issue with complete reproduction steps

**Comment by wojciech-kulik** [comment]
I updated @wSedlacek version to:
```lua
-- close deleted files via oil.nvim
vim.api.nvim_create_autocmd("User", {
  pattern = "OilActionsPost",
  callback = function(args)
    local parse_url = function(url)
      return url:match("^.*://(.*)$")
    end

    if args.data.err then
      return
    end

    for _, action in ipairs(args.data.actions) do
      if action.type == "delete" and action.entry_type == "file" then
        local path = parse_url(action.url)
        local bufnr = vim.fn.bufnr(path)
        if bufnr == -1 then
          return
        end

        vim.cmd("bw " .. bufnr)
      end
    end
  end,
})
```

However, it looks like I can't delete any buffer when floating oil is visible. Even if I manually run `:bw BUFNR` it doesn't work. Only if I close oil.

Any ideas why it is happening?

**Comment by wojciech-kulik** [comment]
I improved the version above:

```lua
-- close deleted files via oil.nvim
vim.api.nvim_create_autocmd("User", {
  pattern = "OilActionsPost",
  callback = function(args)
    local parse_url = function(url)
      return url:match("^.*://(.*)$")
    end

    if args.data.err then
      return
    end

    for _, action in ipairs(args.data.actions) do
      if action.type == "delete" and action.entry_type == "file" then
        local path = parse_url(action.url)
        local bufnr = vim.fn.bufnr(path)
        if bufnr == -1 then
          return
        end

        local winnr = vim.fn.win_findbuf(bufnr)[1]
        if not winnr then
          return
        end

        vim.fn.win_execute(winnr, "bfirst | bw " .. bufnr)
      end
    end
  end,
})
```

as we are still in Oil, we need to use `vim.fn.win_execute`
