### ISSUE TITLE
[windows - trash] bug: delete can't handle non ascii characters

### ISSUE THREAD

**Issue by TheLeoP** [stevearc/oil.nvim#316]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2397+ga9f578b7a

### Operating system/version

Windows 11

### Describe the bug

When trying to delete a file with non ascii characters on its name with the `delete_to_trash = true` option enabled, oil.nvim willl silently fail.

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. `nvim -u repro.lua`
2. `:Oil<cr>`
3. `o` (enter insert mode on a new line)
4. `á<esc>:w<cr>` (create a new file with the name `á`) and `o` (confirm)
5. `dd:w<cr>` (delete the file with the name `á`) and `o` (confirm)

### Expected Behavior

oil.nvim should be able to send the file to the windows trash.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
	      delete_to_trash = true,
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by TheLeoP** [comment]
I suspect that this bug has something to do with the weird encoding windows uses by default on `powershell`. When trying to debug this, I found that on [this line](https://github.com/stevearc/oil.nvim/blob/master/lua/oil/adapters/trash/windows/powershell-trash.lua#L64), $path has no value.

If I run the command from `powershell` directly, this does not happen (i.e. the command works as intented). This leads me to believe that the encoding used by Lua and the one used by powershell is differen (in particular, the input encoding, because the results send by `powershell` when listing trash entries has no problems with non-ascii characters). I tried using the [same trick](https://github.com/stevearc/oil.nvim/blob/master/lua/oil/adapters/trash/windows/powershell-trash.lua#L16) used when listing files from the trash, but it didn't work.

My understanding is that:
1. Lua only sees strings as arrays of bytes, but I don't know if this means using UTF-8 for encoding or the underlying windows representation.
2. [`powershell`](https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell/49481797#49481797) encoding is weird (the answer has in depth information about it). I tried using multiple different combination of values for `[Console]::InputEncoding`, `[Console]::OutputEncoding` and `$OutputEncoding`, but I couldn't solve the bug.

**Comment by stevearc** [comment]
You're correct that the lua strings are just byte arrays. To figure out the encoding, you'll have to look for the source of those strings. In this case, it's the `list` command, for which you're manually specifying an encoding of UTF-8. So I think we can say with some confidence that the strings are going to be UTF-8 encoded.

I'd recommend trying to get a super simple repro script. Something that just runs the `delete_cmd` on a hard-coded file name. Try it with `vim.fn.jobstart`, and maybe also try it with `vim.fn.system`, and also `vim.system` if you're on nightly or `vim.loop.spawn` if you're not. Isolating the invocation should help us narrow down where the problem could be.

**Comment by TheLeoP** [comment]
I think I got it. Current hypothesis: the problem has something to do with `nvim_chan_send`.

With this minimal example (where `C:\Users\pcx\Desktop\á` is a file that already exists):

```lua
if not id then
	id = vim.fn.jobstart({
		"powershell",
		"-NoProfile",
		"-NoLogo",
		"-ExecutionPolicy",
		"Bypass",
		"-Command",
		"-",
	}, {
		on_stdout = function(_, data)
			vim.print(data)
		end,
	})
end
vim.api.nvim_chan_send(
	id,
	[[
$aux = 'C:\Users\pcx\Desktop\á'
$path = get-item $aux
write-host $aux
write-host $path
        ]]
)
```

The output is:

```lua
{ "C:\\Users\\pcx\\Desktop\\á" }
{ "", "" }
{ "", "" }
```

`$path` has no value.

If I instead do not use `nvim_chan_send`:

```lua
vim.fn.jobstart({
	"powershell",
	"-NoProfile",
	"-NoLogo",
	"-ExecutionPolicy",
	"Bypass",
	"-Command",
	[[
$aux = 'C:\Users\pcx\Desktop\á'
$path = get-item $aux
write-host $aux
write-host $path
		]],
}, {
	on_stdout = function(_, data)
		vim.print(data)
	end,
})
```

The output is:

```lua
{ "C:\\Users\\pcx\\Desktop\\<a0>" }
{ "", "" }
{ "C:\\Users\\pcx\\Desktop\\<a0>" ,}
{ "", "" }
{ "" }
```

`$path` **has** a value.

Now, the problem is: is this a bug or am I missunderstanding something about `nvim_chan_send`? `:help channel-bytes` says that:

> Channels opened by Vimscript functions operate with raw bytes by default.

But I that it saws nothing about encoding (?).

**Comment by stevearc** [comment]
Yeah `nvim_chan_send` sends raw bytes so that you can send terminal escape codes and such. The encoding...I mean the encoding is just going to be what the format of the bytes are when read from the source. My default assumption would be utf-8. Could it be that Powershell processes commands passed in as arguments _differently_ than commands passed in via stdin? This is also something you could test. You could try running this command by hand and piping in the commands from a different source (not neovim), or you could try using the `jobstart` + `nvim_chan_send` to run a binary you create to inspect the bytes that are sent to it.

**Comment by TheLeoP** [comment]
Thanks for the ideas :D. This is, indeed, a problem with powershell interpreting differently arguments and commands passed in via stdin.

[This stackoverflow answer](https://stackoverflow.com/a/67578318) explains the problem and a workaround using `cmd` to launch powershell using the UTF-8 codepage. This is a bit convoluted, but it does work. The previous failling minmal reproduction now work with this modification:

```lua
id = vim.fn.jobstart({
	"cmd",
	"/c",
	'"chcp 65001 && powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -Command -"',
}, {
	on_stdout = function(_, data)
		vim.print(data)
	end,
})
vim.api.nvim_chan_send(
	id,
	[[
$aux = 'C:\Users\pcx\Desktop\á'
$path = get-item $aux
write-host $aux
write-host $path
        ]]
)
```

I'll open a small PR fixing this
