### ISSUE TITLE
bug: Changing `float.max_width` and `float.max_height` is ugly

### ISSUE THREAD

**Issue by budimanjojo** [stevearc/oil.nvim#32]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Linux

### Describe the bug

Changing float `max_height` and `max_width` to `>0` broke the float. It's not in the monitor but I probably cant just a while ago.

### Steps To Reproduce

```
require("oil").setup({

  float = {
    -- Padding around the floating window
    padding = 2,
    max_width = 40,
    max_height = 40,
    border = "rounded",
    win_options = {
      winblend = 10,
    },
  },
})
  ```

### Expected Behavior

The float should appear in the middle

### Repro

```Lua
sorry I'm not doing this.
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Not sure exactly what your issue was, but I confirmed that the float was being positioned incorrectly. Was that what you were seeing?

**Comment by budimanjojo** [comment]
> Not sure exactly what your issue was, but I confirmed that the float was being positioned incorrectly. Was that what you were seeing?

Yes, it's being positioned at bottom left of the screen and not centered.

**Comment by stevearc** [comment]
still?

**Comment by budimanjojo** [comment]
Latest commit fixed it! Thank you! I'll close this now.
