### ISSUE TITLE
`cd` doesn't seem to be working

### ISSUE THREAD

**Issue by ZacharyRizer** [stevearc/oil.nvim#320]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2473+g0246f1a89

### Operating system/version

MacOS 14.13.1

### Describe the bug

I might be misunderstanding the use of this functionality, but there isn't too much documentation about it. In the key mapping section of the docs there are these keys: 

```				
["`"] = "actions.cd",
["~"] = "actions.tcd",
```

I figured that `cd` would move me into a directory if I pressed \` over a directory (and do nothing if I was hovering over a file). But `cd` and also `tcd` seem to have no effect. The desired outcome is that I could map CD to move around quickly between directories with `actions.cd` and `actions.parent`. Rather than relying on `actions.select` to move into a directory. Sometimes I accidentally select a file when trying to move quickly through directories. 

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Toggle Oil with `:Oil`
2. move the cursor over a directory
3. press the key mapped to `actions.cd` - `
4. nothing happens

### Expected Behavior

1. Toggle Oil with `:Oil`
2. move the cursor over a directory
3. press the key mapped to `actions.cd` - `
4. Oil navigates into the directory

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This is a misunderstanding of the functionality. The actions do the same thing as `:cd` and `:tcd`, passing in the current oil directory. If you want the functionality you're describing, you could create your own function that leverages `oil.get_cursor_entry` and `oil.select`

**Comment by ZacharyRizer** [comment]
@stevearc thanks for the information and sorry for the clutter.

**Comment by ZacharyRizer** [comment]
In case anyone has a similar question down the line: 

```
local oil = require("oil")

local function custom_open_dir()
	local node = oil.get_cursor_entry()
	if node.type == "directory" then
		oil.select()
	end
end

oil.setup({
	default_file_explorer = true,
	keymaps = {
		["L"] = custom_open_dir,
		....
	},
```
