### ISSUE TITLE
bug: Saving oil buffer works but goes through an error every time

### ISSUE THREAD

**Issue by gisketch** [stevearc/oil.nvim#322]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 

### Describe the bug

https://github.com/stevearc/oil.nvim/assets/78424395/b80b5870-9fb0-445b-82f8-63a37900d5f4

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. open oil
2. delete or rename a file
3. save buffer
4. see error

### Expected Behavior

no error

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
If you look at the stack trace, this appears to be a bug in telescope-file-history.nvim. They appear to be attempting to open or read the buffer in BufWritePost, which will fail because not all buffers are files (see `:help buftype`)
