### ISSUE TITLE
bug: [Windows] drive letters are handled incorrectly (entry selection, buffer name)

### ISSUE THREAD

**Issue by LunarLambda** [stevearc/oil.nvim#326]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2534+g25124d360

### Operating system/version

Windows 10

### Describe the bug

Presume we're starting from `$USERPROFILE`, i.e. `C:\Users\LunarLambda\`.

`:e oil:///` (or `:e .` and press `-` until one hits the drive letter listing)

I get the following:

```
C/
E/
H/
M/
P/
V/
Y/
```

Selecting an entry, say `C`, doesn't open `C:/`, it opens `$PWD/C:/`, so in my case `C:/Users/LunarLambda/C:/`.

Also, oil drops the `:` from the drive prefix, causing `C:/` to display as `C/`, which is bothersome as it breaks vim functions like `fnamemodify` or `expand` (e.g. `matchstr(expand('%:~:.'), 'oil://\w*\zs.*')` gets me `C/Users/LunarLambda` instead of `~`.)

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

See above

### Expected Behavior

Selecting a drive letter from the listing should navigate to it properly.

I assume the reason this happens is because of Windows' drive-relative-working-directory-paths (i.e. `/path` is like `$PWD/path`).

### Directory structure

N/A

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by mbwilding** [comment]
I came here to add basically the same bug notice, well just the parts about the file browsing not switching drives.

**Comment by mbwilding** [comment]
PR with the proposed fix.

https://github.com/stevearc/oil.nvim/pull/341

**Comment by LunarLambda** [comment]
Am unfortunately not near a windows machine to test with at the moment

**Comment by mbwilding** [comment]
No worries, just added a fix to handle mapped drives also.
