### ISSUE TITLE
feature request: fr maybe, i want it to start on startup when i do `nvim <some-dir>` like netrw used to

### ISSUE THREAD

**Issue by daUnknownCoder** [stevearc/oil.nvim#327]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

idk if this already exists, I m using nvim-tree as my daily file browser, but it has a profound impact on my startuptime, i would like to use oil.nvim but dont want to set an `autocmd` for oil so anything to do?

### What is the significance of this feature?

cannot use this plugin without it

### Additional details

open it at `nvim <some dir>` or `nvim .`, nvim-tree in both cases is sluggish

**Comment by lucaseras** [comment]
This is already implemented, see the `default_file_explorer` option in [the README](https://github.com/stevearc/oil.nvim?tab=readme-ov-file#options)

**Comment by stevearc** [comment]
This sounds like a feature request for nvim-tree. By default, oil will try to take over the buffer if you open a directory (such as with `nvim .`). However, as lucaseras mentioned, if you want it to play nice with other file managers you can set `default_file_explorer = false` and it will stop trying to take over those buffers. It sounds like you want the same sort of option for nvim-tree, which may or may not exist I don't know.
