### ISSUE TITLE
feature request: set `modifiable` to true if the user is in the directory group

### ISSUE THREAD

**Issue by DerpDays** [stevearc/oil.nvim#342]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Currently, when checking if a buffer should be modifiable, it only checks if the group is the same group as what neovim is opened with, it would be nice if it would check if the user is in the group regardless if they have opened neovim with the specific group that the folder needs.

### Provide background

I'm trying to edit files belonging to another group, but although I'm in the group needed for the directory I'm trying to open it still sets modifiable as false since I haven't opened neovim with the specific group. To get around this I can just set modifiable to true or run `sg GROUPNAME "nvim ...."` but it's quite tedious to remember to do so.

### What is the significance of this feature?

nice to have

### Additional details

Not quite sure how you'd want this to be implemented, we could read from /etc/group and check if the user is part of the group.
Or more simply, split `vim.fn.system("id -G")` and check if the directory's group id is in the result.

I'd be happy to implement this

**Comment by DerpDays** [comment]
I've done a quick implemented both of the ways I mentioned.

@stevearc, it'd be great if you could have a quick glance over these and tell me which you prefer so I can send a PR, where it can be further polished - or if you have a better idea on how to do this.

https://github.com/DerpDays/oil.nvim/tree/id - Simpler, uses the `id -G` command and iterates through the result, standard on linux and bsd, I don't think it's likely someone wouldn't have it. 
https://github.com/DerpDays/oil.nvim/tree/groupfile - Uses /etc/group to check if the user is in the group for the directory, the file is standard on linux and bsd.

**Comment by stevearc** [comment]
I think the `id -G` approach is fine. I'd make two requests for your current implementation:
1. cache the result. We should only ever have to call it once.
2. gracefully fall back to the previous behavior if anything fails with `id -G` (a vim.notify warning would be appropriate)
