### ISSUE TITLE
[question] save files after rename

### ISSUE THREAD

**Issue by dan-cooke** [stevearc/oil.nvim#343]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.0

### Operating system/version

Arch Linux

### Describe the bug

I'm a little confused how the DX is supposed to work for this plugin,

If i have the following files

a.ts
```.ts
export a = 'hello'
```

b.ts
```.ts
import { a } from './a'
```

Structured like

```
a.ts
b.ts
```

And I use oil to rename
```
a.ts -> c.ts
```

Now my `b.ts` contents are like this
```
import { a } from './c'
```

but my git status will only show `a` being renamed

It will not show b.ts being modified to use the new path

So this means...
1. This buffer is not automatically saved
2. b.ts will not even be loaded into a buffer automatically, so I would have to manually find all the files I think have been affected, open them and then run `:update`

This is quite possibly a configuration issue on my part, but just wondering if this the intended experience?

Thanks for the great plugin!

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

irrelevant

### Expected Behavior

irrelevant

### Repro

```Lua
irrelevant
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
The changed buffers should be _open_, which you can confirm with `:ls!`. If you want to save them, you can do a `:wa` to write all buffers. Alternatively, if you want to automatically save them you can set the config option `lsp_file_methods.autosave_changes`

https://github.com/stevearc/oil.nvim/blob/c86e48407b8a45f9aa8acb2b4512b384ea1eec84/lua/oil/config.lua#L43-L45
