### ISSUE TITLE
bug: gitsigns is broken when I open a file first time in splitting window in oil.nvim

### ISSUE THREAD

**Issue by twandylue** [stevearc/oil.nvim#36]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.2

### Operating system/version

MacOS 12.4

### Describe the bug

I found that if I open the file for the first time, which means this file does not be opened by any buffer before, in the splitting window in`oil.nvim`, [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) could not show the difference normally.  I am not sure whether should I report this issue to `gitsigns.nvim` or `oil.nvim`.

By the way, I use neovim in iterm2(v3.4.19)

Thanks a lot !!!

I made a video to clearly describe this issues.

https://user-images.githubusercontent.com/70478084/212789229-94a11963-e52f-4e0a-bdb8-bf1f5286fb6b.mp4

### Steps To Reproduce

1. git init
2. git add .
3. nvim -u repro.lua
4. :Oil
5. <C-s> to open a file in the splitting window
6. enter new lines or characters

### Expected Behavior

[gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) should show the difference in the file in splitting window.

For example,
<img width="586" alt="Screen Shot 2023-01-17 at 09 08 21" src="https://user-images.githubusercontent.com/70478084/212788052-4f12f5fe-ab5c-4f88-b5fa-178bb4d6367d.png">

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/oil.nvim",
    config = function()
      require("oil").setup({
        -- add any needed settings here
      })
    end,
  },
  {
    "lewis6991/gitsigns.nvim",
    config = function()
      require("gitsigns").setup({
        -- add any needed settings here
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Thanks for the thorough repro! Made it easy to figure out what's going on.

Oil sets some window options when it opens, and one of those is `signcolumn=no`. We were restoring the previous window options when you left the oil buffer, but if you split the window it would clone the window options, but not the restore behavior. So the split window was getting stuck as `signcolumn=no` when you edited a file, and that was causing the gitsigns to not show up. Should be fixed now!
