### ISSUE TITLE
feature request: the abilty to move a directory to a unrelevant directory

### ISSUE THREAD

**Issue by sekerhalithamza** [stevearc/oil.nvim#364]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to be able to move a directory or a file to another directory when their only relativity is maybe their grandparent or parent.

### Provide background

Lets say we have

- grandparent
  - parent1
    - child1
    - child2
  - parent2
    - child3
    - child4
  
I would like to be able to move parent1 under parent2, child1 to parent2 etc. But when I try it rn with deleting and then pasting it gives an error like "did id changed"   

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
Could you provide a more detailed set of repro steps? I don't know what the error is that you're seeing, and I don't know how you're deleting, pasting, or navigating around these buffers.

**Comment by sekerhalithamza** [comment]
First of all, I am not a native speeker so my english is not perfect so sorry for that. When you press dd it deletes it and then gets the data to the register.  Then you can paste it into another buffer. If we can move files/folders around like this it would be awesome. If further explaning is needed. I can record a video.

**Comment by stevearc** [comment]
I would love to see a video of the problem. Oil should already be able to move files and directories by deleting them and pasting them into another buffer. If this is not working, then it is a bug. Based on your description, I don't know what could be going wrong.

**Comment by sekerhalithamza** [comment]
here is an example. I hope this shows the problem clearly

https://github.com/stevearc/oil.nvim/assets/104067464/74350bbe-4844-44b4-b2e8-a439dddc9f29

**Comment by sekerhalithamza** [comment]
If more error logs or other factors is needed. I can provide those

**Comment by sekerhalithamza** [comment]
I just figured out that if you delete it correctly it does not throw an error. Thanks though!
