### ISSUE TITLE
bug: lpeg pattern fails to match

### ISSUE THREAD

**Issue by stellarhoof** [stevearc/oil.nvim#367]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.10.0-dev-e948d7f

### Operating system/version

MacOS Sonoma 14.4.1

### Describe the bug

`glob_pattern` in [this line](https://github.com/stevearc/oil.nvim/blob/bcfc0a2e01def5019aa14fac2fc6de20dedb6d3d/lua/oil/lsp/workspace.lua#L80) fails to match a filename when renaming, causing lsp client to not notify the server of `workspace/didRenameFiles`.

The glob string is `**/*.{ts,cts,mts,tsx,js,cjs,mjs,jsx}` and the filename is 'packages/ui/src/rats/Button.tsx'

`:lua =vim.glob.to_lpeg('**/*.{ts,cts,mts,tsx,js,cjs,mjs,jsx}'):match('packages/ui/src/rats/Button.tsx')` also fails to match

If I remove `glob_pattern` in the linked code and instead use `glob` it works as intended.

Probably an issue with neovim itself?

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. nvim -u repro.lua
2. Execute `:lua =vim.glob.to_lpeg('**/*.{ts,cts,mts,tsx,js,cjs,mjs,jsx}'):match('packages/ui/src/rats/Button.tsx')`

### Expected Behavior

File renaming triggers `workspace/didRenameFiles`

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Yes, this is an issue upstream. There's not much I can do here, short of creating a new glob matching implementation. I'd recommend filing an issue upstream with the minimal `vim.glob.to_lpeg` repro. It would probably also be helpful if you can narrow down the repro a bit to determine which part of the pattern or path is causing problems.
