### ISSUE TITLE
feature request: Jump current file

### ISSUE THREAD

**Issue by thevan96** [stevearc/oil.nvim#37]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

How to jump to the current file open in oil buffer but cursor under the name file? Default now the cursor is on top

### Provide background

I don't want to open the current folder of the current file and then must search the name file current again

**Comment by stevearc** [comment]
There's already some logic in place to do what you're asking, but I did find an edge case where it didn't trigger. I fixed that edge case, but I'm not sure if that's the situation you discovered. Could you try it again, and if you still see the issue could give very specific steps to reproduce what you're seeing?

**Comment by thevan96** [comment]
If you used nerdtree, this feature is like NerdTreeFind,I write wrap function but not cursor not under the name file.
```
function! JumpFile()
  let file_name = expand('%:p:t')
  Oil %:p:h
  call search(file_name)
endfunction
command! JumpFile call JumpFile()
Plug 'stevearc/oil.nvim'
nnoremap <leader>ff :JumpFile<cr>
nnoremap <leader>fv :vsp+JumpFile<cr>
nnoremap <leader>fs :sp+JumpFile<cr>
```

**Comment by stevearc** [comment]
So the reason that `search()` doesn't work is that Oil is async and so the buffer contents actually get rendered a millisecond or two after opening the buffer. If you want to open the parent directory, you should just run `:Oil` with no arguments. That will open the dir and jump the cursor to the location of the file you were just in. When you run `:Oil <path>` it disables any jumping logic.
