### ISSUE TITLE
bug: oil-ssh doesn't work if there is no "extra_scp_args" in config

### ISSUE THREAD

**Issue by inferst** [stevearc/oil.nvim#370]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 10 WSL2 Ubuntu

### Describe the bug

When opening a file via oil-ssh there will be error in command line and file won't be open

![Screenshot 2024-05-10 020950](https://github.com/stevearc/oil.nvim/assets/6252160/e5c50e8f-47f0-4e35-9785-b1d6d4e5b12a)

It works if I add this in config

extra_scp_args = { '-O' }

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. nvim oil-ssh://user@server/some_file
2. file won't be open (error)

### Expected Behavior

oil-ssh can open a file

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by tejomaygadgil** [comment]
Tysm!! I am finding the same exact issue (and work-around) on a MacOS Sonoma M1 Mac.

**Comment by stevearc** [comment]
Thanks for the report!
