### ISSUE TITLE
feature request: allow loading entries into command line mode

### ISSUE THREAD

**Issue by rgrinberg** [stevearc/oil.nvim#38]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

In dirvish, one can use the `.` key to load the entry under the cursor (or multiple entries in a selection) into the command mode. For example, if we consider the cursor to be `|`

```
...
foo.lua|
...
```

Hitting `.` will open command mode with the cursor on `|`:

```
:| foo.lua
```

### Provide background

This is quite useful for running shell commands on individual files. For example, to `stat` the current file one would:

* Press `.` on the desired file on the cursor
* Type in `! stat` and hit `<CR>`

**Comment by stevearc** [comment]
I've added an action that will do this. It's not mapped by default, so you'll have to add it yourself:
```lua
require("oil").setup({
  keymaps = {
    ["."] = "actions.open_cmdline",
  }
})
```

**Comment by rgrinberg** [comment]
Awesome. Thank you!

**Comment by ahrm** [comment]
It would be nice if we could add multiple files simultaneously by selecting them in visual mode and then pressing `.`.
