### ISSUE TITLE
feature request: Add a Oil Toggle command

### ISSUE THREAD

**Issue by RiteshChepuri** [stevearc/oil.nvim#384]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be nice to have oil toggle so that we could return to last or previous buffer.

### Provide background

Previously when I open a file tree or file explorer like nvim-tree it used have a toggle command so that we could return back to the previous buffer. I made a command to close the netrw plugin when I switched to it. So it would be nice If we have OilToggle command to close the oil buffer. 

### What is the significance of this feature?

strongly desired

**Comment by RiteshChepuri** [comment]
Yeah I think it might work. but rather than returning to previous buffer, we can delete the buffer so that it wont appear on buffers list. Thank you.

**Comment by halshar** [comment]
```lua
vim.keymap.set('n', '<Tab>', function()
   vim.cmd((vim.bo.filetype == 'oil') and 'bd' or 'Oil')
end)
```

this works like charm, thank you :)
