### ISSUE TITLE
bug:  can't open anything using <CR> or <C-t>

### ISSUE THREAD

**Issue by directormac** [stevearc/oil.nvim#385]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch

### Describe the bug

as indicated in the title.
I am using LazyVim as my base here is how i configured my [oil](https://github.com/directormac/dotfiles/blob/e99b9afa8f668bc9a4648631c34417f949e54fcb/.config/nvim/lua/plugins/tools.lua#L88)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

Copy Configuration and use LazyVim

![image](https://github.com/stevearc/oil.nvim/assets/5866196/f7ce09ab-e134-49e7-ab6a-b80666da8e1d)

### Expected Behavior

Should open the file under cursor

### Repro

```Lua
Current [Configuration](https://github.com/directormac/dotfiles/blob/e99b9afa8f668bc9a4648631c34417f949e54fcb/.config/nvim/lua/plugins/tools.lua#L88)
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by snuffop** [comment]
:+1:

**Comment by directormac** [comment]
> 👍

You having this errors too @snuffop ?

**Comment by directormac** [comment]
> I have the very same issue. I downgraded through the last 2 oil.nvim tags in my lazy config, but this did not change the behaviour. The only other thing i can remember i did was upgrading to `0.10.0` nvim (arm-based macos):
> 
> ```
> vim -v
> NVIM v0.10.0
> Build type: Release
> LuaJIT 2.1.1713773202
> Run "nvim -V1 -v" for more info
> ```
> 
> Highly likely it is a `v0.10.0` issue, i ~think~ thought, but OP is on `0.9.5` apparently, which contradicts this. @directormac you are sure you're on `0.9.5`?

Yup im pretty sure im on 0.9.5, but i just downgraded because 

```txt
❯ nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

even downgrading luajit i still get the same thing from oil i maybe thought its one of the deps.

**Comment by buztard** [comment]
I just had the same issue. In my case it happened because of a wrong filetype detection in a [different plugin](https://github.com/towolf/vim-helm/commit/69a51170f9e0f7c21242c85e2feac6aa17adeb22). You can check the filetype of your oil buffer using `set ft?` and switch to `ft=oil` in case it's different

**Comment by directormac** [comment]
Yup looks like it i have vim-helm too now its all good again. Closing this issue now.
