### ISSUE TITLE
bug: Title is being displayed as Highlight

### ISSUE THREAD

**Issue by alwaysamer** [stevearc/oil.nvim#387]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.0 

### Operating system/version

MacOS 14.4.1

### Describe the bug

Since setting up WezTerm, the title in my floating Oil window is being displayed with some sort of highlighting.

See here:

![image](https://github.com/stevearc/oil.nvim/assets/22222279/4c62bae3-4cc3-417f-acd9-783c3f494e62)

It may be due to my new WezTerm configuration, but I can't figure out what is missing because I am not very good at Lua, so I can't really check the code to see how the text is being displayed.

This is not really a bug but more of a question. How is that specific text being displayed so I can understand the issue and fix my config?

Thanks and sorry if this is the wrong place for this kind of questions. Been trying to fix this for a long time myself.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Use WezTerm
2. Start Oil in Neovim

### Expected Behavior

I would expect the Text to be shown without that weird square in the Background.

### Repro

```Lua
not really sure if this is neccessary.
```

### Did you check the bug with a clean config?

- [x] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by esn89** [comment]
@alwaysamer what's the fix for this?

**Comment by ixion396** [comment]
How did you fix this?

**Comment by stevearc** [comment]
This is set by `:help hl-FloatTitle`. Change that highlight group in your colorscheme to adjust the visuals.
