### ISSUE TITLE
Oil Buffer Unmodifiable After a File Operation

### ISSUE THREAD

**Issue by UnrealApex** [stevearc/oil.nvim#4]
After modifying a file and returning to the Oil buffer, it is not modifiable.

**Comment by stevearc** [comment]
It took me a while to figure out how you triggered this. I'll add an issue template, but in the future I'd highly recommend providing exact steps for how to replicate the issue. It helps enormously when trying to reproduce it.

I was able to hit this by
1. Open an oil buffer `nvim .`
2. Make any edits (e.g. create a file)
3. `:w`
4. When the preview window is displayed, cancel it
Expected: I should be able to make more changes to the oil buffer
Actual: the oil buffer is not modifiable

If that was what was causing the problem for you, it should be fixed! If you were encountering it some other way, please provide detailed steps to reproduce it.

**Comment by UnrealApex** [comment]
Indeed your commit fixed the issue. My apologies, I will do so next time.
