### ISSUE TITLE
bug: Cannot open oil 

### ISSUE THREAD

**Issue by t18n** [stevearc/oil.nvim#409]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

After updating to the latest stable Nvim version and the latest Oil, the plugin does not display the **root** directory anymore.

Error shown:
```
   Error  10:54:48 notify.error lazy.nvim Failed to run `config` for oil.nvim

...s/turbo/.local/share/nvim/lazy/oil.nvim/lua/oil/util.lua:159: E565: Not allowed to change text or change window

# stacktrace:
  - /oil.nvim/lua/oil/util.lua:159 _in_ **rename_buffer**
  - /oil.nvim/lua/oil/init.lua:746 _in_ **maybe_hijack_directory_buffer**
  - /oil.nvim/lua/oil/init.lua:1265 _in_ **setup**
```

https://github.com/stevearc/oil.nvim/assets/14198542/36fc4cf6-6ece-4f9c-a2af-030b99feb2ff

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

Unfortunately I cannot reproduce this with the repro. So creating the issue with the hope to get some inputs.

### Expected Behavior

Oil should not show any error and work with root directory

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    'stevearc/oil.nvim',
    opts = {},
    -- Optional dependencies
    dependencies = { "nvim-tree/nvim-web-devicons" },
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by t18n** [comment]
I found a workaround for now: after opening Nvim, I use Telescope to open a random file before open Oil, it will then work as normal. Hopefully this can be fixed :)

**Comment by stevearc** [comment]
Since you can't reproduce the issue with a clean config, it's most likely interference with some other plugin. The message
> E565: Not allowed to change text or change window

seems to be related to autocomplete. So maybe you're loading oil in the middle of a completion function somehow.

The last resort to figure out the conflict is always to `:help bisect`

**Comment by jellydn** [comment]
FYI - I've got the same issue and use `lazy.nvim` to pin to the commit `18272aba9d00a3176a5443d50dbb4464acc167bd`

```lua
  {
    "stevearc/oil.nvim",
    commit = "18272aba9d00a3176a5443d50dbb4464acc167bd",
    opts = { }
  }
```

**Comment by jellydn** [comment]
FYI - It's working for me with last commit now.

**Comment by NicolasGB** [comment]
Same, it's working again.
I've also noted that the "actions.save" which i had mapped is gone now, i replaced it with `vim.cmd.w`

**Comment by stevearc** [comment]
@t18n does the most recent commit work for you as well?

**Comment by t18n** [comment]
@jellydn unfortunately `    commit = "18272aba9d00a3176a5443d50dbb4464acc167bd",` did not work for me.

@stevearc I updated to
```
  "oil.nvim": { "branch": "master", "commit": "64a3a555b40d96faae488ed6cf5d0f8b38520891" },
```
but the issue persisted.

**Comment by stevearc** [comment]
@t18n the only clue I have is that it might be related to autocomplete somehow. It's definitely a bad interaction with something else in your config, but without being able to reproduce it on my end I can't look into it. As mentioned before, you could try `:help bisect`. Another place to look could be using `:Lazy` to see what triggered the loading of `oil.nvim`, because it looks like the error is happening in the setup function, so it's possible that oil is getting loaded in a weird or unexpected context.

**Comment by Divelix** [comment]
I disabled lazy load for oil and now it works fine.

**Comment by t18n** [comment]
@Divelix that's it. Set `lazy = false` fixed it for me. Thank you!

**Comment by iton0** [comment]
I got this working so that oil is lazy loadable:
```lua
	"stevearc/oil.nvim",
	keys = {
		{ "-", "<cmd>Oil<cr>" },
		{ "<leader>-", "<cmd>Oil --float<cr>" },
	},
	opts = {
		default_file_explorer = false,

```
It seems something to do with the `default_file_explorer` option and setting it to false. Didn't know if this would help but wanted to show just in case.
NOTE: i disabled netrw in my lazy.nvim config
