### ISSUE TITLE
feature request: shortcut to scroll preview window

### ISSUE THREAD

**Issue by yingzhu146** [stevearc/oil.nvim#41]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

First off: Thanks a ton for the plugin, this is fantastic, fantastic work.

In telescope, I can scroll the preview of the currently selected item via `<c-u>` `<c-d>` - would be awesome to have something similar here to allow `oil.nvim`

Thanks a ton!

### Provide background

I'm trying to improve the speed at which I can explore a repo quickly - a key part of that is being able to browse previews quickly to get a rough overview of the code in each module

**Comment by stevearc** [comment]
I've added two new actions you can use for this purpose: `actions.preview_scroll_down` and `actions.preview_scroll_up`. You can view all available actions at `:help oil-actions` now.

**Comment by yingzhu146** [comment]
You're amazing, thanks so much for all your work on this!
