### ISSUE TITLE
bug: jumplist doesn't work properly when using oil to switch files

### ISSUE THREAD

**Issue by murtaza64** [stevearc/oil.nvim#415]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Macos 14.5

### Describe the bug

If you use Oil to switch to another file, then hit C-o to jump back to the last file, it doesn't take you to the file you were on when you opened oil, but to the file before that

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. echo hello | tee a.txt | tee b.txt > c.txt
2. nvim -u repro.lua
3. :e a.txt
4. :e b.txt
5. navigate to c.txt with Oil
6. Wait ~2 sec for the oil buffer to be cleaned up
7. C-o
8. you will be taken to a.txt

### Expected Behavior

You should be taken to b.txt.

The jumplist looks similar in these two situations:
Situation 1:
`:clearjumps`
`:e a.txt`
`:e b.txt`
`:e c.txt`
<img width="269" alt="image" src="https://github.com/stevearc/oil.nvim/assets/13615693/67a10264-c534-464a-b4da-172fc1ce5a6b">

Situation 2:
`:clearjumps`
`:e a.txt`
`:e b.txt`
`:Oil` to c.txt
<img width="261" alt="image" src="https://github.com/stevearc/oil.nvim/assets/13615693/877bd6b9-65c5-45f6-9e16-f2ce9ac4ce0f">

Yet jumping with C-o in situation 2 doesn't take you to `b.txt`. Is it because there's no jump with index 1?

Not too sure of the details of how the jumplist actually works, so maybe I'm missing something, but this has been very mildly annoying for the past few weeks 😅 

### Directory structure

a.txt
b.txt
c.txt
repro.lua

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
The repro steps you provided are minimal and detailed, but when I do the exact same thing I see the correct behavior (`<C-o>` jumps back to b.txt, then a.txt). I'm on Neovim v0.10.0, could you try updating to that version to see if that could be the difference?

**Comment by murtaza64** [comment]
Huh, I updated 0.10 after posting this bug, and lo and behold, the repro steps I outlined now produce the expected behavior. Guess we can close this
