### ISSUE TITLE
incomplete documentation: how to change border sytle

### ISSUE THREAD

**Issue by bs10x** [stevearc/oil.nvim#417]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

I can't figure out how to change the border style. Is there another option other that "rounded"?

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

`<cmd> Oil --float . <CR>`

### Expected Behavior

Mention somewhere if there are other window border options.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
See `:help nvim_open_win`. This will give you an idea what the options are for the `border` parameter, and a better understanding of how floating windows are configured in general

**Comment by davisssamuel** [comment]
None of the border options found in `:h nvim_open_win` change the appearance of windows in oil buffers.

my oil.lua file:

```lua
return {
  "stevearc/oil.nvim",
  lazy = false,
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("oil").setup({
      delete_to_trash = true,
      view_options = { show_hidden = true },

      -- window appearance
      float = { border = "single" },
      confirmation = { border = "single" },
      progress = { border = "single" },
    })
}
```
