### ISSUE TITLE
feature request: have a option to use default command line to for confirmation

### ISSUE THREAD

**Issue by chphungphat** [stevearc/oil.nvim#420]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

The popup doesn't interact quite well with some plugin like indent-line or hlchunk. It seem the popup is actually a regular buffer and these indent plugins add indent line to them

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Displaying the changes in the command line will not be a good user experience. If you have other plugins that are messing up the UI, I recommend configuring those plugins to not interfere. You can try disabling them for the filetype `oil_preview`.
