### ISSUE TITLE
not an issue: I want to show appreciation

### ISSUE THREAD

**Issue by Axlefublr** [stevearc/oil.nvim#421]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I want to donate to this project…

### Provide background

…because it's easily my favorite plugin (2nd after a plugin I made, so that doesn't count), and has turned into a system-wide file manager for me. I want to give back for this amazing piece of software :)

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
I appreciate the sentiment! I do have a policy for myself to not accept donations for my open source work, to help me set boundaries (see #195). If you are really moved in a monetary way, I'd recommend donating to Neovim itself since we all benefit from that!
