### ISSUE TITLE
feature request: Copy file name and path to clipboard

### ISSUE THREAD

**Issue by shashankshetty1996** [stevearc/oil.nvim#423]
### Did you check existing requests?

- [X] I have searched the existing issues

### Overview:
Similar to the functionality available in popular IDEs like VSCode, implementing the option to copy file paths directly from the file explorer can greatly enhance user experience and productivity. This feature aims to provide users with the convenience of effortlessly copying the filename, absolute path, and relative path of a file for various use cases.

### Detailed Functionality:
- **Copying File Name:**
  - Users can easily copy the file name for quick referencing when creating or renaming files in different directories.
  
- **Copying Absolute Path:**
  - Enables users to copy the absolute path of a file, facilitating efficient navigation from the local terminal to the specific file location.
  
- **Copying Relative Path:**
  - Simplifies sharing file references with collaborators by copying the relative path, aiding in seamless communication and collaboration.
  
- **Navigating in Version Control Repositories:**
  - Copying the relative path allows users to swiftly locate files within version control repositories such as GitHub, Bitbucket, enhancing visibility and ease of access.

### Benefits:
- Streamlines file path handling for various tasks within the project workflow.
- Reduces manual effort and potential errors associated with typing out or searching for file paths.
- Improves collaboration by providing clear and easily accessible file references to team members.

### Implementation Details:
- Finalise having keymaps and update same in helper screen keybindings.
- Provide options to copy the file name, absolute path, and relative path based on predefined key bindings.
- Ensure seamless integration with existing features and workflows for a cohesive user experience.

### Provide background

- **I am trying to reference specific files in my codebase.**
  - *Current workflow:* Manually typing or searching for file paths to include in documentation, configuration files, or code comments.
  
- **I need to quickly access and insert file paths into various parts of my project.**
  - *Current workflow:* Time-consuming process of locating and copying file paths from the file explorer or terminal.
  
- **I want to streamline the process of handling file paths for improved efficiency.**
  - *Current workflow:* Lack of a direct feature to copy filenames, absolute paths, or relative paths with ease.

- **I want to copy the file name and paste it in another directory when creating a new file.**
  - *Current workflow:* Manually typing or renaming files, which can be error-prone and time-consuming.
  
- **I want to copy the absolute path to navigate efficiently from my local terminal to the file location.**
  - *Current workflow:* Having to type out or navigate through directories to reach the desired file.
  
- **I want to copy the relative path to easily share file references with my colleagues for collaboration.**
  - *Current workflow:* Providing complex or incorrect paths that may lead to confusion or errors.
  
- **I want to copy the relative path to quickly locate the file within version control repositories like GitHub, Bitbucket, etc.**
  - *Current workflow:* Manually searching for the file in the repository, which can be time-consuming and cumbersome.

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
There is some documentation at `:help oil-actions` about the built-in actions you can easily use as keymaps. Take a look at `:help actions.yank_entry`

**Comment by shashankshetty1996** [comment]
Under `:help oil-actions` I found `copy_entry_filename` and `copy_entry_path` actions. Thanks for the update @stevearc

**Comment by shashankshetty1996** [comment]
Under `:help oil-actions` I found `copy_entry_filename` and `copy_entry_path` actions. Thanks for the update @stevearc
