### ISSUE TITLE
feature request: Status icons (git, lsp, file modifications)

### ISSUE THREAD

**Issue by Rumi152** [stevearc/oil.nvim#426]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Is it possible to add column for statuc icons? For example [+] for modified files, some other icons for git and maybe errors or diagnostics from lsp

### Provide background

I really like the plugin but without these icons it can't replace my file tree plugin i've been using (NeoTree). Quickly looking for changes or errors is a lot harder

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
There is an existing third-party plugin for git status https://github.com/refractalize/oil-git-status.nvim

**Comment by Rumi152** [comment]
Wow. Thank you very much. It is exactly what i was looking for.
