### ISSUE TITLE
bug: Regression for alt buffers

### ISSUE THREAD

**Issue by scheatkode** [stevearc/oil.nvim#43]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

Linux 6.1.6-arch1-3

### Describe the bug

Alternate buffer handling was working prior to commit ca4da68aaebaebf5cd68151c2b5ad56e00c06126.

I tried tracking the issue in a debugging session since this is most likely scoped in [`init.lua`](https://github.com/stevearc/oil.nvim/blob/ca4da68aaebaebf5cd68151c2b5ad56e00c06126/lua/oil/init.lua). Apart from the refactor, nothing major seems to have changed; hitting breakpoints in `restore_alt_buf` as well as the various autocmds suggest that the issue lies elsewhere.

Apologies for not being able to pinpoint the cause and provide a fix.

### Steps To Reproduce

1. nvim -u repro.lua
2. Open a file
3. Open another file with oil
4. `<C-^>`

Results in `E23: No alternate file`

### Expected Behavior

Alternate buffer should be set correctly.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Dangit, I added a bunch of tests for the alternate buffer so this wouldn't happen! Apologies for the thrash; it should be fixed now.

**Comment by scheatkode** [comment]
No worries, thank you for the quick response and the amazing plugin ! :smile:
