### ISSUE TITLE
bug: icons not appearing in windows terminal

### ISSUE THREAD

**Issue by Parad0x84** [stevearc/oil.nvim#447]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Win11

### Describe the bug

Icons looks weird (mini.icons)

![image](https://github.com/user-attachments/assets/3a014d13-359a-4326-85ce-8c0783a04ae0)

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

I have following lua file included by Lazy
[oil-nvim.txt](https://github.com/user-attachments/files/16200660/oil-nvim.txt)

### Expected Behavior

I expect to see real icons. Currently it looks like icons have very low width

### Directory structure

Anything

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
                dependencies = { 'echasnovski/mini.icons' },
                -- dependencies = { 'nvim-tree/nvim-web-devicons' },
                opts = {
                  default_file_explorer = true,
                  delete_to_trash = true,
                  watch_for_changes = true,  -- Set to true to watch the filesystem for changes and reload oil
                  
                  columns = {
                    "icon",
                    -- "permissions",
                    -- "size",
                    -- "mtime",
                  },
            
                  keymaps = {
                    ["<CR>"] = "actions.select",
                    ["<C-t>"] = { "actions.select", opts = { tab = true }, desc = "Open the entry in new tab" },
                    ["<C-p>"] = "actions.preview",
                    ["<C-c>"] = "actions.close",
                    ["<C-l>"] = "actions.refresh",
                    ["-"] = "actions.parent",
                    ["_"] = "actions.open_cwd",
                    ["`"] = "actions.cd",
                    ["~"] = { "actions.cd", opts = { scope = "tab" }, desc = ":tcd to the current oil directory" },
                    ["gs"] = "actions.change_sort",
                    ["gx"] = "actions.open_external",
                    ["g."] = "actions.toggle_hidden",
                    
                    --["<C-h>"] = { "actions.select", opts = { horizontal = true }, desc = "Open the entry in a horizontal split" },
                    --["<C-s>"] = { "actions.select", opts = { vertical = true }, desc = "Open the entry in a vertical split" },
                    --["g?"] = "actions.show_help",
                    --["g\\"] = "actions.toggle_trash",
                  },
                  -- Set to false to disable all of the above keymaps
                  use_default_keymaps = true,
                },
            })
        end,
  },
  {
    'echasnovski/mini.nvim',
    config = function()
      -- Better Around/Inside textobjects
      --
      -- Examples:
      --  - va)  - [V]isually select [A]round [)]paren
      --  - yinq - [Y]ank [I]nside [N]ext [']quote
      --  - ci'  - [C]hange [I]nside [']quote
      require('mini.ai').setup { n_lines = 500 }

      -- Add/delete/replace surroundings (brackets, quotes, etc.)
      --
      -- - saiw) - [S]urround [A]dd [I]nner [W]ord [)]Paren
      -- - sd'   - [S]urround [D]elete [']quotes
      -- - sr)'  - [S]urround [R]eplace [)] [']
      require('mini.surround').setup()
      require('mini.icons').setup()

      -- Simple and easy statusline.
      --  You could remove this setup call if you don't like it,
      --  and try some other statusline plugin
      local statusline = require 'mini.statusline'
      -- set use_icons to true if you have a Nerd Font
      statusline.setup { use_icons = vim.g.have_nerd_font }

      -- You can configure sections in the statusline by overriding their
      -- default behavior. For example, here we set the section for
      -- cursor location to LINE:COLUMN
      ---@diagnostic disable-next-line: duplicate-set-field
      statusline.section_location = function()
        return '%2l:%-2v'
      end

      -- ... and there is more!
      --  Check out: https://github.com/echasnovski/mini.nvim
    end,
  }
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by keyclicker** [comment]
Sorry to ask, but do you have any of the Nerd Fonts installed?

**Comment by Parad0x84** [comment]
@keyclicker Well I have some installed on system, but nowhere in neovim config I specified any. So it shouldn't effect things, right?
Or is it a requirement? I didn't see it in the readme

**Comment by keyclicker** [comment]
You should install one of this fonts as your terminal emulator font.
(I guess it's Windows Terminal in your case.)

**Comment by Parad0x84** [comment]
I installed this one, but still same result
![image](https://github.com/user-attachments/assets/a9fd68a1-45c2-47b8-a7d9-0fe42988d8c1)

**Comment by stevearc** [comment]
As previously commented, this looks like you haven't set up your terminal to use a patched font. I can't speak to how you would do this on Windows, but here's how you can verify if it's working: copy the glyph below and paste it into your terminal (in the prompt is fine, doesn't have to be in neovim). If you see a circle with a check, your font is working. If not, your font is not set up properly.

```

```
It should look like this:
<img width="27" alt="Screenshot 2024-07-15 at 11 53 04 PM" src="https://github.com/user-attachments/assets/ddffbf37-2ecb-4353-b8f5-a3e5a3f98832">

**Comment by Parad0x84** [comment]
Well, it looks fine 
![image](https://github.com/user-attachments/assets/decc3e2b-e88a-4b04-9afa-d042d6b1ac6e)

**Comment by stevearc** [comment]
Iiiinteresting. In neovim, what do you see if you run this command
```
:=require("mini.icons").get("file", "test.lua")
```

**Comment by Parad0x84** [comment]
Here:
![image](https://github.com/user-attachments/assets/daaba9da-059f-4090-95be-d7ca5a2a2105)
![image](https://github.com/user-attachments/assets/3d0c0f7a-50b2-4baf-97df-60710bab7da6)

**Comment by stevearc** [comment]
Well, that is strange that it appears to work in your terminal but doesn't work in Neovim. I don't have any other debugging ideas, but at this point it is also very clearly nothing to do with oil.nvim. You could try posting an issue on mini.nvim about the problem, including the debugging steps you've already taken with pasting the icon in the terminal and the output of `:=require("mini.icons").get("file", "test.lua")`

**Comment by Parad0x84** [comment]
It turns out that specific font has something to do with the issue (MesloLGS NF)
After installing another one (FiraCodeNerdFont), issue seems to be resolved.
Thanks for your help :)

![image](https://github.com/user-attachments/assets/d231e337-6a72-4ec8-82ef-5680ec9f4088)
![image](https://github.com/user-attachments/assets/c9a63527-537c-4495-9ff2-5c2068009e69)

**Comment by Clev7** [comment]
It seems for some reason that some nerd fonts work on windows terminal while others don't
