### ISSUE TITLE
feature request: Some sort of event when Oil is ready

### ISSUE THREAD

**Issue by giodamelio** [stevearc/oil.nvim#458]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I am trying to trigger Oil when I open Neovim with no file/directory specified.

I tried a simple `VimEnter` autocmd, but for some reason I have to wrap the call in a `vim.defer_fn` to make it work. I am a Neovim lua noob though, so I might be missing something simple.

```lua
-- Open Oil if no file/directory is specified
vim.api.nvim_create_autocmd('VimEnter', {
  callback = function()
    if vim.fn.argc() == 0 then
      vim.defer_fn(function()
        require('oil').open()
      end, 10)
    end
  end,
})
```

### What is the significance of this feature?

nice to have

**Comment by TheLeoP** [comment]
Oil will be ready right after calling `require'oil'.setup()` (when you are calling it depends on your config). So, doing the following should do what you expect

```lua
    require("oil").setup(opts)
    if vim.fn.argc(-1) == 0 then require("oil").open() end
```

**Comment by giodamelio** [comment]
Hmm interesting, that still doesn't work for me in the VimEnter. Thanks for confirming that Oil is ready right away after the `setup` call. It is probably something on my side.

The non working config for future reference:

```
-- Oil
oil_setup_options = {
  columns = { 'icon', 'permissions', 'size' },
}
require('oil').setup(oil_setup_options)

-- Open Oil if no file/directory is specified
vim.api.nvim_create_autocmd('VimEnter', {
  callback = function()
    require('oil').setup(oil_setup_options)
    if vim.fn.argc(-1) == 0 then require('oil').open() end
  end,
})
```
