### ISSUE TITLE
bug: Hiding dotfiles also hides the parent directory.

### ISSUE THREAD

**Issue by OmegaHog** [stevearc/oil.nvim#464]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows 11

### Describe the bug

As specified on in the documentation, the script that defines dotfiles only checks for name starting with a single dot, thus also hiding the parent directory along with other dotfiles when triggered. This may cause unexpected behavior. 

**May be fixed by also checking for not ".."**

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Open oil buffer.
2. Go into a nested directory
3. Press g.

### Expected Behavior

Parent directory should not be hidden

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
`..` is a hidden folder, is it not? If you don't want it to be hidden, adjust the `is_hidden_file` function.
