### ISSUE TITLE
How do I unbind s ?

### ISSUE THREAD

**Issue by avario-cpu** [stevearc/oil.nvim#465]
I use [Leap](https://github.com/ggandor/leap.nvim) to move around buffers which uses s as  a main keybind. In oil, s brings up some indexing thing which I don't need. 

I don't find the s keybind mentionned anywhere in oil's doc....

**Comment by stevearc** [comment]
Oil does not bind `s`. You can find the list of keymaps that Oil sets by default here:
https://github.com/stevearc/oil.nvim/blob/a632c898fbe0e363ef89b9577f1a7714ab67d682/lua/oil/config.lua#L60-L77

If you want to find where that is set, try `:verbose nmap s`. You may need to start Neovim as `nvim -V1` to find the exact line.
