### ISSUE TITLE
bug: can't edit files in <any>/etc/nginx

### ISSUE THREAD

**Issue by hlidotbe** [stevearc/oil.nvim#47]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.0 commit 202301190018-42d514236-333b5866f

### Operating system/version

Ubuntu Server 20.04 LTS

### Describe the bug

If I try to open Oil in a etc/nginx folder all entries are prefixed by `/somenumber` and I can't do anything beside closing or navigating up. The content of the etc/nginx folder doesn't mater, nor its location it seems.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/193949/214250399-0f7cf4ac-7583-4657-9bfe-fecc8cd5e9a3.png">

Trying anything on those entries results in a "Could not find entry under cursor" message.

### Steps To Reproduce

1. mkdir -p /tmp/test/etc/nginx/folder
2. touch /tmp/test/etc/nginx/file
3. cd /tmp/test/
4. nvim -u repro.lua
5. open oil and navigate to etc/nginx
6. profit?

### Expected Behavior

I would expect to be able to continue navigating and edit files

### Directory structure

/a/etc/nginx/folder/
/a/etc/nginx/file.txt

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This was a fun bug! Turns out, there's some pattern matching to determine the 'nginx' filetype:
https://github.com/neovim/neovim/blob/cd613712b1a8db233f95f173333b46ebd9df7c9f/runtime/lua/vim/filetype.lua#L2067-L2071
This was overriding the `oil` filetype because our buffer name had `/etc/nginx` in it. Since we use `filetype == 'oil'` to detect oil buffers in a number of places, this caused some things to break. I've fixed it by adding our own, higher-priority filetype rules.

Note that you will probably still not be able to _edit_ the filesystem at /etc/nginx. The reason for that is the file permissions. Any directory where you don't have write permissions the buffer is set to `nomodifiable`. Unfortunately there's not really a way around this, short of running vim as `sudo`.

**Comment by fiplox** [comment]
Not sure if related, but this pattern with `/somenumber` is shown upon searching on the matching file, or by previewing a directory, in preview window everything is prefixed. Is this intended?

**Comment by fiplox** [comment]
![Screenshot_2023-01-24-19-40-59](https://user-images.githubusercontent.com/56274824/214379993-7b04d8d7-f963-439a-8bd5-ca2fdcc3dbb0.png)
![Screenshot_2023-01-24-19-41-21](https://user-images.githubusercontent.com/56274824/214379998-5f20ec6d-b998-459d-a9e7-1546f0d50a89.png)

**Comment by stevearc** [comment]
The preview window is not, I'll have to look into that.

Being visible during search is intentional, and determined by the `concealcursor` setting. See my response to #46 for more info.

**Comment by fiplox** [comment]
> The preview window is not, I'll have to look into that.

Having it only if `vim.opt.conceallevel = 0`
setting it to `3` removes on preview window

**Comment by hlidotbe** [comment]
Glad you had "fun" 😉

> Note that you will probably still not be able to _edit_ the filesystem at /etc/nginx. The reason for that is the file permissions. Any directory where you don't have write permissions the buffer is set to `nomodifiable`. Unfortunately there's not really a way around this, short of running vim as `sudo`.

Not an issue (for me) in this case. The etc/nginx path is meant to be copied in a docker image so it's not actually THE /etc/nginx but it's still triggering the file type matching.

**Comment by stevearc** [comment]
@fiplox I can't reproduce the issue with the conceal level of the preview window. I've made some changes recently to the ordering of events in the preview window, so optimistically it might be resolved. If you still see this happening on the newest version, please open a new issue and provide a minimal repro file.

**Comment by fiplox** [comment]
@stevearc My bad. Actually, it is my config that overrides the Oil config, as I lazy load Oil on `Syntax` event, which is loaded before my settings :sweat_smile:

**Comment by kfu02** [comment]
@fiplox do you mind sharing how you fixed this? I am having the same issue only with a directory named `zsh/`, but running on the clean config provided by the bug report page does not have the same issue.
