### ISSUE TITLE
bug: Error when using `git rm`

### ISSUE THREAD

**Issue by caoculus** [stevearc/oil.nvim#475]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.1

### Operating system/version

NixOS 24.11

### Describe the bug

When git file operations are enabled, I get this error when I try to remove a file from within Oil:

```
Error executing luv callback:
...n/Downloads/test/.repro/plugins/oil.nvim/lua/oil/git.lua:54: E5560: Vimscript function must not be called in a lua loop callback
stack traceback:
        [C]: in function 'jobstart'
        ...n/Downloads/test/.repro/plugins/oil.nvim/lua/oil/git.lua:54: in function 'rm'
        .../test/.repro/plugins/oil.nvim/lua/oil/adapters/files.lua:559: in function <.../test/.repro/plugins/oil.nvim/lua/oil/adapters/files.lua:557>
```

After pressing ENTER, deletion gets stuck at this loading bar...

![image](https://github.com/user-attachments/assets/6a03df8b-42fa-4724-9276-7b7e0473bc0b)

...and if I press "Cancel", then the file still gets deleted.

I took a look at "adapters/files.lua" and I see that the callback for `git add` is wrapped in `vim.schedule_wrap`, while the callback for `git rm` is not:

https://github.com/stevearc/oil.nvim/blob/1fe476daf0b3c108cb8ee1fc1226cc282fa2c9c1/lua/oil/adapters/files.lua#L555-L564

If I manually add `vim.schedule_wrap` then this seems to fix the issue.

Thanks in advance!

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Create an empty git repository (say, in the "test" folder).
2. nvim -u repro.lua
3. Open Oil in the git repository.
4. Create "a.txt" using Oil.
5. Delete "a.txt" using Oil.

### Expected Behavior

The file should be deleted without any error.

### Directory structure

test/a.txt

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--single-branch",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
                -- enable git file operations (this is the only change)
                git = {
                    add = function() return true end,
                    mv = function() return true end,
                    rm = function() return true end,
                }
            })
        end,
    },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Should be fixed. Thanks for the report!
