### ISSUE TITLE
feature request: implement the ability to have a tree view when needed similar to netrw

### ISSUE THREAD

**Issue by Bhanukamax** [stevearc/oil.nvim#48]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be nice to have an optional tree view that we can toggle on and off when needed.

### Provide background

 This is a feature I use in netrw when need to browse a new code base, etc, not a thing that's frequently used, but it comes in handy when I need to pair and explore file tree together with a co worker too.

### Additional details

I have attached a screenshot from netrw for reference, you can get this view if you keep pressing "i" on a netrw buffer to toggle through all the views.
![image](https://user-images.githubusercontent.com/8494781/214333316-9e1ac36b-f2df-4691-bfbe-a78870cb965f.png)

**Comment by stevearc** [comment]
A tree view is out of scope for oil. It would add a massive amount of complexity and maintenance burden, and I'm not convinced that it's worth it. The current directory is exposed via an API, so it should be relatively straightforward to open nvim-tree or neo-tree in the current directory if you need the tree view for browsing.

**Comment by textzenith** [comment]
Easy to do or not, this is what I need!

Reorganize projects en masse using nothing but Vim edits  — if I create a plugin anytime soon, this will be it. Till then, I'll enjoy having fun with oil 😃
