### ISSUE TITLE
After opening a file with oil, my autocommand doesn't work as expected

### ISSUE THREAD

**Issue by budimanjojo** [stevearc/oil.nvim#49]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.2

### Operating system/version

NixOS

### Describe the bug

I have an autocommand to fill the file with template on `BufCreate` and `BufNewFile` when the file is empty or is a new file (doesn't exist in filesystem) like this:
```
local loadTemplate = function()
  local fpath = vim.fn.expand '%:p'
  local fname = vim.fn.expand '%:p:t'
  local tfile = vim.api.nvim_eval('stdpath("config")') .. '/templates/' .. fname
  if vim.fn.filereadable(vim.fn.expand(tfile)) == 1 and vim.fn.getfsize(fpath) < 1 then
    vim.b.tfile = tfile
    vim.cmd([[execute ':0r' b:tfile | normal Gddgg]])
  end
end

local loadtemplate = vim.api.nvim_create_augroup('loadtemplate', { clear = true })
vim.api.nvim_create_autocmd({ 'BufCreate', 'BufNewFile' }, {
  pattern = '*',
  callback = function()
    vim.schedule(loadTemplate)
  end,
  group = loadtemplate
})
```
If I open a new file with `oil.nvim`, the autocommand will fill the with the template even if the file is not empty (that means the function `vim.fn.getfsize(fpath)` is not returning the file size correctly. I don't know why but it's very weird.

### Steps To Reproduce

1. Create a new file named `example` and write something into it.
2. Create a template file in `~/.config/nvim/templates/example` and put something inside that file.
3. Open the `example` file with `oil.nvim`, that file will be filled with the content of `~/.config/nvim/templates/example`.

### Expected Behavior

The file should be opened with it's original content.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
local loadTemplate = function()
  local fpath = vim.fn.expand '%:p'
  local fname = vim.fn.expand '%:p:t'
  local tfile = '~/.config/nvim/templates/' .. fname
  if vim.fn.filereadable(vim.fn.expand(tfile)) == 1 and vim.fn.getfsize(fpath) < 1 then
    vim.b.tfile = tfile
    vim.cmd([[execute ':0r' b:tfile | normal Gddgg]])
  end
end

local loadtemplate = vim.api.nvim_create_augroup('loadtemplate', { clear = true })
vim.api.nvim_create_autocmd({ 'BufCreate', 'BufNewFile' }, {
  pattern = '*',
  callback = function()
    vim.schedule(loadTemplate)
  end,
  group = loadtemplate
})
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This is happening because we first open a buffer named `oil:///path/to/example` and then rename it to `/path/to/example`. When you're checking if the file exists, it's checking for a file named `oil:///...`, which of course isn't a file on disk. Unfortunately `BufAdd` (which is the newer name for `BufCreate`) is called before `BufReadCmd`, which is where we set most of the useful buffer options that could be used to detect that this is an oil buffer. You could add a check for if the buffer name is a URI and early return if so

```lua
vim.api.nvim_create_autocmd({ 'BufCreate', 'BufNewFile' }, {
  pattern = '*',
  callback = function()
    if vim.api.nvim_buf_get_name(args.buf):match(".*://") then
      return
    end
    vim.schedule(loadTemplate)
  end,
  group = loadtemplate
})
```

**Comment by budimanjojo** [comment]
Thanks! I'll close this for now as the workaround work.
