### ISSUE TITLE
feature request: lua api + default option to copy current oil path

### ISSUE THREAD

**Issue by matu3ba** [stevearc/oil.nvim#50]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

This is a common file action, but clipboard may not be available (ie over ssh) so a lua function (also for logging commonly used paths or adding them to a scratch buffer/work file etc) would be nice.

Users may then do their own commands or keymaps to copy `:e path` to register etc.

Copying the paths to file sounds like a less common action and it could be documented how to set those up in the manual/README.

Short question on defaults: Why did you use `<C-h>` for horizontal split and not `<C-v>` ?

### Provide background

I find myself often wanting to combine paths or copy them after inspection via telescope. However after I have opened them, I would need to open a file to use my custom command `FDir`.

This is slower to type than my keybinding to open current dir with oil and a plugin specific keybinding to copy current path
and additionally offers the advantage of being able to inspect what path to copy.

### Additional details

The alternative is to describe to describe the user how to setup a plugin-specific keybinding,
which is then hopefully listed in the `g?` help.

Another alternative is to force the user to open a file to get the directory (what I am currently doing) with
```lua
add_cmd('FrelDir', function() vim.fn.setreg('+', vim.fs.dirname(plenary.path:new(vim.api.nvim_buf_get_name(0)):make_relative())) end, {})
add_cmd('FabsDir', function() vim.fn.setreg('+', vim.fs.dirname(vim.api.nvim_buf_get_name(0))) end, {})
```

Likewise this works for filepaths (and for completion line and column):
```lua
add_cmd('Frel', function() vim.fn.setreg('+', plenary.path:new(vim.api.nvim_buf_get_name(0)):make_relative()) end, {}) -- copy relative path
add_cmd('Fabs', function() vim.fn.setreg('+', vim.api.nvim_buf_get_name(0)) end, {}) -- absolute path
add_cmd('Fline', function()
  local fname = vim.fs.basename(vim.api.nvim_buf_get_name(0))
  local lineNum = vim.api.nvim_win_get_cursor(0)[1]
  vim.fn.setreg('+', fname .. ':' .. tostring(lineNum))
end, {}) -- copy filename:line
add_cmd('Fcolumn', function()
  local fname = vim.fs.basename(vim.api.nvim_buf_get_name(0))
  local line_col_pair = vim.api.nvim_win_get_cursor(0) -- row is 1, column is 0 indexed
  vim.fn.setreg('+', fname .. ':' .. tostring(line_col_pair[1]) .. ':' .. tostring(line_col_pair[2]))
end, {}) -- copy filename:line:column
```

Also, many thanks for the great plugin.

**Comment by stevearc** [comment]
I've added an action that will copy the path of the entry under the cursor. That may be sufficient for you, and if not it should provide an example for you to work off of to get the desired behavior.

I used `<C-h>` as the default mapping for split because `<C-v>` enters visual block mode, which is a relatively common operation for editing text, so I didn't want a binding the conflicts with it.

**Comment by matu3ba** [comment]
Many thanks!

**Comment by matu3ba** [comment]
I think the function feels now superflous.

For anyone reading this, you can use something along
```lua
M.pwshCdExec = function()
  local dir = oil.get_current_dir()
  local entry = oil.get_cursor_entry()
  if not dir or not entry then return "" end
  return "cd " .. dir .. "; .\\" .. entry.parsed_name
end
local setPlusAnd0Register = function(content)
  vim.fn.setreg('0', content)
  -- if vim.fn.hasclip
  vim.fn.setreg('+', content)
end

add_cmd('Oabs', function() setPlusAnd0Register(oil.get_current_dir()) end, {})
add_cmd('Orel', function() setPlusAnd0Register(plenary.path:new(oil.get_current_dir()):make_relative()) end, {})
```
