### ISSUE TITLE
feature request: Extend preview.win_options to override win_options

### ISSUE THREAD

**Issue by windowsrefund** [stevearc/oil.nvim#509]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I now see how `win_options` extends to the preview window. This is good since I like to have things like `number`, `signcolumn`, and `relativenumber` enabled for various reasons. However, I don't need these things in the preview window (all I want to do is preview the content in the most lightweight manner possible). If `preview.win_options` could be refactored to override the higher level `win_options`, one could disable all the bloat when it comes to previewing.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
I'm not really sure what you're talking about. The preview window only sets window options from `preview.win_options`

https://github.com/stevearc/oil.nvim/blob/52cc8a1fb35ea6ce1df536143add7ce7215c63c0/lua/oil/mutator/preview.lua#L111-L113

**Comment by windowsrefund** [comment]
This doesn't appear to be working

```
          preview = {
            win_options = {
              number = false,
              relativenumber = false,
              signcolumn = "no",
            },
          },
```

**Comment by stevearc** [comment]
Can you provide a minimal config that reproduces the issue? I tried using the script below and it appears to be working as intended.

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/oil.nvim",
    opts = {
      win_options = {
        number = true,
        relativenumber = true,
        signcolumn = "yes",
      },
      preview = {
        win_options = {
          number = false,
          relativenumber = false,
          signcolumn = "no",
        },
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by windowsrefund** [comment]
Good call. Yea, it does work with a minimal config so I'll close this out and get busy trying to figure out what's overriding or confusing things.

**Comment by stevearc** [comment]
@mehalter oof, this is a case of some unfortunate name collisions. I have _foolishly_ decided to call the window that pops up on `:w` that shows you all of the filesystem actions that are about to be executed the "preview" window, because it shows you a preview of what is about to happen. That was a mistake and I should probably try to rename it to something more clear. It looks like you are looking at the actual built-in preview window that appears when using the `actions.preview` keymap. There currently aren't any config options that allow you to customize that window.

**Comment by mehalter** [comment]
Ah, thanks so much for the clarification on the window names. The original poster was asking about the preview window I am referring to I believe. So maybe this is a feature request rather than a bug

**Comment by stevearc** [comment]
I've refactored the config options (with backwards compatibility shims) so it's now possible to add `win_options` or similar to the preview window

**Comment by stevearc** [comment]
I did not _implement_ it, I just refactored it to a state where the config options make sense and it would be easy for someone else to submit a PR for it
