### ISSUE TITLE
bug: Oil fails to open if the user is currently focused on a terminal buffer

### ISSUE THREAD

**Issue by Jeansidharta** [stevearc/oil.nvim#51]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.2

### Operating system/version

arch-linux 6.0.12

### Describe the bug

Oil.nvim fails to open when user is currently focused on a terminal buffer.

Whenever the user tries, they are greeted with this error message:

`Could not find oil adapter for scheme 'term://'`

### Steps To Reproduce

- Create a minimal config as specified below (`repro.lua`)
- Open neovim: `nvim -u repro.lua`
- Open a terminal: `:terminal`
- Open oil: `:lua require('oil').open()`

### Expected Behavior

A normal oil window should open, with no error message

### Directory structure

No specific directory structure required

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy.nvim if it's not located.
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

return require("lazy").setup({
  {
    "stevearc/oil.nvim",
    config = true,
  },
})
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Thanks for the report! Should be fixed now.
