### ISSUE TITLE
bug: Issues with split behavior

### ISSUE THREAD

**Issue by MarcoBuess** [stevearc/oil.nvim#510]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Windows 11 23H2

### Describe the bug

I overwrote the default split keymaps like so:
```lua
{
  ["<C-h>"] = false,
  ["<C-s>"] = { "actions.select", opts = { horizontal = true }, desc = "Horizontal [s]plit" },
  ["<C-v>"] = { "actions.select", opts = { vertical = true }, desc = "[V]ertical split" },
}
```
Both split keymaps split vertically though. What am I missing?

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

Overwrite keymaps with the ones in the description.

### Expected Behavior

`<C-s>` does a horizontal split, `<C-v>` does a vertical split.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              columns = {
                "permissions",
                "size",
                "mtime",
                "icon",
              },
              keymaps = {
                ["<C-h>"] = false,
                ["<C-s>"] = { "actions.select", opts = { horizontal = true }, desc = "Horizontal [s]plit" },
                ["<C-v>"] = { "actions.select", opts = { vertical = true }, desc = "[V]ertical split" },
              },
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by Foo-x** [comment]
The user's config and the default config is merged with `vim.tbl_deep_extend()`.
https://github.com/stevearc/oil.nvim/blob/52cc8a1fb35ea6ce1df536143add7ce7215c63c0/lua/oil/config.lua#L358

The keymap for `<C-s>` already exists in default config which `vertical = true`, so merging with user's keymap which `horizontal = true` will make both horizontal and vertical true.
https://github.com/stevearc/oil.nvim/blob/52cc8a1fb35ea6ce1df536143add7ce7215c63c0/lua/oil/config.lua#L65

It looks like neovim splits vertically if both is true. (`lua vim.cmd.sbuffer({ mods = { horizontal = true, vertical = true } })`)

IMO keymaps should not be deep merged.

**Comment by stevearc** [comment]
@Foo-x is correct, this is because of some unfortunate side effects from the deep merging. The fix is a bit inelegant, but very simple.
