### ISSUE TITLE
feature request: How can I write a function to have actions.cd add path to zoxide before cd-ing into it?

### ISSUE THREAD

**Issue by esn89** [stevearc/oil.nvim#512]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Not asking for this to be implemented inside oil.nvim, 

but I am wondering how I can write a function to have the `~` run a `zoxide add $PATH` command before `:cd`ing into it.

How can I start?  Is this a callback function to write?

### What is the significance of this feature?

strongly desired

**Comment by esn89** [comment]
I am trying to get it to work with something like this:

```lua
                ['`'] = {
                    callback = function()
                        local oil = require('oil')
                        local dir = oil.get_cursor_entry()
                        print(vim.inspect(dir['name']))
                        -- vim.cmd('zoxide add ' .. dir)
                        require('oil.actions').cd()
                    end,
                },
```

But the `require('oil.actions').cd()`
Is throwing `/Users/me/.config/nvim/lua/plugins/oil/init.lua:39: attempt to call field 'cd' (a table value)` even with the vim.cmd commented out.

**Comment by stevearc** [comment]
Try something like this:
```lua
['`'] = {
  callback = function()
    local dir = require("oil").get_current_dir()
    if dir then
      vim.system({'zoxide', 'add', dir})
      vim.cmd.cd({args = {dir}})
    else
      vim.notify("Cannot :cd; not in a directory", vim.log.levels.WARN)
    end
  end,
},
```

**Comment by esn89** [comment]
That worked beautifully.  Thank you @stevearc
