### ISSUE TITLE
feature request: History Navigation (Prev/Next Jump)

### ISSUE THREAD

**Issue by Akirisu-kirisu** [stevearc/oil.nvim#513]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

**Summary:**
Add a feature to Oil.nvim that allows users to view and navigate their history of visited locations in the file system, with the ability to jump back and forth between previously visited locations.

**Proposed Features:**

1. **Location History:**
    - Track the history of visited directories as users navigate through them in Oil.nvim.
    - Display a list of recent directories that can be accessed quickly (like a "breadcrumb" style history).
    - Allow users to click on any of the locations in the history list to directly jump to that directory.
2. **Prev/Next History Navigation:**
    - Provide commands or key mappings to move between the previous and next locations in the history list.
    - For example, `:OilHistoryPrev` and `:OilHistoryNext` or key bindings like `<C-o>` for previous and `<C-i>` for next.
    - This would allow users to jump back and forth between directories without needing to manually search for them.
3. **Persistent History:**
    - Optionally, make the history list persistent across sessions, so that users can return to previously visited directories even after restarting Neovim.

**Example Workflow:**

- User opens Oil.nvim and navigates to `/home/user/projects/`.
- They then navigate to `/home/user/projects/project1/` and later to `/home/user/projects/project2/`.
- At any point, the user can press a shortcut or use a command to jump back to `/home/user/projects/project1/` or `/home/user/projects/` using the history navigation.

**Benefits:**

- Improves navigation efficiency by reducing the need to manually retrace steps.
- Provides a more intuitive and user-friendly experience when working across multiple directories.
- Helps users quickly return to important or frequently visited directories.

### Provide background

**Motivation:**
Currently, when navigating the file system in Oil.nvim, once you navigate away from a location, there is no easy way to jump back to previously visited directories. This feature would be useful for those who frequently navigate through multiple directories and want a more efficient way to return to past locations.

### What is the significance of this feature?

strongly desired

### Additional details

sj.nvim that allows users to navigate through their previous search queries with the ability to jump back and forth between the last search and subsequent searches.

**Comment by stevearc** [comment]
I am unlikely to want to add this to oil, as it's I believe a fairly niche use case and would require a decent amount of code, documentation, maintenance, etc.

If you haven't tried it yet, you can look into setting `cleanup_delay_ms = false` so the oil buffers won't get auto deleted in the background. That should enable the jumplist to navigate forwards/backwards through your oil buffer history.

**Comment by Akirisu-kirisu** [comment]
Thank you for your suggestion and the workaround with `cleanup_delay_ms = false`. After considering the scope of the requested feature, I've decided not to move forward with adding it to the oil project at this time. I really appreciate the time you took to look into this and provide an alternative solution!

I’ll go ahead and close the issue as "not planned." Thanks again for your input!
