### ISSUE TITLE
bug: ctrl-o / ctrl-i does not work as expected

### ISSUE THREAD

**Issue by swtch1** [stevearc/oil.nvim#517]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

macOS 14.6.1

### Describe the bug

It is typical when using vim/nvim to enter ctrl-o to go back.  When navigating a directory structure with oil I often navigate through the tree, enter a file, press ctrl-o to go back to oil.  But then I may press ctrl-i to go back to the file.  I would expect oil to act like any other file buffer when navigating this way but it does not, and sometimes I end up in a file that I haven't visited at all during my session.

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. nvim . (assuming you get oil here)
2. navigate to directory
3. navigate to file
4. ctrl-o (expect to go back to oil, which it does)
5. ctrl-i (expect to go back to file, which it does)
6. ctrl-o (expect to go back to oil, which is does not)

Originally I thought this behavior depended on navigating through a directory first, but that's not the case.  There is actually a randomness to whether it will work as expected or not.

### Expected Behavior

Described in steps to reproduce.

### Directory structure

Any structure with files in a directory.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
The default behavior for oil is to try to clean up unused buffers in the background, but that does mess with the jumplist. If you expect the jumplist to operate mostly on files, then it's intuitive. If you expect it to jump back into directories, then it isn't. You can try disabling this auto cleanup behavior by setting `cleanup_delay_ms = false`

**Comment by swtch1** [comment]
That makes a lot of sense, I wouldn't want a bunch of oil buffers hanging around.  I'll try that setting or modify my workflow.  Thank you.

**Comment by looshch** [comment]
> The default behavior for oil is to try to clean up unused buffers in the background

@stevearc can i please kindly ask if i use the plugin exclusively only via `vim.cmd 'vertical Oil'` is it possible that it creates multiple buffers or will it always re-use the same one?
