### ISSUE TITLE
feature request: Are there plans to support 3rd/image.nvim ? in the preview window it would be amazing. 

### ISSUE THREAD

**Issue by carlos-algms** [stevearc/oil.nvim#518]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be amazing to have support for image rendering in the preview window. 
With some custom code, it's possible to make it work on Telescope already. 

nvim-neo-tree/neo-tree.nvim already supports it by default, if you have image.nvim installed, the preview window will use it. 

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Doesn't this already exist? I was under the impression that image.nvim hijacks the buffer when you open an image file to render the image, which means it should work out of the box with oil.

**Comment by carlos-algms** [comment]
That seems about right. 
I don't know why it didn't work before. 

<img width="967" alt="image" src="https://github.com/user-attachments/assets/e9ee07f1-9439-491f-969f-10cb55c32e94">

thank you for commenting.
