### ISSUE TITLE
bug: Trashing a file and renaming another file to trashed file results in wrong content!

### ISSUE THREAD

**Issue by rieje** [stevearc/oil.nvim#519]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Arch Linux

### Describe the bug

Trashing `b.txt` and renaming `a.txt` to `b.txt` then applying the changes results in the  now `b.txt` with the contents of `a.txt`.

### What is the severity of this bug?

blocking (cannot use plugin)

### Steps To Reproduce

1. `echo a > a.txt`
2. `echo b > b.txt`
3. `nvim -u repro.lua .`
4. Launch Oil, delete fileB line, rename fileA line to fileB, save the buffer and exit.
5. `cat b.txt` shows 'a'

### Expected Behavior

 `cat b.txt` shows 'b', as it's `a.txt` renamed to `b.txt`.

### Directory structure

./a.txt ./b.txt

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
So you have two files:
```
a.txt -> "a"
b.txt -> "b"
```
You trash `b.txt` and you rename `a.txt` -> `b.txt`. Let's process those one at a time. First the trash
```
a.txt -> "a"
```
Then the rename
```
b.txt -> "a"
```
Then we run `cat b.txt` and see "a". Why do we think this result is incorrect?

**Comment by rieje** [comment]
Sorry I was drunk and lacking sleep, really don't know what I was thinking... Closing this.
