### ISSUE TITLE
feature request: on file created hook

### ISSUE THREAD

**Issue by Skyppex** [stevearc/oil.nvim#527]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

When i create new files with oil, i want the file to be filled with some basic content. A hook which takes the file path would be perfect. I can handle writing to the file in the hook. This makes it a bit more versatile as you're not locked into writing content to the file, it can be used for anything else where you might need the file path or just the filetype.

### Provide background

When creating .cs files i (almost) always want it to contain a line with the namespace that c# code in the file should exist within. In the most popular IDEs this just happens by itself, but since nvim is a text editor, i have to manually write it in. I just want to avoid that because its boilerplate and i don't really care about it, but it has to be done. Adding a hook which is invoked after a file is created will allow me to do this with a little configuration on my part.

I tried using an autocmd with `"BufNewFile"`, but that falls short because its only when

### What is the significance of this feature?

strongly desired

### Additional details

I would say this is `strongly desired` for me, but i'm betting its a `nice to have` for most.

i imagine the configuration like this:
```lua
{
    file_created_hooks = {
        lua = function(path) ... end,
        cs = function(path) ... end,
    }
}
```

the key (`lua`, `cs`) is the neovim filetype and the `path` is the full path to the file

**Comment by stevearc** [comment]
There is a User autocmd that is dispatched after performing file mutations
https://github.com/stevearc/oil.nvim/blob/3c2de37accead0240fbe812f5ccdedfe0b973557/lua/oil/mutator/init.lua#L423-L426

The type definition for actions is above
https://github.com/stevearc/oil.nvim/blob/3c2de37accead0240fbe812f5ccdedfe0b973557/lua/oil/mutator/init.lua#L19-L49

You'll need to process the urls to get the actual filename, but it should be relatively straightforward

**Comment by Skyppex** [comment]
> There is a User autocmd that is dispatched after performing file mutations
> 
> https://github.com/stevearc/oil.nvim/blob/3c2de37accead0240fbe812f5ccdedfe0b973557/lua/oil/mutator/init.lua#L423-L426
> 
> The type definition for actions is above
> 
> https://github.com/stevearc/oil.nvim/blob/3c2de37accead0240fbe812f5ccdedfe0b973557/lua/oil/mutator/init.lua#L19-L49
> 
> You'll need to process the urls to get the actual filename, but it should be relatively straightforward

:o huge new, ty :)
