### ISSUE TITLE
feature request: close oil after opening split

### ISSUE THREAD

**Issue by roginfarrer** [stevearc/oil.nvim#53]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I'd like to be able to close oil once I've opened a split, so the original window is opened to the buffer I was on when oil was opened. 

### Provide background

I'm used to this behavior coming from lir, and it's a bit annoying to have to return to the oil buffer to close it. I have a hacky workaround that involves tracking window numbers and jumping back and forth between the new and original windows.

```lua
local select = function(direction)
  local actions = require 'oil.actions'
  local selectCmd = 'select_' .. direction == 'vertical' and 'vsplit' or 'split'

  -- the active oil window
  local winnr = vim.api.nvim_get_current_win()
  -- execute open split and get its winnr
  actions[selectCmd].callback()

  if vim.api.nvim_win_is_valid(winnr) then
    local newWinnr = vim.api.nvim_get_current_win()
    -- go back to original oil window, and close it
    vim.api.nvim_set_current_win(winnr)
    require('oil.actions').close.callback()

    if vim.api.nvim_win_is_valid(newWinnr) then
      -- Jump to the newly opened split
      vim.api.nvim_set_current_win(newWinnr)
    end
  end
end
```

I think this can be implemented in a more straightforward manner internally.

**Comment by stevearc** [comment]
How about this solution?
```lua
local oil = require("oil")
oil.select({ vertical = true })
vim.cmd.wincmd({ args = { "p" } })
oil.close()
vim.cmd.wincmd({ args = { "p" } })
```
If I were to write this functionality with oil, it would basically be the same thing

**Comment by roginfarrer** [comment]
Ah, that works much better than my solution. Did not realize that was possible with `wincmd`. Thanks!
