### ISSUE TITLE
feature request: Single side padding

### ISSUE THREAD

**Issue by XxDraggy** [stevearc/oil.nvim#538]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would really love being able to set the padding for every side of the floating window individually.

### Provide background

Currently I have the padding on 10 and for me its on the sides perfect. But then also the top and bottom side get squished in and those sides just do not look ok.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
You can customize this using the `float.override` function in the config. Simply edit the row/col/width/height values as you like to customize the appearance of the floating window.
