### ISSUE TITLE
feature request: Limit going beyond the project folder (change actions.parent)

### ISSUE THREAD

**Issue by kelvinauta** [stevearc/oil.nvim#541]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

(I can contribute with this feature if it is accepted)
Currently, actions.parent goes to the parent directory without any limitation. The idea would be to change this action so that it can go, at most, to the project folder. Currently, this can be achieved by creating a custom function like this:
```lua
local oil = require("oil")
local actions = require("oil.actions")
local function is_project_root(path)
    return ( vim.fn.getcwd() == path ) or (vim.fn.getcwd() .. "/" == path)
end
local custom_parent = function()
    local current_dir = oil.get_current_dir()
    if is_project_root(current_dir) then
        vim.notify("Ya estás en la raíz del proyecto", vim.log.levels.WARN)
        return
    end
    actions.parent.callback()
end
```
and set in the oil configuration
```lua
-- keymaps
 ["-"] = { callback = custom_parent, mode = "n" }
```

### Provide background

The main reason is because sometimes I accidentally go beyond the root of the project, and this can be uncomfortable. I even feel a bit scared of ruining my system files by accident or with some automation using oil. I think it would also be interesting to add an option in the config called `limit_parent="cwd"` with options such as cwd or root.

### What is the significance of this feature?

nice to have

### Additional details

If this feature is accepted, I would like to know if you have any contribution guide to be able to contribute with this.

**Comment by stevearc** [comment]
To do this in any way that actually provides safety is _quite_ difficult, as we would have to prevent editing outside the cwd from all possible edit sources. Throw symlinks in and it gets even more complicated. I don't think the benefit of this is worth the complexity of adding it to the plugin officially.

As you've discovered, it's straightforward to do a quick hack that gets you 90% of the way there. I think that works great as a user customization, but it's not robust enough for me to want to merge.
