### ISSUE TITLE
feature request: configure which files are hidden

### ISSUE THREAD

**Issue by xuxinx** [stevearc/oil.nvim#58]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

respect 'wildignore' like vinegar or add a option to configure which files are hidden.

### Provide background

suppose I have files:
- .git
- .gitignore
- a.txt

I want to hide the `.git` but not hide `.gitignore` and `a.txt`.

**Comment by stevearc** [comment]
I've added a config function that will allow you to define which files should be categorized as "hidden".

**Comment by Arisa-Snowbell** [comment]
It would be cool to have the function already in README.md as I can't really make it easily as I never used lua really, I want it to read .gitignore and ignore files from there and ignore .git
