### ISSUE TITLE
Canceling File Modification Fails to Return File's Original State in Oil

### ISSUE THREAD

**Issue by UnrealApex** [stevearc/oil.nvim#6]
Doing a file operation and canceling it does not return the file's state to how it was prior to the file operation.

**Reproduction**
1. Do a file operation, delete(`dd`) is easy to visualize
2. write the file with `:w`
3. Cancel the deletion
4. See that the file has not returned in the buffer/back to its original state

**Comment by stevearc** [comment]
I see, this does clarify what you were talking about in the other issue. So this is actually the intended behavior. If you make some changes, `:write`, then see "oops, this is accidentally going to do something I didn't intend", you should be able to cancel it and perform some more changes without losing your prior work. However, if you want to _intentionally_ discard your changes, you can do that the same way you would with any other buffer: `:e!`

**Comment by UnrealApex** [comment]
I understand where this could be useful. Perhaps make it an option that is setable?

**Comment by stevearc** [comment]
I'm hesitant to add UI or a config option for this. If you want, it's easy to create a keybind that calls [discard_all_changes()](https://github.com/stevearc/oil.nvim/#discard_all_changes). If you want you can even create that keybinding just in the preview window:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "oil_preview",
  callback = function(args)
    vim.keymap.set("n", "d", function()
      vim.api.nvim_win_close(0, true)
      require("oil").discard_all_changes()
    end, { buffer = args.buf })
  end,
})
```

**Comment by UnrealApex** [comment]
Your autocommand almost works! It closes the confirm buffer but Oil's discard function does not seem to work.

**Comment by stevearc** [comment]
Ah, I think this was because the `:w` would mark the buffer as not modified, even if you cancel out of the preview window. Then discarding the changes wouldn't work, because the buffer wasn't marked as modified. It should work now

**Comment by UnrealApex** [comment]
Hmm, I do not think the autocmd worked. The mapping fires, but `discard_all_changes()` does not revert the buffer state.

**Comment by stevearc** [comment]
Interesting. I'm unable to reproduce it; `discard_all_changes()` works for me now no matter how I try it. Could you provide detailed repro steps? Preferably using a minimal config like the one in the issue template.

**Comment by UnrealApex** [comment]
Nevermind, just had to call it before Oil.
