### ISSUE TITLE
bug: copying a file and trying to rename it deletes the concealed text instead of the file name

### ISSUE THREAD

**Issue by adriafarres** [stevearc/oil.nvim#61]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Arch Linux

### Describe the bug

Given a directory with a file, copying the file and trying to rename it with `cw` deletes the concealed text instead of the file name

### Steps To Reproduce

1. Create a file in given directory such that oil sees the following
```
abc.txt
```
2. Open oil, copy the file with `yy` and paste it with `p`
```
abc.txt
abc.txt
```
3. Try to rename the new file by pressing `cw`. What you see is
```
abc.txt
001 abc.txt    (the slash at the beginning is removed)
```
4. The file name is not getting edited; the concealed text is

### Expected Behavior

The cursor should be positioned at the beginning of the file name and not before the concealed text.

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
I've added a change that forces the cursor to be positioned after the concealed file ID at the beginning of the line. I tried to do it in a minimally invasive way so the editing of new files wouldn't experience weird cursor behavior, but it will probably need some testing to iron out the kinks.

**Comment by adriafarres** [comment]
Thank you for the fix. It has worked well for me up until now. I didn't mention anything, because I wanted to give it some time to try it out.
