### ISSUE TITLE
feature request: Add `open_tcd`

### ISSUE THREAD

**Issue by nyngwang** [stevearc/oil.nvim#62]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

like `actions.open_cwd` but instead show the buftree by `vim.fn.getcwd(-1, 0)` instead of `vim.fn.getcwd(-1, -1)`.

### Provide background

So people who have lots of tabpages can have a different tabpage current-directory.

**Comment by stevearc** [comment]
The built-in actions are only meant to cover things that are commonly needed or complex enough that having a single implementation would be useful. For something like this it's easy enough to do yourself:

```lua
require("oil").setup({
  keymaps = {
    ["_"] = function()
      require("oil").open(vim.fn.getcwd(-1, 0))
    end
  }
})
```
