### ISSUE TITLE
feature request: I want to see the corresponding cwd of the current `:Oil` buffer.

### ISSUE THREAD

**Issue by nyngwang** [stevearc/oil.nvim#63]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

title. I'm astonished by the fact that nobody asked for this before.

What if I have two projects(or two subfolders under the same project) consisting of exactly the same folder layout? For example: (they have identical layouts)

```
  config/
  data/
  utils/
```

 Then it will be indistinguishable about which projects/subfolders I'm at. Note that `:pwd` doesn't help (Say I never set window current-directory then `:pwd` will always stick to the value of `vim.fn.getcwd(-1, -1)`).

### Provide background

I guess that your consideration might be that you will then have to define a special line, e.g. the first line, to put the result of `cwd` for the content of the current `:Oil` buffer. So feel free to reject it.

**Comment by vimalk78** [comment]
i have the same question, how to get oil to display the current directory, and i see same answer `winbar`

for someone like me who has no idea what winbar is, can someone please give required steps? i will be so thankful.

i get following error when i try `:winbar` `E492: Not an editor command: winbar`

**Comment by manishbhatt** [comment]
@vimalk78 

Here is my working  config for Oil

```
return {
    "stevearc/oil.nvim",
    opts = {
        delete_to_trash = true,
		win_options = {
		    winbar = "%{v:lua.require('oil').get_current_dir()}"
		 }
    },
    dependencies = {
        "nvim-tree/nvim-web-devicons"
    }
}
```
