### ISSUE TITLE
feature request: Please support `nyngwang/NeoZoom.lua`

### ISSUE THREAD

**Issue by nyngwang** [stevearc/oil.nvim#64]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Currently, oil.nvim always close the floating window created by [nyngwang/NeoZoom.lua](https://github.com/nyngwang/NeoZoom.lua) when it shouldn't.

#### `<C-c>` doesn't work as expected:

1. Run `:NeoZoomToggle` on a buffer `A` to create a floating window holding `A`.
2. Rnd `:Oil` to replace `A` with the filetree.
3. Press `<C-c>` to switch back to `A`.

Step 3. will fail and close the floating window.

#### `<CR>` doesn't work as expected:

1. Run `:NeoZoomToggle` on a buffer `A` to create a floating window.
2. Rnd `:Oil` to replace `A` with the filetree.
3. Press `<CR>` on buffer `B` to switch the current buffer to `B`.

Again, step 3. will close the floating window and stay in the oil buffer.

### Provide background

I expect that I oil.nvim should not close any floating window created by other plugins.

**Comment by stevearc** [comment]
Should be fixed now

**Comment by stevearc** [comment]
Did the fix for #65 resolve this as well?
