### ISSUE TITLE
feature request: Support window view restoring on `require('oil').close()`

### ISSUE THREAD

**Issue by nyngwang** [stevearc/oil.nvim#65]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It will be great if `vim.fn.winrestview(view)` can be implemented on the plugin side. As a plugin author, I know this is non-trivial(as one might call `:Oil` in any window under any tabpage, so storing/invalidating them could be tedious) so put it as a feature request and feel free to reject it.

### Provide background

After toggling `:Oil` buffer by `M.open()` and `M.close()`, the `topline` of the current window might be different from the one before calling `M.open()`, i.e. it's like calling `zz` after `M.close()`.

**Comment by stevearc** [comment]
Done!
