### ISSUE TITLE
feature request: set cwd to the currently displayed directory in the oil buffer

### ISSUE THREAD

**Issue by kekscode** [stevearc/oil.nvim#68]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to have an option in the oil config which allows for dynamically changing the working directory dynamically while browsing through folder structures in oil. A bit like `autochdir` in the (neo)vim config maybe, but buffer-local for the oil buffer, like a `lcd`.

### Provide background

I love oil for browsing through directories and sometimes batch processing renames and stuff (thanks a lot for oil.nvim, i just love it!)

Sometimes i want to bring up telescope for doing a quick live-grep + adding the found files to the quickfix list for later processing, too. Right now, i would have to manuall `cd ...` to the current directory displayed in oil and then start interacting with telescope.
I would love if there would be an option which allows for dynamically setting the working directory to the one which is currently displayed in oil. Right now, it does not change while browsing through the directories (which is a good default i guess), but i'd like to see an options which enables dynamically changing the working directory while browsing with oil in order to fire up other tools (like telescope) to be able to use the combination of tools.

### Additional details

Maybe there are side effects to be considered, but i cannot think of any myself.

**Comment by stevearc** [comment]
The way I handle this personally is I set buffer-local keymaps in oil that override my global keymaps. For example, I use `<leader>ff` to search for files. In oil buffers, I set this keymap
```lua
vim.keymap.set("n", "<leader>ff", function()
  require("telescope.builtin").find_files({cwd = require("oil").get_current_dir()})
end, {buffer = bufnr})
```

Perhaps something like this would work for you?

**Comment by Bekaboo** [comment]
For someone who found this and prefer change cwd instead of using buffer-local keymaps, here is my solution:

```lua
vim.api.nvim_create_autocmd('TextChanged', {
  desc = 'Set cwd to follow directory shown in oil buffers.',
  group = vim.api.nvim_create_augroup('OilAutoCwd', {}),
  pattern = 'oil:///*',
  callback = function()
    if vim.bo.filetype == 'oil' then
      vim.cmd.lcd(require('oil').get_current_dir())
    end
  end,
})
```

**Comment by artem-nefedov** [comment]
OK, so I managed to make it work "reliably" with this setup, but it looks like a terrible hack to be honest:

```lua
keymaps = {
      ["<CR>"] = function()
        require("oil.actions").select.callback()
        vim.defer_fn(function()
          local curdir = require("oil").get_current_dir()
          if curdir then
            vim.cmd.lcd(curdir)
          end
        end, 200)
      end,
}
```

**Comment by stevearc** [comment]
Try using this:

```lua
keymaps = {
  ["-"] = function()
    require("oil.actions").parent.callback()
    vim.cmd.lcd(require("oil").get_current_dir())
  end,
  ["<CR>"] = function()
    require("oil").select(nil, function(err)
      if not err then
        local curdir = require("oil").get_current_dir()
        if curdir then
          vim.cmd.lcd(curdir)
        end
      end
    end)
  end,
}
```

The `select` function is async, so we don't have a guarantee that the new buffer has been entered by the time it finishes running. You need to put the lcd logic in the callback

**Comment by ggandor** [comment]
Improving on @Bekaboo s snippet, I think this is the cleanest and most general solution:

```lua
  vim.api.nvim_create_autocmd('FileType', {
    group = vim.api.nvim_create_augroup('OilAutoCwd', {}),
    pattern = 'oil',
    callback = function ()
      vim.cmd.lchdir(require'oil'.get_current_dir())
    end,
  })
```
