### ISSUE TITLE
Refresh On File Modifications Outside Neovim

### ISSUE THREAD

**Issue by UnrealApex** [stevearc/oil.nvim#7]
It would be nice if Oil would be refreshable like Netrw with `<C-l>` when a file is modified outside of Neovim.

**Comment by stevearc** [comment]
Are you thinking that `<C-l>` would do the same thing as `:edit!`?

**Comment by UnrealApex** [comment]
Indeed. It would be a nice quality of life change.

**Comment by stevearc** [comment]
Added!
