### ISSUE TITLE
feature request: expand directory

### ISSUE THREAD

**Issue by canvanaut** [stevearc/oil.nvim#70]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hi, I'm just getting started with using this awesome plugin! It would be nice if one can expand the directory under the cursor to view the nested files/directories to easily manipulate them across directories.

### Provide background

Difficult to manipulate nested files/directories in different subdirectories.

**Comment by stevearc** [comment]
I'll give the same answer as #48: this is effectively a tree view and it's out of scope. It would require basically a complete rewrite, and would be far more complex to boot.
