### ISSUE TITLE
bug: float window title displays on top of the preview window

### ISSUE THREAD

**Issue by krivahtoo** [stevearc/oil.nvim#72]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

v0.9.0-dev-920+gc9b0fe1f4

### Operating system/version

Arch Linux

### Describe the bug

The floating window title is displayed on top of the preview window.
![image](https://user-images.githubusercontent.com/41364823/224502608-61736c45-fbf3-4c63-826d-2c1f8da1c5c9.png)

### Steps To Reproduce

1. nvim -u repro.lua
2. open oil with `require('oil').open_float()`.
3. do some editing and save.

### Expected Behavior

The floating window title should be hidden with its window.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
  float = {
    -- Padding around the floating window
    padding = 10,
    max_width = 40,
    max_height = 0,
    border = "rounded",
    win_options = {
      winblend = 0,
    },
  },
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
fixed, thanks for the report!
