### ISSUE TITLE
feature request: a robust way to open files with xdg-open / open

### ISSUE THREAD

**Issue by kekscode** [stevearc/oil.nvim#73]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to open the selected entry in Oil with `open` (mac) or `xdg-open` (linux). Maybe with a mapping like `gx` which is commonly used to open URIs.

Disclaimer: This is (maybe) not a feature request, more a workflow question maybe and may result in my lack of knowledge in properly configuring keymaps using the Oil API.

### Provide background

Oil is so very useful to me, that i started to use it as an alternative to a normal file explorer application or the terminal for file/folder operations and batch processing of files. A good example is:

I have a lot of 3D printable gcode ascii files which i copy/move and rename/patch inside an Oil buffer and with vim quickfix lists / `cdo` commands. Other examples are things like batch-processing big JSON files like Grafana dashboards, SVG image XMLs, etc.

After the processing, I would like to open those directly from Oil with other (GUI) applications on my OS. My understanding is that the best way to do this is to use `xdg-open` on Linux or `open` on mac. So i end up using `:!open '<filepath/filename>'` in nvim which is a bit clumsy and feels wrong while already looking on an Oil buffer with all the files/paths and having set the cwd to the right location, too.

### Additional details

I read through the docs and hoped to find something in the Oil API like a field which contains the currently selected file path + file name which i could just map to a keymapping, but i couldn't find something usable. But i may just have overlooked something obvious?

**Comment by stevearc** [comment]
Yes, so [get_cursor_entry](https://github.com/stevearc/oil.nvim/#get_cursor_entry) returns a table that contains the name of the item under the cursor, and [get_current_dir](https://github.com/stevearc/oil.nvim/#get_current_dir) should return the current directory. You should be able to put those together to run `open`/`xdg-open` using `vim.fn.system` or `vim.fn.jobstart`.

**Comment by stevearc** [comment]
Translated to a format you can use with the keymaps config option:
```lua
local oil = require("oil")
oil.setup({
  keymaps = {
    ["gx"] = function()
      local cwd = oil.get_current_dir()
      local entry = oil.get_cursor_entry()
      if cwd and entry then
        vim.fn.jobstart({ "open", string.format("%s/%s", cwd, entry.name) })
      end
    end,
  },
})
```
