### ISSUE TITLE
feature request: configurable preview window

### ISSUE THREAD

**Issue by krivahtoo** [stevearc/oil.nvim#74]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

The preview window is currently way too big for displaying changes (which is often just less than 5 lines). It would be nice to have a configuration option like the floating window.

**Comment by stevearc** [comment]
I've pushed up a change. Now, you can create whatever preview window you want and oil will use it. You can [copy the logic from actions.preview](https://github.com/stevearc/oil.nvim/blob/57451c517d96ad856ed418203729f5d3cb200de6/lua/oil/actions.lua#L40-L58) and just add something right before the call to `oil.select({ preview = true })` that creates a window and sets `previewwindow = true` on it. Oil will automatically display the preview content in that window.

**Comment by krivahtoo** [comment]
Sorry, I didn't realize there is a file preview window, the preview window I meant is the confirmation window that shows up after running `:w` command.

Created here:
https://github.com/stevearc/oil.nvim/blob/6d9b1e5241ee08c77ff37a3d90d8ff3b6a90d87f/lua/oil/mutator/preview.lua#L61-L70

**Comment by stevearc** [comment]
Ah, makes sense. I've added that too!
