### ISSUE TITLE
feature request: make oil 'polite'

### ISSUE THREAD

**Issue by kaihowl** [stevearc/oil.nvim#76]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

"Polite" as described for [elihunter173/dirbuf.nvim](https://github.com/elihunter173/dirbuf.nvim):

> Polite: Plays nicely with tree-based file viewers like [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua), [fern.vim](https://github.com/lambdalisue/fern.vim), and [carbon.nvim](https://github.com/SidOfc/carbon.nvim).

It would be nice if Oil could be configured such that it does not assume full autonomy and add autocommands to take over all directory-style buffers. Instead, it should be possible to just invoke it based on the command `Oil` or the protocol/filetype `oil://`.

At any rate: Thank you for this great plugin. It works better than any other plugins I tried in the category of "edit-a-directory-as-if-it-is-a-text-buffer".

### Provide background

I want to use Carbon for most of my navigation as I for example want to navigate into subdirectories in a tree-style fashion without losing the context of the parent nodes. I.e., tree-style navigation vs netrw-style navigation.

Yet, whenever I need to restructure parts of the project, using Oil would come in handy.

**Comment by stevearc** [comment]
I've added a new `default_file_explorer` config options. If you set that to `false`, it should do what you want

**Comment by kaihowl** [comment]
Works splendidly! Thank you so much. :)

**Comment by textzenith** [comment]
Thanks for that one, I came looking for this.
