### ISSUE TITLE
feature request: Add action to yank the path of a file

### ISSUE THREAD

**Issue by primeapple** [stevearc/oil.nvim#86]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

What I'd love to see:
- Add an action to yank the relative path from the CWD
- Add an action to yank the absolute path

[Lir](https://github.com/tamago324/lir.nvim) does this pretty well, even though it misses the relative path yank option.

Mappings could be `gy` and `gY`. Even `C-y` would be sufficient.

**Comment by stevearc** [comment]
There is already an action to copy the absolute path: https://github.com/stevearc/oil.nvim/blob/fb8b101d7cb4727d8719ab6ed141330eca997d3f/doc/oil.txt#L305-L306

If you want to copy the relative path, you can use the same logic as the absolute path copy https://github.com/stevearc/oil.nvim/blob/fb8b101d7cb4727d8719ab6ed141330eca997d3f/lua/oil/actions.lua#L194-L204

And then perform the relative path transformation afterwards

```lua
local relpath = vim.fn.fnamemodify(filepath, ":.")
```
