### ISSUE TITLE
feature request: auto enable preview

### ISSUE THREAD

**Issue by IndianBoy42** [stevearc/oil.nvim#87]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would love to have a config option that makes the preview <C-p> automatically open when oil starts

### Provide background

I find i pretty much always want the preview open since I mostly open oil when trying to explore the filetree

**Comment by stevearc** [comment]
I've added a User autocmd that will fire when an oil buffer finishes rendering. You can use that to open the preview automatically
```lua
    vim.api.nvim_create_autocmd("User", {
      pattern = "OilEnter",
      callback = vim.schedule_wrap(function(args)
        local oil = require("oil")
        if vim.api.nvim_get_current_buf() == args.data.buf and oil.get_cursor_entry() then
          oil.select({ preview = true })
        end
      end),
    })
```
Note the `schedule_wrap` is required. There are some bugs with calling `oil.select` inside an autocmd; the `nested` option for BufReadCmd appears to not be respected :/

**Comment by jaydeland** [comment]
Quick update to the autocmd to use open_preview:
```bash
vim.api.nvim_create_autocmd("User", {
  pattern = "OilEnter",
  callback = vim.schedule_wrap(function(args)
    local oil = require("oil")
    if vim.api.nvim_get_current_buf() == args.data.buf and oil.get_cursor_entry() then
      oil.open_preview()
    end
  end),
})
```

**Comment by etherbound-dev** [comment]
> Quick update to the autocmd to use open_preview:
> 
> vim.api.nvim_create_autocmd("User", {
>   pattern = "OilEnter",
>   callback = vim.schedule_wrap(function(args)
>     local oil = require("oil")
>     if vim.api.nvim_get_current_buf() == args.data.buf and oil.get_cursor_entry() then
>       oil.open_preview()
>     end
>   end),
> })

This only works some of the times. If I open and close Oil sometimes preview opens automatically, other times it does not
