### ISSUE TITLE
feature request: add guardrail to prevent editing copied-in-buffer-but-not-saved file

### ISSUE THREAD

**Issue by maxh** [stevearc/oil.nvim#93]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I'm not sure if this is a bug or just user confusion. I think I'm looking for a dialog that prompts me to save file changes before editing copied files. See explanation below.

### Provide background

A common use case for me is:

- Open oil buffer with `_`
- Copy a filename say `file.txt` with `yyp`
- Rename the new filename with say `ct.newfile`
- `<Esc>` to exit edit mode
- *(Forget to `:w` to actually copy the file.)*
- `<CR>` on `newfile.txt` to edit new file
- Edit the new file and `:wa` to save all
- Get prompted by oil dialog to copy the file
- Push `o` to ok to the operation (aside: pushing `o` doesn't always seem to work, but haven't been able to reliably repro it not working)
- Now original file `file.txt` contents are overwritten with changes made while I thought I was in `newfile.txt`.

I'm not sure the best approach here, but I imagine something that prompts me to save the oil buffer to actually create `newfile.txt` before being able to edit it by pushing `<CR>`.

### Additional details

Open to other ideas / suggestions here.

**Comment by stevearc** [comment]
This is a tricky interaction. There's two similar cases here: editing a copied/moved file and editing a copied/moved directory. The solution I'm currently using is selecting a file or directory will open the location as it currently exists on disk. This I think works reasonably well in that it doesn't require any crazy hacks and the behavior is at least consistent and predictable, though it may not be intuitive.

I like your idea of prompting the user to save before continuing. I think it's a lot more attainable than trying to have "perfect" behavior, and I like that it feels aesthetically similar to the built-in `shortmess` option. This requires a bit more thought than I have time for right now; I'll think on it for a bit and come back to this when I get a chance.

**Comment by stevearc** [comment]
I've added a new default behavior: if you select a file or directory that is new, moved, or renamed, you will be prompted to save your changes. This behavior can be disabled via the `prompt_save_on_select_new_entry` config option. LMK if this works for you

**Comment by maxh** [comment]
I manually tested and this will work for me, thanks! A few minor thoughts FWIW:

- Showing the pending changes or changing the language to "Save pending file and directory changes?" could make it more clear this about changes in the oil buffer.
- If I copy the file but don't rename it, I don't get prompted. I'll open a separate issue about that.
