### ISSUE TITLE
feature request: toggle float windows

### ISSUE THREAD

**Issue by yujinyuz** [stevearc/oil.nvim#94]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Ability to toggle floating window

### Provide background

Thanks for this great plugin!

I'm coming from lir.nvim and one thing I've used is the `require('lir.float').toggle()`.

Would it be possible to implement this?

Or this there any work around I could use?

**Comment by nyngwang** [comment]
Maybe this could help: [nyngwang/NeoZoom.lua](https://github.com/nyngwang/NeoZoom.lua).

**Comment by stevearc** [comment]
Does the [open_float](https://github.com/stevearc/oil.nvim/#open_floatdir) function do what you want? There's also `:Oil --float` which does the same thing.

**Comment by yujinyuz** [comment]
@stevearc Sorry I wasn't clear about my post.

I was actually talking about that but I want it to work like the same way with `require('lir.float').toggle()` where if you call it, it opens the oil interface and if you call it again, it closes it

**Comment by stevearc** [comment]
Added toggle_float function!

**Comment by yujinyuz** [comment]
@stevearc awesome. thanks!
