### ISSUE TITLE
Failure to delete Lualine autocmds

### ISSUE THREAD

**Issue by bjjblackbelt** [stevearc/oil.nvim#97]
When opening a file as a split from a floating window, I received the following error:

> Error executing vim.schedule lua callback: ~/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:292: Failed to delete autocmd
> stack traceback:
>         [C]: in function 'nvim_del_autocmd'
>         ~/.local/share/nvim/lazy/oil.nvim/lua/oil/init.lua:292: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>

Out of my ~80 plugins, I tracked the issue down to Lualine. I am unfamiliar with Neovim or Lua development and therefore  cannot say if this bug should be added to the Lualine repo instead of here. However, I believe the `open_float()` function can be made more robust with the following change at line #291 in `lua/oil/init.lua`:

From: `vim.api.nvim_del_autocmd(id)`
To: `pcall(vim.api.nvim_del_autocmd, id)`

I'll create a pull-request if I get the time, but I figure someone else may be more qualified to make this change.

**Comment by stevearc** [comment]
Should be fixed now
